### ISSUE TITLE
FormC/ Use-of-Proceeds Document Icon Is Very Big.

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#1024]
@OstapL 
@MariaKravchuk please check this when the issue is cleared.
![screen shot 2016-10-07 at 9 43 32 am](https://cloud.githubusercontent.com/assets/1624001/19192205/7fe0b6d8-8c73-11e6-968d-326507992a4e.png)

**Comment by OstapL** [comment]
@arthuryip723 
Fixed
please check and close this issue
