### ISSUE TITLE
Education Links in "Raise Capital" aren't linking properly

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#1062]
![image](https://cloud.githubusercontent.com/assets/21956276/19291653/84618f06-8fe4-11e6-98bd-c009f6e3f109.png)

1. rename "Issuer Tutorial" to "Business Tutorial" and link it to the Business Tutorial in Resources
2. What's My Business Worth? Should go to this page:
![image](https://cloud.githubusercontent.com/assets/21956276/19291685/acfc110c-8fe4-11e6-9a74-1c75823c35ef.png)

3. How Much Should I Raise? should link to the right place in Resources

**Comment by OstapL** [comment]
@kenstaut 
Fixed 1 
Fixed 2
Fixed 3 #1067 
please check 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/company/create
