### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#108]
@NewRoman @leonstiel @vladyslav2 
1)Why here near "KRAVCHUK" does not exist icon for dropdown list like near the "Raise funds"?

![2016-08-23 15 34 05](https://cloud.githubusercontent.com/assets/20995691/17891984/92e18f2c-6947-11e6-976f-d58fee9ef4b6.png)

2)Please fix the names of buttons to "LOG IN" and "SIGN UP"

![2016-08-24 16 29 38](https://cloud.githubusercontent.com/assets/20995691/17932329/23b47c96-6a18-11e6-890d-292f22550f06.png)

**Comment by NewRoman** [comment]
1-2
https://github.com/NewRoman/gfwhitelabels/commit/c2584202bd543e8ef9fa42186e02d3ad2d14c98b

All points were done.

**Comment by NewRoman** [comment]
@MariaKravchuk Able to check
http://growthfountain-es7.s3-website-us-east-1.amazonaws.com/
