### ISSUE TITLE
Drifted Button in Raise Fund

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#1084]
![screen shot 2016-10-13 at 11 35 37 am](https://cloud.githubusercontent.com/assets/1624001/19355776/885c8678-9139-11e6-9f8e-b34446ee37cc.png)
@OstapL

**Comment by growthfountain** [comment]
@OstapL please check when you scale the browser down horizontally.  For example the social sign-up buttons do not scale gracefully 
![image](https://cloud.githubusercontent.com/assets/6185789/19368728/6e865bda-916f-11e6-8e04-0c200289ec31.png)

**Comment by OstapL** [comment]
@growthfountain 
Fixed social sign-up buttons
please check 
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/account/login

**Comment by OstapL** [comment]
@arthuryip723 
please check this 
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/company/create
