### ISSUE TITLE
Campaign Preview Design: Add 'Edit' Button

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#1094]
@MariaKravchuk 
We need to add an "Edit" button when the user is in the preview page of a campaign. And Ken wants that it is sticky when scrolling.
Thanks.

**Comment by growthfountain** [comment]
@MariaKravchuk we should also have a submit option.  For example, you complete the specifics page, you click preview, you want to make a change, you click edit to go back.  you click preview again, you like how it is now, you click submit.

**Comment by MariaKravchuk** [comment]
@OstapL I added in the layout two buttons (edit, submit). Let`s do it.
![2016-10-19 16 47 26](https://cloud.githubusercontent.com/assets/20995691/19521289/c02125be-961b-11e6-869d-272c0d51f513.png)

**Comment by OstapL** [comment]
@MariaKravchuk @growthfountain 
Fixed #1203 
check 
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/api/campaign/147
