### ISSUE TITLE
When No Images in The Gallery, The Preview/Detail Page Shows Broken Images.

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#1097]
![screen shot 2016-10-13 at 6 50 54 pm](https://cloud.githubusercontent.com/assets/1624001/19369868/22784c88-9176-11e6-8cef-cbf7066c5f5d.png)
@vladyslav2

**Comment by leonstiel** [comment]
This had been fixed but is reoccuring for some reason
