### ISSUE TITLE
Company Page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#112]
@OstapL @leonstiel @vladyslav2 

1) Why does the company name situated not in the center?
![2016-08-23 15 41 47](https://cloud.githubusercontent.com/assets/20995691/17892151/8325daa6-6948-11e6-8890-940e10c3404d.png)

2)Make a video window larger and at the center
![2016-08-23 16 07 50](https://cloud.githubusercontent.com/assets/20995691/17892874/10dd8c4c-694c-11e6-868d-c7c5f2ff55b5.png)

3) If the video close, you can see this. Fix it.
![2016-08-23 16 10 26](https://cloud.githubusercontent.com/assets/20995691/17892925/44dbf7e0-694c-11e6-87cd-e68d953ffa5d.png)

4)Check the spacing between lines in accordance with the design.
![2016-08-23 16 12 32](https://cloud.githubusercontent.com/assets/20995691/17892967/81b64c42-694c-11e6-9a4c-8771a531f495.png)

5)Also check the upper and lower padding in these elements
![2016-08-23 16 13 52](https://cloud.githubusercontent.com/assets/20995691/17893024/c21cce8c-694c-11e6-92df-7fda4b75a113.png)

6) If you press in the menu for example on Risks, it directs to the section Risks somehow not on top of this section.
![2016-08-23 19 21 19](https://cloud.githubusercontent.com/assets/20995691/17900297/661e6d5a-6967-11e6-95e0-6ab9e772e48f.png)

7) Why is not possible to view photos and videos here?!
![2016-08-23 19 27 12](https://cloud.githubusercontent.com/assets/20995691/17900366/ba06a16c-6967-11e6-91cb-6d163935799d.png)

**Comment by OstapL** [comment]
@MariaKravchuk @leonstiel 
Fixed1 http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign/43
Fixed2 http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign/43
Fixed3 http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign/43
Fixed4 http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign/43
Fixed5  http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign/43
