### ISSUE TITLE
ESTABLISHED BUSINESS VALUATION CALCULATOR

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1125]
1) This text should be above gray line
![2016-10-17 14 56 08](https://cloud.githubusercontent.com/assets/20995691/19436651/190398d6-947a-11e6-91bb-d34f958db656.png)

2) please make the name of bars on the center of each appropriate  charts
![2016-10-17 14 58 46](https://cloud.githubusercontent.com/assets/20995691/19436755/b46f22fe-947a-11e6-9251-e56ff98b9cb1.png)

See layout here:
https://www.dropbox.com/home/Maria%20Wireframes/CALCULATORS/Established%20Calculator/PSD?preview=Established+Calculator%3A+Finish.psd

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #1666 
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/calculator/establishedBusiness/finish
