### ISSUE TITLE
Typo in raise fund/specifics

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#1153]
![screen shot 2016-10-17 at 6 07 04 pm](https://cloud.githubusercontent.com/assets/1624001/19457600/13589b50-9495-11e6-942b-e21f32d07b6a.png)

@vladyslav2

**Comment by vladyslav2** [comment]
@arthuryip723 please check

**Comment by MariaKravchuk** [comment]
@vladyslav2 in the end of this text should be "they must be provided here"
