### ISSUE TITLE
BLOG

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#116]
@NewRoman  @leonstiel 

1)Why the word "blog" is not aligned to the left side of the menu (categories)?
![2016-08-23 20 00 37](https://cloud.githubusercontent.com/assets/20995691/17902336/9de05b06-696f-11e6-8bf7-b6d8df503003.png)

2)This title should be all capital letters
![2016-08-23 20 24 59](https://cloud.githubusercontent.com/assets/20995691/17902414/f9e838ec-696f-11e6-8456-f23368f27098.png)

3) Please check this button. It should not be a button large
![2016-08-23 20 29 33](https://cloud.githubusercontent.com/assets/20995691/17902589/90b5beca-6970-11e6-8fe7-b31c340794cc.png)

4)between this elements should be 50 pixels distance
![2016-08-23 20 32 25](https://cloud.githubusercontent.com/assets/20995691/17902679/d454f9fc-6970-11e6-9367-5d5d1155f4af.png)

5)Make this icon according to layout
![2016-08-23 20 33 35](https://cloud.githubusercontent.com/assets/20995691/17902734/234360ee-6971-11e6-8d0d-1960c2b7e631.png)

6)Under the lines of these elements must be 30 pixels everywhere
![2016-08-23 20 36 39](https://cloud.githubusercontent.com/assets/20995691/17902845/a3716fc2-6971-11e6-8345-aab8f5af1b17.png)
![2016-08-23 20 36 44](https://cloud.githubusercontent.com/assets/20995691/17902844/a3705768-6971-11e6-8fbc-52ca4a75c197.png)
![2016-08-23 20 36 50](https://cloud.githubusercontent.com/assets/20995691/17902846/a371bb12-6971-11e6-808b-24f25abb20e7.png)

**Comment by NewRoman** [comment]
1.
https://github.com/NewRoman/gfwhitelabels/commit/cbfbf14ba289f8b5f0bd9653cbdcfa301a967ba8
2.
https://github.com/NewRoman/gfwhitelabels/commit/284c150654424863436ebdaa9a8ca0ddf1908c8d
3. https://github.com/NewRoman/gfwhitelabels/commit/03552ac7f96786d44496ea438c7035cfe556a973
4 - 5
https://github.com/NewRoman/gfwhitelabels/commit/0d25685e019006d0e5f7ccd7a78adf5c05a3e34e
6.
https://github.com/NewRoman/gfwhitelabels/commit/7fd3fbeb5638773289556ab2e8335320b5736431

All points were done.

**Comment by NewRoman** [comment]
@MariaKravchuk able to check
http://growthfountain-es7.s3-website-us-east-1.amazonaws.com/pg/blogs

**Comment by MariaKravchuk** [comment]
@NewRoman Please add to this title the letter-spacing (200)
![2016-08-25 13 45 48](https://cloud.githubusercontent.com/assets/20995691/17966483/733eda60-6aca-11e6-9a55-4dff66bae68f.png)

**Comment by NewRoman** [comment]
Please add to this title the letter-spacing (200)

fixed here
https://github.com/NewRoman/gfwhitelabels/commit/8356864edce5bb47568e817478c17430b1e9ef09
