### ISSUE TITLE
DCU

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1173]
@NewRoman 
1) Please make all fonts and spaces on the sliders and bottom banner like in layout
![2016-10-18 16 42 58](https://cloud.githubusercontent.com/assets/20995691/19480431/01971f0e-9553-11e6-884f-9a1dc2663b70.png)

2)Change the image here like in layout
![2016-10-18 16 51 01](https://cloud.githubusercontent.com/assets/20995691/19480452/148dcd6a-9553-11e6-8cec-bae04117a98e.png)

3)On Education page make letter spacing 100 in the headings
![2016-10-18 16 56 17](https://cloud.githubusercontent.com/assets/20995691/19480636/d1040c0c-9553-11e6-8d30-7b9f954e8e8e.png)

4)Please make this section (Blog) like in Rivermark we have http://growthfountain-river-mark.s3-website-us-east-1.amazonaws.com/pg/blogs

![2016-10-18 17 15 28](https://cloud.githubusercontent.com/assets/20995691/19481519/e0b6a346-9556-11e6-97e3-cc1ca917f0bb.png)

5) Make the title of article in bold font
![2016-10-18 17 22 07](https://cloud.githubusercontent.com/assets/20995691/19481731/9c989858-9557-11e6-8eec-0aa0517cb87e.png)

6) Make this title with bold font (Campaign page)
![2016-10-18 18 23 28](https://cloud.githubusercontent.com/assets/20995691/19484355/00208392-9560-11e6-87ec-2498687101f6.png)

7)make this title in black color
![2016-10-18 18 24 06](https://cloud.githubusercontent.com/assets/20995691/19484390/1db40ae6-9560-11e6-987f-dc4a65887fed.png)

8) Make this filters like on GrowthFountain site (not rounded) 
![2016-10-21 11 33 24](https://cloud.githubusercontent.com/assets/20995691/19591943/3e59d694-9782-11e6-81a1-2360fed525ba.png)

See updated layout
https://www.dropbox.com/home/Maria%20Wireframes/White%20label%20sites/DCU?preview=DCU+index.psd

**Comment by NewRoman** [comment]
@MariaKravchuk 
1, 2, 4 ready

**Comment by NewRoman** [comment]
@MariaKravchuk 
all points done
