### ISSUE TITLE
Filters (List of Campaigns)

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1178]
@OstapL 
1)Fix this 3 filters
![2016-10-18 19 55 23](https://cloud.githubusercontent.com/assets/20995691/19487781/e143a2b2-956c-11e6-9a6b-8927ae6926b5.png)

They should work like the first filter "Industry"

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #1196 
check 
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/api/campaign
