### ISSUE TITLE
Delete Risks section on the Campaign page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1199]
@OstapL 
We should delete Risks on Campaign page. 
![2016-10-19 16 51 13](https://cloud.githubusercontent.com/assets/20995691/19521417/46902f00-961c-11e6-9112-08bdc84a9598.png)

![2016-10-19 16 51 49](https://cloud.githubusercontent.com/assets/20995691/19521439/5d8c49aa-961c-11e6-9855-d0c4f2f678e4.png)

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed 
#1203 
check 
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/api/campaign/147
