### ISSUE TITLE
Wrong error alignment

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1200]
@OstapL 
FIx this error alignment (Create Company)
![2016-10-19 17 47 50](https://cloud.githubusercontent.com/assets/20995691/19523875/8adda4b4-9624-11e6-8866-0c1bc89b243b.png)

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #1224 
check 
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/company/create
