### ISSUE TITLE
Sign up pop up

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1201]
@OstapL 
1) Please remove period after Privacy Policy. 
![2016-10-19 17 58 43](https://cloud.githubusercontent.com/assets/20995691/19524277/d8ec50f0-9625-11e6-83b8-3b77b0f854a2.png)

2)Add to "Electronic Signature and Electronic Delivery of Documentation» this link 
https://beta.growthfountain.com/pg/electronic_signature

3)Let each of this links will open in new page (not behind the pop up window)
![2016-10-19 18 01 06](https://cloud.githubusercontent.com/assets/20995691/19524359/220618d4-9626-11e6-8077-7339bd59f644.png)

**Comment by OstapL** [comment]
1 Fixed 
2 Fixed 
3 Fixed
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/account/signup
