### ISSUE TITLE
LLC’s can only issue a Revenue Share"

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1230]
@vladyslav2 
If user selects LLC only Payback/Revenue Share should be allowed (not common equity) with Pop-up saying "C-corps can choose to issue Common Equity or a Revenue Share.  LLC’s can only issue a Revenue Share"

**Comment by vladyslav2** [comment]
@arthuryip723 Arthur i added company information for get request

**Comment by vladyslav2** [comment]
so backend fixed

**Comment by arthuryip723** [comment]
thanks.

**Comment by MariaKravchuk** [comment]
@vladyslav2 Let`s add the tips with text "C-corps can choose to issue Common Equity or a Revenue Share. LLC’s can only issue a Revenue Share" on the Create Company page.
![2016-10-26 11 51 07](https://cloud.githubusercontent.com/assets/20995691/19719445/a4b48576-9b72-11e6-8d49-c357d4043e19.png)
