### ISSUE TITLE
Updates on Main Page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1286]
1)Make appearance of this section like in the layout (text, color link, image opacity)
![2016-10-21 12 10 30](https://cloud.githubusercontent.com/assets/20995691/19593264/61e4e58a-9788-11e6-9e34-78771892df05.png)

2)Please check here spaces and make them like in layout
![2016-10-21 12 19 57](https://cloud.githubusercontent.com/assets/20995691/19593381/0123a5c8-9789-11e6-88e7-c4f13eb42099.png)
![2016-10-21 12 20 03](https://cloud.githubusercontent.com/assets/20995691/19593382/0123ee84-9789-11e6-8554-c3daf69f35ee.png)
![2016-10-21 12 20 19](https://cloud.githubusercontent.com/assets/20995691/19593383/0126a124-9789-11e6-9bd8-e680fe755159.png)

3)Please update this section as I made in layout
![2016-10-21 12 25 08](https://cloud.githubusercontent.com/assets/20995691/19593492/8089a7c2-9789-11e6-95fc-e2a7591ab745.png)

4) Place DCU logo on the center regarding top logo
![2016-10-21 12 26 03](https://cloud.githubusercontent.com/assets/20995691/19593529/ad02fc0e-9789-11e6-9aa8-54630d6b198a.png)

See updated layout here:
https://www.dropbox.com/home/Maria%20Wireframes/Main%20page?preview=index.psd

**Comment by OstapL** [comment]
Fixed
check 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/
