### ISSUE TITLE
Pagination on List of Campaigns

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1287]
@vladyslav2 @arthuryip723 
I think we should show only 9 campaigns on the first page.
Therefore please make correct work of this pagination 
![2016-10-21 12 33 14](https://cloud.githubusercontent.com/assets/20995691/19593705/926fdd34-978a-11e6-966d-e485bb24d44a.png)

**Comment by vladyslav2** [comment]
@MariaKravchuk we finish this but we need to have more that 6 companies submited
