### ISSUE TITLE
Html updates for create campaign process

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1294]
@OstapL 
1)General Information
delete line after FAQ section
![2016-10-21 14 33 40](https://cloud.githubusercontent.com/assets/20995691/19597223/f32245b6-979b-11e6-8ea6-9c689be2ea63.png)

2)Media
Please check length of this line
![2016-10-21 15 21 36](https://cloud.githubusercontent.com/assets/20995691/19598200/2dae1a7e-97a2-11e6-8c98-097d9c8d5cbd.png)

3)Team members
Place the editing icon near delete icon. And make space under Member's name as in layout
![2016-10-21 14 53 23](https://cloud.githubusercontent.com/assets/20995691/19597669/9ac3a1e6-979e-11e6-8fa9-ab118465507a.png)

4)Specifics
- add to "How Much Should I Raise?" his link ( https://beta.growthfountain.com/calculator/whatmybusinessworth/intro )
![2016-10-21 15 01 55](https://cloud.githubusercontent.com/assets/20995691/19597798/7f2017ca-979f-11e6-967f-42fcbf63ae76.png)

- Delete letter spacing from headings "Here’s how Revenue Share works"
![2016-10-21 15 03 36](https://cloud.githubusercontent.com/assets/20995691/19597831/afecc6d2-979f-11e6-8c95-672088d33738.png)

5) And Make such icon for completed sections
![2016-10-21 15 18 36](https://cloud.githubusercontent.com/assets/20995691/19598111/ac435c42-97a1-11e6-9ab6-daffd27c96d4.png)

Layout see here
https://www.dropbox.com/home/Maria%20Wireframes/Create%20Company%20and%20Campaign/PSD?preview=04+CREATE+CAMPAIGN%3ASpecifics.psd

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed 1 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/general_information/116
Fixed 2 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/media/116
Fixed 3 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/team-members/116
Fixed 4 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/specifics/116
Fixed 5 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/general_information/116
check
