### ISSUE TITLE
PROFILE

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#130]
@vladyslav2  @NewRoman @leonstiel 
1) Change Title "Account" to "Profile" and tab "Account information" to "Profile informetion"
![2016-08-24 16 56 29](https://cloud.githubusercontent.com/assets/20995691/17933272/252fa6be-6a1c-11e6-84aa-9708d290c1c6.png)

2)Replace this caption on "Drop your profile photo here or click
to upload". Also make this icon like a link for uploading.
![2016-08-24 17 00 14](https://cloud.githubusercontent.com/assets/20995691/17933418/b4aa0848-6a1c-11e6-8d34-f10498e8e79b.png)

**Comment by NewRoman** [comment]
1-2
https://github.com/NewRoman/gfwhitelabels/commit/99221398e4fbcd6cbb9aff65e6a68ec92e82ce35

All fixed

**Comment by NewRoman** [comment]
@MariaKravchuk able to check
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/account/profile

**Comment by MariaKravchuk** [comment]
@NewRoman please review task 2! 
"Also make this icon like a link for uploading."
2016-08-24 17 00 14
