### ISSUE TITLE
OVERVIEW

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#131]
@NewRoman @leonstiel 
Check here the spaces between paragraphs and in the list according to our typography
![2016-08-24 17 09 22](https://cloud.githubusercontent.com/assets/20995691/17933799/1fe27b26-6a1e-11e6-95ce-52159304673f.png)

**Comment by NewRoman** [comment]
1
https://github.com/NewRoman/gfwhitelabels/commit/aba198f910bb9a8cced484a84f3794d835171d69

Done

**Comment by NewRoman** [comment]
@MariaKravchuk able to check
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/overview
