### ISSUE TITLE
Update Text on site for Beta Issuer Launch

### ISSUE THREAD

**Issue by leonstiel** [vladyslav2/gfwhitelabels#1330]
[Web Site Beta Full _ Alex Commentsv4KS.PPTX](https://github.com/vladyslav2/gfwhitelabels/files/545032/Web.Site.Beta.Full._.Alex.Commentsv4KS.PPTX)

Please update according to the attached document. Please double check each change, as this will be going out to Issuers.

**Comment by MariaKravchuk** [comment]
@arthuryip723 do you perform it?
