### ISSUE TITLE
Tweak spaces on Fundraising Description

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1338]
@OstapL 
1) When Revenue Share please change the spaces between the text blocks 
![2016-10-24 12 08 58](https://cloud.githubusercontent.com/assets/20995691/19639862/da922ca2-99e2-11e6-9528-4fb64ade4d8c.png)

**Comment by OstapL** [comment]
Fixed #1343 
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/api/campaign/113
