### ISSUE TITLE
Spelling on the Issuer dashboard

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1358]
@OstapL 
Please correct the spelling on the Issuer Dashboard page
Should be "Campaign" everywhere. 
![2016-10-25 13 04 55](https://cloud.githubusercontent.com/assets/20995691/19681830/a7ec69da-9ab3-11e6-82bf-c893c5f8d268.png)

**Comment by OstapL** [comment]
Fixed 
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/dashboard/issue-dashboard
