### ISSUE TITLE
Image squeezes on mobile device for white label sites

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#1369]
rivermark:
![image](https://cloud.githubusercontent.com/assets/21956276/19704148/a66eb920-9ad4-11e6-9687-f9467c6abf66.png)

jeanne darc:
![image](https://cloud.githubusercontent.com/assets/21956276/19704172/bd1a1a5c-9ad4-11e6-90a9-1ec616b8feef.png)

dcu
![image](https://cloud.githubusercontent.com/assets/21956276/19704216/dd7d08fe-9ad4-11e6-9e1e-5480db83e84f.png)

should recrop like the growthfountain site does:
![image](https://cloud.githubusercontent.com/assets/21956276/19704135/9370ce12-9ad4-11e6-941e-85d2ef4f3a66.png)

**Comment by OstapL** [comment]
@kenstaut 
Fixed 
Ken, please check
