### ISSUE TITLE
Fixes to some About us pages 

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1378]
@OstapL 
1)(Careers page ) Place  "Apply" button on the center. And make the space above button 50 px
![2016-10-26 13 11 41](https://cloud.githubusercontent.com/assets/20995691/19722105/dd5d777e-9b7d-11e6-9f4d-f088c3982149.png)

2)Tweak places of "In the News" and "FAQ" sections oj the side menu. First should be "In the News"
![2016-10-26 13 12 58](https://cloud.githubusercontent.com/assets/20995691/19722180/23b9405e-9b7e-11e6-9463-c1d94e23bbf4.png)

3)Add to "In the News page" side "About us" menu
![2016-10-26 13 15 08](https://cloud.githubusercontent.com/assets/20995691/19722207/4ff5f928-9b7e-11e6-8c44-22941c3c6814.png)

**Comment by OstapL** [comment]
Fixed 1 http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/pg/careers
Fixed 2 
Fixed 3 http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/pg/news
#1380
