### ISSUE TITLE
Complete Company page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1387]
@arthuryip723 @
If user completes create Company process on the side menu should be check mark in appropriate place. 
![2016-10-26 17 51 21](https://cloud.githubusercontent.com/assets/20995691/19731320/b67341de-9ba5-11e6-9162-c7ebe94a1376.png)

**Comment by arthuryip723** [comment]
ok. i'll be working on this.
