### ISSUE TITLE
revenue share calculator

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#1397]
and calculator should not say "Congratulations, Revenue Share Contract is complete!" unless 2x the investment has been returned. 
![image](https://cloud.githubusercontent.com/assets/21956276/19735182/7601600e-9b78-11e6-9bfe-65a5ff4b2305.png)

**Comment by OstapL** [comment]
change text #1434 
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/calculator/paybackshare/step-1
