### ISSUE TITLE
Error on Preview->Submit ->Edit Specifics 

### ISSUE THREAD

**Issue by growthfountain** [vladyslav2/gfwhitelabels#1418]
Ken had this error and I was able to recreate it:
1) I entered Company Info
2) I save & continued to the next page, and then clicked Preview
3) I clicked Submit from the Preview page
4) It popped up a section to EDIT, I clicked on Specifics.
5) I got the errors in the attached image

![image](https://cloud.githubusercontent.com/assets/6185789/19747227/69f26ae4-9ba8-11e6-80bf-c021e18e49df.png)

![image](https://cloud.githubusercontent.com/assets/6185789/19747253/9b8e406e-9ba8-11e6-8e0e-6ba1bbfa5518.png)

**Comment by growthfountain** [comment]
Also occurs if you submit from the Specifics page when it's unpopulated

**Comment by vladyslav2** [comment]
@growthfountain @arthuryip723 it is javascript issue
Arthur should be able to fix this
