### ISSUE TITLE
Updates to Form C Review

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1457]
@OstapL 
Please add new changes to the Form C Review page:
- "Submit" buttons
- Pop up

And make HTML for Congratulations on submitting page (which we`ll have after submitting of Form C)

All layouts for this task here:
https://www.dropbox.com/home/Maria%20Wireframes/Form%20C/Form%20C%20Review

**Comment by OstapL** [comment]
Fixed #1463
