### ISSUE TITLE
Text Changes as per Ken's Request

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#1462]
[Comments to Calculators KS.pptx](https://github.com/vladyslav2/gfwhitelabels/files/558779/Comments.to.Calculators.KS.pptx)
Work for @OstapL :
/calculator/paybackshare/step-1
/calculator/whatmybusinessworth/intro
/calculator/establishedBusiness/intro
/calculator/capitalraise/intro
They correspond to slid 1, 3, 8, 9 of the .pptx.

Please tweak the warning content at the bottom of the pages to make it look good. There seems to be no previous designs for this. Thus you can consult @MariaKravchuk for that if necessary.
Let me know if you have any questions. Thanks.

**Comment by MariaKravchuk** [comment]
@arthuryip723 do you already completed it or will do it yet?

**Comment by arthuryip723** [comment]
I think I finished most. And I need to work with ostap a bit to wrap it up. The thing is my pull request is pending for Vlad's approval. Is he in today?

**Comment by OstapL** [comment]
@arthuryip723 @MariaKravchuk 
Fixed 1 3 8 9 
#1479
