### ISSUE TITLE
Cannot "Save & Continue" to Perks page if "Specifics" is completely blank

### ISSUE THREAD

**Issue by growthfountain** [vladyslav2/gfwhitelabels#1465]
It shows errors for Max Value > Min Value, etc.

**Comment by vladyslav2** [comment]
@growthfountain @arthuryip723 Arthur ?

**Comment by arthuryip723** [comment]
![screen shot 2016-11-01 at 2 41 15 pm](https://cloud.githubusercontent.com/assets/1624001/19905141/dd13ccd2-a04b-11e6-84aa-c539d67d51c4.png)
![screen shot 2016-11-01 at 2 41 30 pm](https://cloud.githubusercontent.com/assets/1624001/19905140/dd12dd0e-a04b-11e6-89f9-7a3dd99fc8a5.png)
Backend prevents me from clicking 'save and continue' to go through specifics with default values(0's).
@vladyslav2
