### ISSUE TITLE
Add Spinner to Gallery

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1470]
Add Spinner to Gallery when uploading photos 
![2016-10-31 11 32 39](https://cloud.githubusercontent.com/assets/20995691/19849798/c23421d0-9f5d-11e6-817c-67157f0abe48.png)

**Comment by arthuryip723** [comment]
@MariaKravchuk @growthfountain 
this should have been fixed. please check. Thanks.
