### ISSUE TITLE
Add to JDCU white label site

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#1507]
Please add this disclaimer to the bottom of the beta.jdcu.growthfountain.com

The investment opportunities and/or products offered through GrowthFountain are not insured by Jeanne D'Arc Credit Union. Deposits/investments are not insured by the National Credit Union Administration (NCUA) or the Massachusetts Share Insurance Corporation (MSIC). These investment opportunities/products are not obligations of Jeanne D’Arc Credit Union and are not endorsed, recommended or guaranteed by Jeanne D'Arc Credit Union or any government agency. The value of the investment may fluctuate, the return on the investment is not guaranteed, and loss of principal is possible. Jeanne D'Arc Credit Union is not a registered broker-dealer nor are they affiliated with GrowthFountain. Jeanne D'Arc Credit Union has contracted with GrowthFountain to make potential non-deposit investment opportunities and products available to credit union members. 

![image](https://cloud.githubusercontent.com/assets/21956276/19945019/92603116-a114-11e6-9244-843bae6cf8a6.png)

**Comment by MariaKravchuk** [comment]
@OstapL look here https://www.dropbox.com/home/Maria%20Wireframes/White%20label%20sites/Jeanna%20D'Arc?preview=JD+index.psd

**Comment by OstapL** [comment]
@MariaKravchuk @kenstaut 
Fixed #1524 
http://growthfountain-jeanne-darc.s3-website-us-east-1.amazonaws.com/
