### ISSUE TITLE
Change <title> for all white label sites

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1518]
@OstapL 
Change <title> for all white label sites
![2016-11-03 19 24 54](https://cloud.githubusercontent.com/assets/20995691/19977150/46a418f4-a1fb-11e6-8700-58ce660a7456.png)

For jeanna D`Arc:
Crowdfunding I Jeanne D'Arc CU 

For DCU:
Crowdfunding I Digital Federal Credit Union

For Rivermark:
Crowdfunding I Rivermark Community CU

**Comment by OstapL** [comment]
Fixed #1523
