### ISSUE TITLE
Raise Capital: Specifics Page on IE

### ISSUE THREAD

**Issue by growthfountain** [vladyslav2/gfwhitelabels#1526]
Please check and fix the Specifics page within Raise Capital on IE.

1) Clicking Preview should save the content
2) Cannot move forward without entering data
3) Incorrect Error messages

![](https://files.slack.com/files-pri/T02LSJYBU-F2YHVQMD4/pasted_image_at_2016_11_03_03_07_pm.png)

**Comment by MariaKravchuk** [comment]
@growthfountain the same problems we have not only on IE.
