### ISSUE TITLE
campaign listing page/3 of shares

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1529]
![image](https://cloud.githubusercontent.com/assets/21366183/20022655/f01d93ae-a2b1-11e6-8875-d489e3a88a80.png)

![image](https://cloud.githubusercontent.com/assets/21366183/20022665/ffdf0926-a2b1-11e6-9fab-b1847f8bf1ef.png)

"number of shares" value should equal "minimum # of shares"

**Comment by vladyslav2** [comment]
@arthuryip723 can you take a look please ?

**Comment by arthuryip723** [comment]
@vladyslav2 sure.
