### ISSUE TITLE
Paragraphs are not displayed on the Сampaign Page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#1531]
@arthuryip723 
Let`s do all paragraphs in the texts on Campaign page as we have in the Raise capital forms.

![2016-11-07 14 13 02](https://cloud.githubusercontent.com/assets/20995691/20057474/54ff6678-a4f4-11e6-9c3a-591222b64f9b.png)

![2016-11-07 14 13 35](https://cloud.githubusercontent.com/assets/20995691/20057489/68038196-a4f4-11e6-86ae-e8d30fef21ce.png)

**Comment by arthuryip723** [comment]
Sure. I'll look at this today.
