### ISSUE TITLE
BLOG/Article

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#161]
@NewRoman @leonstiel 
1) make this inscription separately "DECEMBER 10"
![2016-08-25 20 01 38](https://cloud.githubusercontent.com/assets/20995691/17978689/df9bfb54-6aff-11e6-92e6-eacf992ddc81.png)

2)This should not be a button. Еhere should be the same pagination as on the Blog page or Campaign List.
![2016-08-25 20 10 12](https://cloud.githubusercontent.com/assets/20995691/17978831/8a5c1420-6b00-11e6-93c0-fb32f14d25ad.png)

3)Why text does not equalized with the image? (Blog page)
![2016-08-25 20 24 17](https://cloud.githubusercontent.com/assets/20995691/17979173/fcac3c02-6b01-11e6-83db-c19e8892dd9b.png)

4)Why line under the title such short? (Blog page)
![2016-08-25 20 25 40](https://cloud.githubusercontent.com/assets/20995691/17979279/72a49dfa-6b02-11e6-8e9c-46ce19441a35.png)

5)Align content to the right. (Blog page)
![2016-08-25 20 29 15](https://cloud.githubusercontent.com/assets/20995691/17979339/ba19dd9e-6b02-11e6-8e4f-c99b2107c115.png)

**Comment by NewRoman** [comment]
1-2
https://github.com/NewRoman/gfwhitelabels/commit/bb4c9b459d1bfecdf1e01839e258e3170dec91fd
3, 5
https://github.com/NewRoman/gfwhitelabels/commit/9e5a46d6c626a295633a5a305f0ab5e1cfd19bed
4.
https://github.com/NewRoman/gfwhitelabels/commit/eb2f979ae319a528521771c0d10637b096381d70

All points were done

**Comment by NewRoman** [comment]
@MariaKravchuk ready to check 
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/oneblog
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/blogs

**Comment by MariaKravchuk** [comment]
@NewRoman Please make the same space between side menu and content according to layout, that I have just sent to you.
![2016-08-25 23 49 52](https://cloud.githubusercontent.com/assets/20995691/17985541/fb2e9a88-6b1e-11e6-9fe7-1478ba17f9a1.png)

**Comment by NewRoman** [comment]
@MariaKravchuk 
ready
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/blogs
