### ISSUE TITLE
Marks

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#163]
@NewRoman @OstapL @leonstiel 
Roman and Ostap why do you have different bulleted points?
![2016-08-25 21 36 25](https://cloud.githubusercontent.com/assets/20995691/17981535/c5d00a32-6b0c-11e6-80ed-746f4965373c.png)
![2016-08-25 21 36 36](https://cloud.githubusercontent.com/assets/20995691/17981536/c5d29d06-6b0c-11e6-9e8f-bd2060634889.png)

**Comment by NewRoman** [comment]
я для этих страниц добавил свои точки(на клас .simple-list c елементом <i> перед текстом елемента <li>) так как на нижнем скрине, поскольку на дизайне от Марии они меньше чем стандартные.

@OstapL @MariaKravchuk 

какие все таки точки берем за основу? у кого какие идеи?

**Comment by MariaKravchuk** [comment]
@NewRoman зроби так як у Остапа, жирніші точки.

**Comment by NewRoman** [comment]
@MariaKravchuk 
fixed

**Comment by NewRoman** [comment]
@MariaKravchuk 
ready to check
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/overview
