### ISSUE TITLE
PRIVACY POLICY

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#165]
@OstapL @leonstiel 
Align the side menu sections so they do not go beyond the top line.
![2016-08-25 21 43 26](https://cloud.githubusercontent.com/assets/20995691/17981710/773792ea-6b0d-11e6-8ce0-9b7da67b5ca5.png)

**Comment by NewRoman** [comment]
done here 
https://github.com/NewRoman/gfwhitelabels/commit/eb2f979ae319a528521771c0d10637b096381d70

**Comment by OstapL** [comment]
@MariaKravchuk  @leonstiel
Fixed
