### ISSUE TITLE
Issue#170. On page news there are no correct name in the top

### ISSUE THREAD

**Issue by NewRoman** [vladyslav2/gfwhitelabels#170]
![_093](https://cloud.githubusercontent.com/assets/8603994/17984628/c4932182-6b1a-11e6-9dfb-6bceea03bcba.png)

**Comment by NewRoman** [comment]
@MariaKravchuk 
check it please and close issue.

able to check on
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/news

**Comment by MariaKravchuk** [comment]
@NewRoman not "News" but "In the  news"

**Comment by NewRoman** [comment]
@MariaKravchuk 
ready
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/news
