### ISSUE TITLE
Final review

### ISSUE THREAD

**Issue by OstapL** [vladyslav2/gfwhitelabels#1732]
первая страница поле security_type

The date of this offering material being listed on the funding portal at www.GrowthFountain.com is 1995-03-02 - нужно ставить текущую дату

Type of security offered: - campaign.security_type - не работает 

CHANGES ARE POSSIBLE IN CERTAIN CIRCUMSTANCES 
 https://growthfountain.com/1 - ссылка на компанию 

Ability of one class of security to materially limit, dilute or qualify the rights of another class:
Ability of any principal shareholders to affect the purchasers of the securities being offered
 тут так же не могу найти поля 

Method by which the offered securities are valued:
 campaign.valuation_determination_other - такого нет 

METHOD FOR DELIVERING THE SECURITIES - текст нужно сделать field в  view файле 

CAPITAL STRUCTURE OF THE ISSUER 
 Class of Security - должен быть селект 

 
нужно проверить поле Principal Business
EXHIBIT C: BIOGRAPHIES

**Comment by vladyslav2** [comment]
> 1995-03-02 - нужно ставить текущую дату

Поправил

> Type of security offered: - campaign.security_type - не работает
просто в 65й форме какая-то проблема с security_type буду смотреть

> CHANGES ARE POSSIBLE IN CERTAIN CIRCUMSTANCES
https://growthfountain.com/1 - ссылка на компанию

поправил

**Comment by MariaKravchuk** [comment]
Секція INTERMEDIARY COMPENSATION, мають тягнутися проценти "trans_percent" (з можливістю редагувати)

**Comment by MariaKravchuk** [comment]
Секція Intermediary Compensation, мають тягнутися поля 
"registration_fee" 
"party_fees"
"fees_to_investor"
 "trans_percent"

**Comment by MariaKravchuk** [comment]
Перевірити чи підтягується інфа в DESCRIPTION OF SECURITIES, MATERIAL TERMS AND OTHER RIGHTS

**Comment by MariaKravchuk** [comment]
Повинні підтягуватися дані в таблицю в секції ASSUMING A MAXIMUM RAISE

**Comment by MariaKravchuk** [comment]
Секція Prior Operating History повинно підтягуватися operating_history

**Comment by vladyslav2** [comment]
@MariaKravchuk пиши новые issue, не пиши тут
я уже запутался что исправлено а что нет
