### ISSUE TITLE
BLOG/Article

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#178]
@NewRoman @leonstiel 
1)Add here please letter-spacing in words (200).
![2016-08-26 14 21 39](https://cloud.githubusercontent.com/assets/20995691/18003987/c1001870-6b99-11e6-9d79-8a455c1b0ee5.png)

2)This
 pagination look good, but add here letter spacing too.
![2016-08-26 14 26 23](https://cloud.githubusercontent.com/assets/20995691/18004002/d6fca9ea-6b99-11e6-8b3e-bd5308658e22.png)

**Comment by NewRoman** [comment]
1-2 fix
https://github.com/NewRoman/gfwhitelabels/commit/6970cf255c0ae0ef02fb34b435f38ffdb2810260

**Comment by NewRoman** [comment]
@MariaKravchuk 
ready to check
