### ISSUE TITLE
In the news

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#179]
@NewRoman @leonstiel 
Please delete this gray line under the last article.
![2016-08-26 14 37 56](https://cloud.githubusercontent.com/assets/20995691/18004199/f9824348-6b9a-11e6-8478-84df449d749e.png)

**Comment by NewRoman** [comment]
fix
https://github.com/NewRoman/gfwhitelabels/commit/6970cf255c0ae0ef02fb34b435f38ffdb2810260

**Comment by NewRoman** [comment]
@MariaKravchuk 
ready to check
