### ISSUE TITLE
Replace the document for Common Equity and Revenue Share

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#1816]
![image](https://cloud.githubusercontent.com/assets/21956276/20814243/dfc9f6f6-b7e6-11e6-8ce1-2b2f08bbc15b.png)
[GrowthFountain Security Description.pdf](https://github.com/vladyslav2/gfwhitelabels/files/625832/GrowthFountain.Security.Description.pdf)

**Comment by OstapL** [comment]
Fixed #1818

**Comment by kenstaut** [comment]
Please check on form c site
