### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#182]
@NewRoman @leonstiel 
Change please sections in LEGAL. There should be "Terms of Use" and "Privacy Policy". 
![2016-08-26 15 07 42](https://cloud.githubusercontent.com/assets/20995691/18004970/dad702e4-6b9f-11e6-899a-2ab5d04e6f72.png)

**Comment by NewRoman** [comment]
fix in this commit
https://github.com/NewRoman/gfwhitelabels/commit/27c14e38bc7f9b02fe83fd0bd2a42b324c4c35c5

**Comment by NewRoman** [comment]
@MariaKravchuk 
ready to check
