### ISSUE TITLE
Profile Page HTML/CSS Issue

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#1851]
@OstapL 
Hello Ostap,
I added a line just like the lines above, but the effect looks weird. Please help fix this. Thanks.
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/account/profile
![screen shot 2016-12-05 at 12 24 28 pm](https://cloud.githubusercontent.com/assets/1624001/20895079/fb5ae040-bae5-11e6-87b7-2f28700e6508.png)

**Comment by OstapL** [comment]
@arthuryip723 
fixed
