### ISSUE TITLE
HTML/CSS Tweaking for Investment Page

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#1876]
@OstapL 
Could you work on the HTML/CSS of the the investment page to make them look like what we want?
![screen shot 2016-12-07 at 9 45 41 am](https://cloud.githubusercontent.com/assets/1624001/20972594/5a038d26-bc63-11e6-90ba-3454145aa3d8.png)
![screen shot 2016-12-07 at 9 45 56 am](https://cloud.githubusercontent.com/assets/1624001/20972595/5a05a5ac-bc63-11e6-81b7-fbe5ef889dcf.png)

**Comment by OstapL** [comment]
FIxed
