### ISSUE TITLE
form c/intro page/payment notification

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1887]
we need to create a message when user enters correct credit card in form c intro page.

Please ask maria for design.

message will say" "Thank you for your payment, you can now complete your Form C"

![image](https://cloud.githubusercontent.com/assets/21366183/20985219/89583468-bc91-11e6-9d9c-b2b86ae929bb.png)

**Comment by OstapL** [comment]
@morganm24 
Fixed 
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/formc/27/introduction
Please Check
