### ISSUE TITLE
campaign setup/media page/cropping tool

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1889]
@arthuryip723 can we maintain ratio... NOT NOIW

When I upload photo and adjust cropping tool, the image border does not match in preview campaign
cropping tool-
![image](https://cloud.githubusercontent.com/assets/21366183/20988227/d41f5042-bc9d-11e6-94ff-0ff21983fd76.png)

campaign preview-
![image](https://cloud.githubusercontent.com/assets/21366183/20988240/ee01109a-bc9d-11e6-8d12-5da487a47067.png)

**Comment by vladyslav2** [comment]
@arthuryip723 i think you can fix this

**Comment by arthuryip723** [comment]
@vladyslav2 Sure.

**Comment by vladyslav2** [comment]
@arthuryip723 have you had any chance to fix this ?

**Comment by arthuryip723** [comment]
@vladyslav2 it's in my pipeline. but I haven't started on this yet.

**Comment by arthuryip723** [comment]
Probably. I should be able to wrap up the use of proceeds restoration quickly. then I'll be on it. @vladyslav2

**Comment by MariaKravchuk** [comment]
@morganm24 @vladyslav2 @arthuryip723 Maybe I do not understand this issue precisely but I think we have such situation because of parallax effect on main header image. And in this case it is normally.
