### ISSUE TITLE
campaign setup/Doing Business As

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1890]
"Doing Business As" -not required but if it filled out it should replace the default company name is campaign preview but not form c

![image](https://cloud.githubusercontent.com/assets/21366183/20988331/4bd510c2-bc9e-11e6-935d-ed2b57fbb3e6.png)

![image](https://cloud.githubusercontent.com/assets/21366183/20988342/59525368-bc9e-11e6-9550-09ef31cbe5e2.png)

make sure campaign thumbnail also uses doing business as
![image](https://cloud.githubusercontent.com/assets/21366183/20988425/b903bb44-bc9e-11e6-9fa2-a806ef4cf1b5.png)

**Comment by vladyslav2** [comment]
@morganm24 can you check please if haven't miss anything ?
