### ISSUE TITLE
campaign setup/media/gallery

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1891]
cropping tool only appears for first image uploaded in gallery. after you crop photo 1 then you can no long crop any more photos.

![image](https://cloud.githubusercontent.com/assets/21366183/20988740/0367dc6e-bca0-11e6-9bd5-c9171ab900de.png)

**Comment by vladyslav2** [comment]
@morganm24 can you check please ?

**Comment by morganm24** [comment]
lets work on this in a few weeks.. not important right now
