### ISSUE TITLE
form c/team member/ officer/format

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1894]
please change format to look like this-
TEXT: Previously held a different position with the issuer?  Please list them:
TEXT: If you’ve been at your current employer fewer than 3 years, please provide additional information below:
@vladyslav2 
![image](https://cloud.githubusercontent.com/assets/21366183/20989304/35a8c4d4-bca2-11e6-8cfd-a819cdf2ef9d.png)
![image](https://cloud.githubusercontent.com/assets/21366183/20989312/3bebed30-bca2-11e6-92ad-2ab1a2fc2df3.png)

**Comment by OstapL** [comment]
Fixed

**Comment by morganm24** [comment]
I working with @vladyslav2 on this

**Comment by OstapL** [comment]
@morganm24 
ok, but I close this issue because  is copy https://github.com/vladyslav2/gfwhitelabels/issues/1897
