### ISSUE TITLE
Create Company

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#190]
@OstapL @vladyslav2 @leonstiel 
1)What does mean help button? Here you need to add some appropriate text.
Also check this title according to the layout. Between the two lines of the title should be 13 pixels. The bottom line of this title should be size 14.
![2016-08-26 18 24 03](https://cloud.githubusercontent.com/assets/20995691/18010922/5e56be5a-6bbb-11e6-82fe-2caef2d30e9a.png)

2)Change widget to any other. This is very inconvenient.
![2016-08-26 18 42 13](https://cloud.githubusercontent.com/assets/20995691/18011224/d5eec45c-6bbc-11e6-834e-7cb2df702668.png)

And here we have not correct format in error message
![2016-08-26 21 32 47](https://cloud.githubusercontent.com/assets/20995691/18016399/dd525660-6bd4-11e6-9ad2-03c7b09472b6.png) 
It should be mm-dd-yyyy and in paralel the same in the box.

3)When you re-enter some information - input field becomes yellow, even if you already entering data in another field.
![2016-08-26 18 43 15](https://cloud.githubusercontent.com/assets/20995691/18011339/62614482-6bbd-11e6-8834-7e239dcbe475.png)
![2016-08-26 18 45 37](https://cloud.githubusercontent.com/assets/20995691/18011340/6263f790-6bbd-11e6-962d-588c4725f4cc.png)

4)The section of the zip code is not working
![2016-08-26 18 46 57](https://cloud.githubusercontent.com/assets/20995691/18011374/91274172-6bbd-11e6-87e6-5c375e49242c.png)

5)If all required fields not filling - the system shows us following error.
![2016-08-26 18 49 00](https://cloud.githubusercontent.com/assets/20995691/18011476/0e86cd7c-6bbe-11e6-8e67-6c941d6ab96f.png)
I propose the following form of errors with highlighting of the box:
![2016-08-26 21 30 58](https://cloud.githubusercontent.com/assets/20995691/18016323/72aba3ac-6bd4-11e6-8c78-b084e62cb49a.png)

6)If a user already corrected the mistake, why the text of the error does not disappear?
![2016-08-26 18 55 56](https://cloud.githubusercontent.com/assets/20995691/18011807/51224ade-6bbf-11e6-89fc-a0feefb942e3.png)

7)Or if a person does not corrected the error, it is not necessary that there appeared additional message about errors.
![2016-08-26 19 02 31](https://cloud.githubusercontent.com/assets/20995691/18012287/976e8c76-6bc1-11e6-9791-8fd0575783ea.png)

8)If user does not fill some required field, the system should forward him to the place of this field.

9) Nothing happens when I click on this icon (arrow) of drop-down list.
![2016-08-26 21 39 55](https://cloud.githubusercontent.com/assets/20995691/18016607/e2e42508-6bd5-11e6-9779-543319519a94.png)

10) Please, change here the labels in the fields by default on MM YYYY
![2016-08-29 21 56 06](https://cloud.githubusercontent.com/assets/20995691/18063478/bce6150e-6e33-11e6-8e33-e36f4011fcc5.png)

**Comment by vladyslav2** [comment]
1) @OstapL must fix this

**Comment by vladyslav2** [comment]
3) @OstapL task

**Comment by vladyslav2** [comment]
@MariaKravchuk can you check please 5, 6, 7

For other tasks  i will need @OstapL help and for task 5 too

**Comment by vladyslav2** [comment]
here is a link for testing http://growthfountain-es7.s3-website-us-east-1.amazonaws.com/company/create

**Comment by MariaKravchuk** [comment]
@vladyslav2 you complete only 6 and 7
