### ISSUE TITLE
form c/team member page/full time employee not saved

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1900]
criteria for full time employees and part time employees does not save after user  adds information director, officer and shareholder.

![image](https://cloud.githubusercontent.com/assets/21366183/20990730/4d7e2b84-bca8-11e6-9b05-788433825e07.png)

**Comment by vladyslav2** [comment]
@morganm24 do you want to update those values automatically when you add new member ?

**Comment by vladyslav2** [comment]
Just for myself: if i enter data to inputs and click add director right away data will not be saved

**Comment by vladyslav2** [comment]
Fixed
