### ISSUE TITLE
form c final review/PAGE 3

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1909]
PAGE 3
please change date to mm/dd/yyyy

add space in between investment and in

![image](https://cloud.githubusercontent.com/assets/21366183/21018026/5bc1084c-bd39-11e6-901f-b39a02387597.png)

**Comment by OstapL** [comment]
@morganm24 @MariaKravchuk 
Fixed add space investment

**Comment by morganm24** [comment]
can we fix date format? @OstapL @MariaKravchuk
