### ISSUE TITLE
FORM C/FINAL REVIEW/PAGE 1

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1912]
PAGE 1
please delete "OFFERING PRICE: $0 IN DEBT SECURITIES" 

![image](https://cloud.githubusercontent.com/assets/21366183/21018839/671ae2c8-bd3c-11e6-8217-540a9e2b5808.png)

**Comment by OstapL** [comment]
@morganm24 @MariaKravchuk 
Fixed #1918
