### ISSUE TITLE
form c final review

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1926]
the wrong dates are matched. please change

take date from here
![image](https://cloud.githubusercontent.com/assets/21366183/21026599/5fcc9592-bd5b-11e6-814b-7959d8263a84.png)

![image](https://cloud.githubusercontent.com/assets/21366183/21026580/49f057c2-bd5b-11e6-877c-dfc477109c96.png)

**Comment by vladyslav2** [comment]
@morganm24 You want all dates on the final review to be in the format MM-DD-YYYY, correct ?
