### ISSUE TITLE
Investor tutorial

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#1931]
7th slide misspelling
should be "an"
![image](https://cloud.githubusercontent.com/assets/21956276/21028775/aeec2526-bd64-11e6-88a7-3ecc47383da4.png)

**Comment by OstapL** [comment]
@kenstaut @MariaKravchuk 
Fixed #1951

**Comment by vladyslav2** [comment]
@kenstaut ?
