### ISSUE TITLE
Company Page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#194]
@vladyslav2 @leonstiel @OstapL 

8)Please Correct accordions. Active accordion should be as the first here. Icons (arrows) should change according to the activity of the accordion.
![2016-08-26 23 18 19](https://cloud.githubusercontent.com/assets/20995691/18019207/ba2d3c40-6be3-11e6-842c-46565f22af26.png)

10)If you click on the button to ask questions and have not yet registered, there must emerge a popup with a form to register or login.
![2016-08-26 23 23 07](https://cloud.githubusercontent.com/assets/20995691/18019343/44deb56c-6be4-11e6-96b5-968e33b7ed42.png)

11)When the user will click on the arrow, bottom commentary should hide.
![2016-08-26 23 25 35](https://cloud.githubusercontent.com/assets/20995691/18019393/89d0b116-6be4-11e6-8bab-5fa50e67ad87.png)

12)In general, a comment system is not working.
![2016-08-26 23 27 27](https://cloud.githubusercontent.com/assets/20995691/18019433/c0be97f6-6be4-11e6-8e6a-ac3ed0f6fea9.png)

**Comment by vladyslav2** [comment]
8) Fixed, check
13) Fixed, check

**Comment by vladyslav2** [comment]
@MariaKravchuk
