### ISSUE TITLE
beta site/campaign setup/specifics page

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1954]
"0" is prepopulated so page is registering as complete.
make sure that user enters value into Pre-money valuation and Price Per Share 

![image](https://cloud.githubusercontent.com/assets/21366183/21065531/cf6dfb42-be2e-11e6-8755-83849e0e0bdb.png)

**Comment by vladyslav2** [comment]
i feel like i need to discuss this issue with a @leonstiel
