### ISSUE TITLE
form c/background check page

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1963]
Do not default to NO. Please make empty for both. user must choose

![image](https://cloud.githubusercontent.com/assets/21366183/21066446/9d725660-be33-11e6-94c0-701edd468cd1.png)

**Comment by vladyslav2** [comment]
@morganm24 please check

**Comment by arthuryip723** [comment]
![screen shot 2016-12-15 at 3 23 11 pm](https://cloud.githubusercontent.com/assets/1624001/21240740/94a5ef82-c2da-11e6-9ae8-cea0c99ff8ef.png)
Here's the GET response for that page.
I used a newly registered account. But the choice field comes with false by default. Thus the question is: Can we make it to be empty when first created? Other wise the front-end doesn't know whether it is newly created or the user choose to answer false previously.
@vladyslav2
