### ISSUE TITLE
account setup/save button

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1968]
please change "SAVE" to "Save and Continue"

![image](https://cloud.githubusercontent.com/assets/21366183/21075229/634dafaa-beda-11e6-8de9-76bc9b518823.png)

**Comment by OstapL** [comment]
@morganm24
Fixed #2243

**Comment by morganm24** [comment]
The button still saves save

![image](https://cloud.githubusercontent.com/assets/21366183/21621204/f65a55c0-d1c5-11e6-9b89-0c59d0946aaa.png)

**Comment by MariaKravchuk** [comment]
@morganm24 we returned the save button. 
@kenstaut we spoke about it earlier after feedback for DCU site, right?
