### ISSUE TITLE
form c/team member/director/red asterisk

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1975]
please remove RED asterisk (*)

![image](https://cloud.githubusercontent.com/assets/21366183/21075840/0c8ecf90-beea-11e6-9a60-7e04d5db4acb.png)

**Comment by vladyslav2** [comment]
well, thats require field if you want to add position or employer information

**Comment by ratmirasanov** [comment]
The same story on form c/team member/officer page.
