### ISSUE TITLE
form c/risks page/check box

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1983]
@arthuryip723 please speak with @OstapL 

please:
-make check box larger
-text larger and bold
-add space between box and text

![image](https://cloud.githubusercontent.com/assets/21366183/21076216/f71f83e8-bef3-11e6-8d2e-37a12a4ce96a.png)

**Comment by OstapL** [comment]
@morganm24 
Fixed #1990 
Morgan please check
