### ISSUE TITLE
form c/oustanding security/exempt offering

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1986]
For both questions: Do you have any business loans or debt? AND an "exempt offering"
i clicked YES for field, entered text into field,, then clicked no
when i clicked save and continue i had an error on top of page.
please make sure that if user clicks no, that question is complete

![image](https://cloud.githubusercontent.com/assets/21366183/21076271/40fbe2da-bef5-11e6-8680-e2ef7b2ea67e.png)

![image](https://cloud.githubusercontent.com/assets/21366183/21076261/107a7a2c-bef5-11e6-9d02-b84229fd3b31.png)

**Comment by vladyslav2** [comment]
duplication
i will close that issue, check #1988
