### ISSUE TITLE
form c review risk factors

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#1987]
need to add section for "MISCELLANEOUS RISK FACTORS"

![image](https://cloud.githubusercontent.com/assets/21956276/21076288/96dc801a-bef5-11e6-8227-190e61b07bd2.png)

which come from the Form C Risk Factors Miscellaneous page

**Comment by OstapL** [comment]
@kenstaut 
Fixed #1993 
please Check
