### ISSUE TITLE
form c/oustanding security

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#1988]
i clicked YES for exempt offerings, entered digit, then clicked no
when i clicked save and continue i had an error on top of page.
please make sure that if user clicks no, that question is complete

![image](https://cloud.githubusercontent.com/assets/21366183/21076271/40fbe2da-bef5-11e6-8680-e2ef7b2ea67e.png)

![image](https://cloud.githubusercontent.com/assets/21366183/21076299/c7edb91c-bef5-11e6-9174-19ac366c12c4.png)

**Comment by vladyslav2** [comment]
build one solution not sure if morgan will be happy with it

**Comment by kenstaut** [comment]
This isn't working.  I click "yes" add a digit, to amount sold, then change my mind and click "no" then save.  The system won't let me do that:
![image](https://cloud.githubusercontent.com/assets/21956276/21324056/27b44b8c-c5ee-11e6-9137-83b98a2c7d4e.png)
