### ISSUE TITLE
Formc Site: When I am at create company page the formc links are disabled.

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#2005]
I am not sure if this is an issue. But see the picture. I'll look into this.
![screen shot 2016-12-12 at 11 01 11 am](https://cloud.githubusercontent.com/assets/1624001/21105989/56ff047a-c05a-11e6-91da-8d2fe547f33a.png)

**Comment by vladyslav2** [comment]
@arthuryip723 you cannot update formc if you haven't feel campaign
