### ISSUE TITLE
FAQ and Additional Info are swapped

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2032]
beta
![image](https://cloud.githubusercontent.com/assets/21366183/21160869/7459d4a0-c154-11e6-9d6e-118446adfeae.png)

form c
![image](https://cloud.githubusercontent.com/assets/21366183/21160880/7c0fdc58-c154-11e6-9c86-923fc4d1ad91.png)

**Comment by arthuryip723** [comment]
@morganm24 So which one is correct? I can change it if you tell me which one is correct.

**Comment by arthuryip723** [comment]
I would the formc site look as the beta site.
