### ISSUE TITLE
Issuer Dashboard

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#205]
@OstapL @leonstiel 
1)Please change the color of the black element in the active state on the lighter. The layout with the corrections sent to Ostap.
![2016-08-29 14 54 36](https://cloud.githubusercontent.com/assets/20995691/18050718/ec58283a-6df8-11e6-9316-a5b1a6dc3232.png)

2)Сheck the font of buttons according to the layout.
Also replace the black button "change material " in green color  as in the layout.
![2016-08-29 14 57 51](https://cloud.githubusercontent.com/assets/20995691/18050775/4cfdd8ec-6df9-11e6-91b5-c41d0d62060b.png)

**Comment by OstapL** [comment]
@MariaKravchuk @leonstiel 
1 Fixed
2 Fixed
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/pg/issuer_dashboard
