### ISSUE TITLE
NOT NOW form c site/perks

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2051]
please make perks box larger so user can see full text
NOT NOW

![image](https://cloud.githubusercontent.com/assets/21366183/21199527/e79d308e-c211-11e6-9d8e-ee21925f5f9a.png)

**Comment by OstapL** [comment]
@morganm24 
Fixed #2080 
please check

**Comment by kenstaut** [comment]
doesn't seem to have been fixed

**Comment by OstapL** [comment]
@kenstaut 
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/campaign/139/perks
please update page

**Comment by kenstaut** [comment]
cool thanks
