### ISSUE TITLE
form c site/company detail/zipcode

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2055]
i entered the zipcode and city/state did not populate
1. make sure zip code populates city and state
2. make sure user can see the FULL city and state (to prevent errors)

![image](https://cloud.githubusercontent.com/assets/21366183/21201575/7642e192-c219-11e6-80a0-5af2f9efab9c.png)

**Comment by arthuryip723** [comment]
@OstapL Can you work on this point?
make sure user can see the FULL city and state (to prevent errors)

with zip code 92647?

Thanks.

**Comment by OstapL** [comment]
@morganm24 @arthuryip723 
I changed width city/state, now user see full city and state but if city name very large - it is  problem because not placed in line  #2081
