### ISSUE TITLE
Dynamically create thumbnails for images

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#206]
1. Fix ImageUpload to be able to create thumbnail on upload based on settings.py file
2. Make connection between main image and thumbnails files. It is not necessary to create database connection between main file and thumbnails i think it is okay  to have agreement that if main file have name:  company.jpg -> thumbnails will have: company_280x120.jpg. But we are open for solutions.
3. Return json response with links to that files.

**Comment by vladyslav2** [comment]
@MariaKravchuk we need a list of thumbnail sizes for all files that we can upload on company/campaign

**Comment by MariaKravchuk** [comment]
@vladyslav2

Header image
Preview (when loaded) on the page Create Campaign/Media - 255х153.
Preview (final display) on the page Сompany page - 1600x548

Thumbnail image
Preview (when loaded) on the page Create Campaign/Media - 255х153.
Preview (final display) on the page List of Campaigns - 350x209

Gallery image
Preview (when loaded) on the page Create Campaign/Media - 77x45 
Preview (final display) on the page Company page - 270x16

**Comment by vladyslav2** [comment]
Как пример, страница campaign media в профиле пользователя.
![screen shot 2016-08-30 at 10 33 28 am](https://cloud.githubusercontent.com/assets/704096/18093267/4e6dece0-6e9d-11e6-8ef7-5d62e1a2c4d4.png)

Сейчас в превью мы показываем пользователю полномаштабную картинку (10 таких картинок в галерее и браузер начинает умирать)

Мне нужно что бы для картинок из сериализатора приходил ответ вида:


header_image_data : {
  id: 380, 
  modified_at: "2016-08-25T18:17:46.634588Z", 
  folder: 36, 
  **thumbnails**: [
     {size: '100x200', url: 'http://amazone.s3...jpg' }, 
     {size: '100x200', url: 'asdgasdg.jpg'}
  ]
}

**Comment by DenekUrich** [comment]
Verify it, please.
