### ISSUE TITLE
specifics/pre money valuation

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2087]
1.Please make "how did you determine your valuation?" a required field.
2.Drop down should default to "Please select one"
3. if user selects "other" then the 2nd question is also required.

*make sure it add red asterisk and include it in entire page logic

![image](https://cloud.githubusercontent.com/assets/21366183/21239092/7c622546-c2d3-11e6-8d53-7f44e91db985.png)

**Comment by kenstaut** [comment]
Doesn't look like "How did you determine your valuation" is a required field.  It has a red asterisk, but user can move on without completing it.  Please make it a required field
