### ISSUE TITLE
Fixes to INVEST

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2104]
1. change the spelling from "Base" to "Based"

![image](https://cloud.githubusercontent.com/assets/21956276/21243481/0bc0231a-c2e7-11e6-829b-c5c98110a523.png)

2. Make sure logic rounds up (cannot issue factional shares, needs to be a multiple of share price)

**Comment by MariaKravchuk** [comment]
@OstapL please fix spelling in the tip

**Comment by OstapL** [comment]
@kenstaut @MariaKravchuk 
Fixed #2111 
change Base to Based
