### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#214]
@NewRoman @leonstiel @vladyslav2 

1)This map should be dynamic. ![2016-08-29 20 50 30](https://cloud.githubusercontent.com/assets/20995691/18061181/5ebd4956-6e2a-11e6-883e-7444868d8135.png)

Like here, but not in black and white.
http://rhythmwp.wpengine.com/contact-2/

**Comment by NewRoman** [comment]
1-3 were fixed in this commit
https://github.com/NewRoman/gfwhitelabels/commit/9770094219b0d445de7143a7bb1058422dd0c9f2

**Comment by NewRoman** [comment]
@vladyslav2 
set up Google maps on contact page
