### ISSUE TITLE
социальные кнопки замерают при определенных обстоятельствах

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#2155]
Если во всплывающем окне от гугла, фейсбука, линкайди при подтверждении регистрации нажать нет, то форма просто перестает реагировать на события.

пологаю что бага в этом коде https://github.com/vladyslav2/gfwhitelabels/blob/formc/src/app.js#L344, точнее проблема в том что событие доходит до body

**Comment by MariaKravchuk** [comment]
@vladyslav2 я так зрозуміла Кен сказав пки сховати соціальні кнопки взагалі
