### ISSUE TITLE
Reset Password doesn't work for the DCU site

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2161]
I get an email with a link that doesn't work:
![image](https://cloud.githubusercontent.com/assets/21956276/21332139/7fd73e02-c614-11e6-8e1d-777dc9e011ee.png)

takes me here:
![image](https://cloud.githubusercontent.com/assets/21956276/21332141/8b25a924-c614-11e6-88af-1d2c11fc6825.png)

**Comment by vladyslav2** [comment]
@kenstaut Ken please check password reset on DCU
