### ISSUE TITLE
Hide Social Sign Up

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2167]
We don't want to use it for now (we may use it later). 

![image](https://cloud.githubusercontent.com/assets/21956276/21365008/5075fde4-c6c1-11e6-948c-496caeb8cf92.png)

And
![image](https://cloud.githubusercontent.com/assets/21956276/21365015/5b16fd16-c6c1-11e6-98a1-da4066f144ab.png)

**Comment by morganm24** [comment]
sign up still has social sign in.. please hide

![image](https://cloud.githubusercontent.com/assets/21366183/21623194/4501dfe6-d1cf-11e6-900e-3176e0c3602d.png)
