### ISSUE TITLE
Form C Review (Common Equity and Revenue Share)

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2212]
Form C does not currently populate the Use of Net Proceeds (dad1, dad2, etc).  Can you just copy and paste the entire table here into Final Review?

![image](https://cloud.githubusercontent.com/assets/21956276/21443582/8f06351a-c874-11e6-8fdd-f09e9cb65578.png)

**Comment by vladyslav2** [comment]
@kenstaut please take a look

**Comment by kenstaut** [comment]
Please add "Net Proceeds" and "Total Use of Net Proceeds"

Currently, it looks like this:
![image](https://cloud.githubusercontent.com/assets/21956276/21505301/f094df9e-cc33-11e6-9a79-5c1f4105f2b2.png)

Please add these fields:
![image](https://cloud.githubusercontent.com/assets/21956276/21505313/0ede53fe-cc34-11e6-9d8a-ef0b4a99cf8b.png)

**Comment by morganm24** [comment]
@kenstaut please make sure that the above issue was fixed
