### ISSUE TITLE
TEAM

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#222]
@NewRoman @leonstiel 
1)Please check this title - here should be the Open Sans font
![2016-08-29 23 23 05](https://cloud.githubusercontent.com/assets/20995691/18066156/c5463308-6e3f-11e6-8c20-39abbb2241b1.png)

2)Add the parallax effect here
![2016-08-29 23 25 01](https://cloud.githubusercontent.com/assets/20995691/18066183/e9af5238-6e3f-11e6-8d78-015777797ba7.png)

**Comment by NewRoman** [comment]
1 fixed
https://github.com/NewRoman/gfwhitelabels/commit/8a47143b01bd9fa199b8ff5f741d4438d041129b

**Comment by NewRoman** [comment]
@MariaKravchuk 
ready to check
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/team
