### ISSUE TITLE
Menu (mobile version)

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#2244]
@OstapL 

1)User`s photo hides the logo
![image](https://cloud.githubusercontent.com/assets/20995691/21481593/2be4afba-cb72-11e6-96d1-1c747b252580.png)

2)When I open menu the photo disappears
![image](https://cloud.githubusercontent.com/assets/20995691/21481608/657cb7f4-cb72-11e6-984b-07df93822247.png)

3)We have some bug when make double click on the user`s icon
![image](https://cloud.githubusercontent.com/assets/20995691/21481627/949bfed2-cb72-11e6-8244-0af0b4c1751a.png)

![image](https://cloud.githubusercontent.com/assets/20995691/21481630/9e010850-cb72-11e6-9ec4-51827bdab4db.png)

Also please check color for both icons (for menu and user)

**Comment by OstapL** [comment]
@MariaKravchuk 
1 Fixed
2 Fixed
