### ISSUE TITLE
Profile (mobile version)

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#2245]
@OstapL 
1)We need new solution for cropping pop up look. Now it is too big
![image](https://cloud.githubusercontent.com/assets/20995691/21481675/3f45adb0-cb73-11e6-9142-8adb856189b5.png)

2)please add the space above profile Information tab as under Financial info tab
![image](https://cloud.githubusercontent.com/assets/20995691/21481699/87842714-cb73-11e6-9e67-9d8a50fe8c31.png)

3)Align City/State field
![image](https://cloud.githubusercontent.com/assets/20995691/21481706/a4bae6d8-cb73-11e6-93db-73ddcad50b18.png)

4)tweak html for sliders
![image](https://cloud.githubusercontent.com/assets/20995691/21481722/c07bf07e-cb73-11e6-97d9-ae8f617551ff.png)

5)When we open a tip then the under`s text becomes smaller
![image](https://cloud.githubusercontent.com/assets/20995691/21481764/1a6113bc-cb74-11e6-9cc8-7447594dbaab.png)

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed 1,2,3,4,5
