### ISSUE TITLE
Campaign page (mobile version)

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#2251]
@OstapL 

1) on the Sign Up pop up please delete the line under social buttons
![image](https://cloud.githubusercontent.com/assets/20995691/21483545/97def97c-cb8c-11e6-8bc2-48ce3ab7f99b.png)

2)The main video is hiding behind the menu
![image](https://cloud.githubusercontent.com/assets/20995691/21483560/dabeeda6-cb8c-11e6-9287-b242ee8bb10a.png)

3) Make bigger space between the appropriate  sections
![image](https://cloud.githubusercontent.com/assets/20995691/21483564/020d691e-cb8d-11e6-8f50-2d8dc43ebedc.png)

4)Make bigger space between sections (Share and progress bar; target amount and minimum investment)
![image](https://cloud.githubusercontent.com/assets/20995691/21483574/3f8d72d4-cb8d-11e6-98ff-c1932e1fe003.png)

5)Please make the maximum width for the text
![image](https://cloud.githubusercontent.com/assets/20995691/21483585/5d4d599c-cb8d-11e6-9b10-72d6dc7b42f3.png)

6)Make bigger space between documents sections
![image](https://cloud.githubusercontent.com/assets/20995691/21483593/7a75f74a-cb8d-11e6-9517-f0007afc0eda.png)

7)Tweak html for communication channel
![image](https://cloud.githubusercontent.com/assets/20995691/21483594/91800778-cb8d-11e6-9822-be2fdec109d3.png)

![image](https://cloud.githubusercontent.com/assets/20995691/21483601/9d3e9f3e-cb8d-11e6-8ae2-7ea6d7705ce5.png)

![image](https://cloud.githubusercontent.com/assets/20995691/21483605/aa7c95e8-cb8d-11e6-9f98-1af394e2d9d6.png)

8)Align the "read more" link with the text
![image](https://cloud.githubusercontent.com/assets/20995691/21483612/c9119940-cb8d-11e6-8954-156ef0283231.png)

**Comment by OstapL** [comment]
@MariaKravchuk Fixed 
please check
