### ISSUE TITLE
Calculators (mobile version)

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#2264]
@OstapL 
1)Revenue Share - we need responsive table or hide it
![image](https://cloud.githubusercontent.com/assets/20995691/21500489/f57f4648-cc47-11e6-95bc-829c51bd2cd3.png)

2)We should tweak this button
![image](https://cloud.githubusercontent.com/assets/20995691/21500499/19409640-cc48-11e6-8127-639e19eb409b.png)

3)Please tweak the tips
![image](https://cloud.githubusercontent.com/assets/20995691/21500505/3840cd6c-cc48-11e6-8871-accd47ef4d9f.png)

4)Tweak graph
![image](https://cloud.githubusercontent.com/assets/20995691/21500512/4be23928-cc48-11e6-833a-1e94c763f356.png)

**Comment by OstapL** [comment]
@MariaKravchuk 
fixed 2 
1 responsive - Maria this table  is responsive ) when you look in your phone should be  scrolls to  right

**Comment by ratmirasanov** [comment]
Moved to https://github.com/Growth-Fountain/growthfountain/issues/59.
