### ISSUE TITLE
Can not delete photo 

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#2277]
@vladyslav2 
I can not delete photo on the Profile page

![2016-12-27 19 45 45](https://cloud.githubusercontent.com/assets/20995691/21505124/3036906e-cc6d-11e6-8d09-296271be0ca3.png)

**Comment by ratmirasanov** [comment]
Moved to https://github.com/Growth-Fountain/growthfountain/issues/52.
