### ISSUE TITLE
Delete redundant line

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#2279]
@vladimir-chagin 
If some section is absent please hide onе redundant separating line on the Campaign page
![2016-12-27 19 50 21](https://cloud.githubusercontent.com/assets/20995691/21505222/e42b9e3e-cc6d-11e6-95e1-f7d348eb7162.png)

**Comment by ratmirasanov** [comment]
Moved to https://github.com/Growth-Fountain/growthfountain/issues/56.
