### ISSUE TITLE
Create Company And Campaign --> We should not be able to click Invest button on the Preview Campaign page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#2281]
@vladyslav2, please lock the Invest button on the preview campaign page:
![2016-12-27 19 57 01](https://cloud.githubusercontent.com/assets/20995691/21505337/012c831c-cc6f-11e6-9f22-12f3b751eeaa.png)

**Comment by ratmirasanov** [comment]
Moved to -- https://github.com/Growth-Fountain/growthfountain/issues/55.
