### ISSUE TITLE
Create Company And Campaign --> We should not be able to write the comment on the Preview campaign page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#2282]
@vladyslav2, we should not be able to write the comment on the Preview campaign page. Please lock this field or Submit button:
![2016-12-27 20 11 11](https://cloud.githubusercontent.com/assets/20995691/21505541/f0ccd704-cc70-11e6-8eb2-5993a6ee047b.png)

**Comment by ratmirasanov** [comment]
Bug moved to https://github.com/Growth-Fountain/growthfountain/issues/54.
