### ISSUE TITLE
Login Page --> Incorrect page is displayed during reset of password

### ISSUE THREAD

**Issue by ratmirasanov** [vladyslav2/gfwhitelabels#2327]
Severity: Major.
Priority: High.
Environment: http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/, All Browsers.

Steps To Reproduce:
1. Go to http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/ site.
2. Click on the "LOG IN" button.
3. Click on the "Forgot your password?" link.
4. Type "ratmir.asanov.7@yandex.ru" into "E-mail" field.
5. Click on the "RESET" button.
6. Check your email and go by provided link.

Actual Result: The page is displayed with "YOUR CODE HAVE BEEN EXPIRED. PLEASE REQUEST NEW LINK" text.

Expected Result: The appropriate page should be displayed.

**Comment by DenekUrich** [comment]
We don't use http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/. We migrated to 
http://alpha.growthfountain.com/ and http://beta.growthfountain.com/
