### ISSUE TITLE
Investor Dashboard

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#233]
@OstapL @leonstiel 
1)Here "investor dashboard" should be gray.
![2016-08-30 17 12 50](https://cloud.githubusercontent.com/assets/20995691/18092642/b8fed21c-6ed5-11e6-9407-df34af0d7e81.png)
 
2) Please correct sorting according to the layout. The name of sorting should be 11 px size and has appropriate letter-spacing.
![2016-08-30 17 18 29](https://cloud.githubusercontent.com/assets/20995691/18092752/2f137caa-6ed6-11e6-91d3-3c130a842793.png)

3)Add the distance between the name and icon on the buttons.
![2016-08-30 17 22 21](https://cloud.githubusercontent.com/assets/20995691/18092817/7d5dcf50-6ed6-11e6-87e3-7e5a5c0f60fa.png)

4)Еhe caption "150% funded" should be in the middle of the progress bar. Button "view campaign" as well.
![2016-08-30 17 24 19](https://cloud.githubusercontent.com/assets/20995691/18092944/e2baf13e-6ed6-11e6-922c-984235ba8092.png)

**Comment by OstapL** [comment]
@MariaKravchuk @leonstiel 
1 Fixed
2 Fixed
3 Fixed
4 Fixed 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/pg/investor_dashboard
