### ISSUE TITLE
Change percentage slider to amount field in the capital raise calculator

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#2337]
In the capital raise calculator on page 2 it asks “How much working capital do you need…?”  The answer is a percentage but there should be amount. 

![2016-12-30 21 55 52](https://cloud.githubusercontent.com/assets/20995691/21571827/bbe4e870-cedb-11e6-857e-3715309608f7.png)

Updated layout here
https://www.dropbox.com/home/Maria%20Wireframes/CALCULATORS/Capital%20Raise%20calculator/PSD?preview=Capital+Raise+calculator%3A+Step+2.psd

**Comment by kenstaut** [comment]
Guys, I've got Arthur working on this, please ignore
