### ISSUE TITLE
In the news

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#234]
@NewRoman @leonstiel 
1)Add please the same information here like in the layout
![2016-08-30 17 34 59](https://cloud.githubusercontent.com/assets/20995691/18093349/3e544832-6ed8-11e6-8cd0-584c1b286d08.png)
![2016-08-30 17 35 07](https://cloud.githubusercontent.com/assets/20995691/18093354/3e68a62e-6ed8-11e6-8e4a-b576d7c9b064.png)
![2016-08-30 17 35 11](https://cloud.githubusercontent.com/assets/20995691/18093351/3e659952-6ed8-11e6-9689-fcb25ec47bfa.png)
![2016-08-30 17 35 15](https://cloud.githubusercontent.com/assets/20995691/18093350/3e621af2-6ed8-11e6-8e7e-7831819b54b3.png)
![2016-08-30 17 35 20](https://cloud.githubusercontent.com/assets/20995691/18093352/3e66935c-6ed8-11e6-86de-cc0aa38f0b37.png)

2)Add links to websites:
- http://www.tsys.com/ngenuity-journal/mastering-a-new-type-of-crowdfunding-with-equity-investments.cfm

![2016-08-30 17 54 12](https://cloud.githubusercontent.com/assets/20995691/18094063/d657e16e-6eda-11e6-8dde-edd1cb611eb4.png)

- http://www.crowdfundinsider.com/2014/11/54809-callahan-associates-announces-strategic-partnership-growthfountain-opening-crowdfunding-opportunities-millions-credit-union-members/

![2016-08-30 17 55 25](https://cloud.githubusercontent.com/assets/20995691/18094102/f6fc828a-6eda-11e6-8913-2e97478d01ef.png)

And also change this logo on 

![2016-08-30 17 55 58](https://cloud.githubusercontent.com/assets/20995691/18094113/088b35be-6edb-11e6-8ad7-ad33ab7b9a81.png)

- http://www.cutimes.com/2014/11/21/callahan-pact-creates-crowdfunding-platform

![2016-08-30 17 44 53]
(https://cloud.githubusercontent.com/assets/20995691/18093720/8124a2fa-6ed9-11e6-9bc4-edaedaed87c6.png)

And change this logo to

![2016-08-30 17 46 04](https://cloud.githubusercontent.com/assets/20995691/18093752/acd7d71e-6ed9-11e6-97ff-ee935a08700c.png)

**Comment by NewRoman** [comment]
1-2 fixed 
https://github.com/NewRoman/gfwhitelabels/commit/1b444d177e84133754dc1da44de92af7483d5341

**Comment by NewRoman** [comment]
@MariaKravchuk 
ready to check
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/news
