### ISSUE TITLE
SignUp Page --> Impossible to sign up with Facebook, LinkedIn and Google

### ISSUE THREAD

**Issue by ratmirasanov** [vladyslav2/gfwhitelabels#2344]
Severity: Major.
Priority: High.
Environment: https://alpha.growthfountain.com, All Browsers.

Steps To Reproduce:
1. Go to https://alpha.growthfountain.com site.
2. Click on the "SIGN UP" button.
3. Check the "I agree to the Terms of Use, Privacy Policy and Electronic Signature and Electronic Delivery of Documentation." checkbox.
4. Click on the "SIGN UP WITH FACEBOOK" button.

Actual Result: The popup window with error message is displayed.
Below screenshots:
![screenshot_3](https://cloud.githubusercontent.com/assets/24833489/21577438/1902b5be-cf63-11e6-98fe-29c69857b45f.jpg)
The same story for signing up with LinkedIn and Google:
![screenshot_4](https://cloud.githubusercontent.com/assets/24833489/21577441/36919316-cf63-11e6-8d7c-708807a0897f.jpg)
![screenshot_5](https://cloud.githubusercontent.com/assets/24833489/21577442/3caec480-cf63-11e6-871b-859a9f1be522.jpg)

Expected Result: The appropriate page should be displayed with successful signing up.

**Comment by DenekUrich** [comment]
Fixed
