### ISSUE TITLE
SignUp Page --> Error validation messages from server should be displayed in the right way

### ISSUE THREAD

**Issue by ratmirasanov** [vladyslav2/gfwhitelabels#2345]
Severity: Minor.
Priority: Medium.
Environment: https://alpha.growthfountain.com, All Browsers.

Steps To Reproduce:
1. Go to https://alpha.growthfountain.com site.
2. Click on the "SIGN UP" button.
3. Type "First name 1" into "First name" field.
4. Type "Last name 1" into "Last name" field.
5. Type "ratmir.asanov.7@yandex.ru" into "E-mail" field (Already existing e-mail is system).
6. Type "qwerty12345" into "Password" field.
6. Type "qwerty12345" into "Re-enter password" field.
7. Check the "I agree to the Terms of Use, Privacy Policy and Electronic Signature and Electronic Delivery of Documentation." checkbox. 
8. Click on the "SIGN UP" button.

Actual Result: The error "non_field_errors: A user is already registered with this e-mail address." message is displayed.

Expected Result: Expected Result: The error message should be provided under input field in red text color.
The following message: E-mail -- "A user is already registered with this e-mail address." message.

Please make the same (not server side messages) for all input fields of the "SIGN UP" form.

**Comment by ratmirasanov** [comment]
Please also add such messages to all input fields if we have so long entered value:
"Length of first name should not exceed more than 30 characters."

**Comment by DenekUrich** [comment]
@vladimir-chagin it is your
