### ISSUE TITLE
Form C - Use of Proceeds Tab

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2355]
This line should automatically calculate GrowthFountain's fee and user should not be able to delete this line.  GrowthFountain's fee is 6% of money raised, so in this example, 
1. should be .06*25,000 = 1,500
2. should be .06*50,000 = 3,000

![image](https://cloud.githubusercontent.com/assets/21956276/21613507/85b65f2a-d1a3-11e6-9512-b1c28197663b.png)

**Comment by ratmirasanov** [comment]
@vladyslav2 tested on alpha.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
