### ISSUE TITLE
Campaign setup/how did you determine valuation

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2362]
this is required. (when user selects other)
 1.please add red asterisk
 2.make sure it is required for logic.

![image](https://cloud.githubusercontent.com/assets/21366183/21621667/0923f59c-d1c8-11e6-9129-40ae53a3d51c.png)

**Comment by ratmirasanov** [comment]
@kenstaut @morganm24 please check it on beta.
