### ISSUE TITLE
Form C Final Review (common and revenue share) Outstanding Security Tab

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2403]
Change "Maturity Date" to "Date of Offering"

![image](https://cloud.githubusercontent.com/assets/21956276/21726745/032e0c7c-d40c-11e6-87aa-6561a1bee3ff.png)

**Comment by ratmirasanov** [comment]
@kenstaut, please check.
Fixed on https://alpha.growthfountain.com.
