### ISSUE TITLE
Env --> Different databases should be used for alpha and beta sites

### ISSUE THREAD

**Issue by ratmirasanov** [vladyslav2/gfwhitelabels#2404]
Different databases should be used for alpha and beta sites:
https://alpha.growthfountain.com;
https://beta.growthfountain.com.

Acceptance Criteria: Provided above sites should be ran on different databases.

**Comment by ratmirasanov** [comment]
Please add additional changes -- I need URL for Admin Panel.

**Comment by vladyslav2** [comment]
http://django-admin-dev.growthfountain.com/admin/ 
@ratmirasanov check
