### ISSUE TITLE
Env --> Making the site faster

### ISSUE THREAD

**Issue by ratmirasanov** [vladyslav2/gfwhitelabels#2413]
Let's make the site more faster -- performance issuer/feature.
After running Google's PageSpeed Tools we have such results:

Compressing and resizing http://growthfountain-formc-storage.s3-website-us-east-1.amazonaws.com/137_908.png could save 2.4MiB (97% reduction).
Compressing and resizing https://beta.growthfountain.com/img/callahan.png could save 126KiB (98% reduction).
Compressing https://beta.growthfountain.com/img/raise-capital.png could save 89.8KiB (33% reduction).
Compressing https://beta.growthfountain.com/img/bg.jpg could save 81.5KiB (20% reduction).
Compressing and resizing http://growthfountain-storage.s3-website-us-west-1.amazonaws.com/205_1392.jpg could save 36.1KiB (87% reduction).
Compressing and resizing https://beta.growthfountain.com/img/logo_dcu.jpg could save 35.8KiB (95% reduction).
Compressing https://beta.growthfountain.com/img/logo.png could save 14.9KiB (71% reduction).
Compressing http://growthfountain-formc-storage.s3-website-us-east-1.amazonaws.com/173_1111.png could save 4.9KiB (38% reduction).
Compressing https://beta.growthfountain.com/img/logo_rivermark.png could save 1.3KiB (37% reduction).

Eliminate render-blocking JavaScript and CSS in above-the-fold content.
**Your page has 3 blocking script resources and 5 blocking CSS resources. This causes a delay in rendering your page.**
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.
Remove render-blocking JavaScript:
https://cdnjs.cloudflare.com/…jax/libs/es6-shim/0.35.1/es6-shim.min.js
https://js.stripe.com/v2/
https://beta.growthfountain.com/bundle.157fab22a43c5fb172a0.js
Optimize CSS Delivery of the following:
https://beta.growthfountain.com/css/main2.css
https://fonts.googleapis.com/css?family=Dosis:400,300,500
https://fonts.googleapis.com/css?family=Open+Sans:400,500,700,300
https://fonts.googleapis.com/css?family=Allura
https://cdnjs.cloudflare.com/…t-awesome/4.6.3/css/font-awesome.min.css

Leverage browser caching.
**Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.**
Leverage browser caching for the following cacheable resources:
http://growthfountain-formc-storage.s3-website-us-east-1.amazonaws.com/128_788.jpg (expiration not specified)
http://growthfountain-formc-storage.s3-website-us-east-1.amazonaws.com/137_908.png (expiration not specified)
http://growthfountain-formc-storage.s3-website-us-east-1.amazonaws.com/173_1111.png (expiration not specified)
http://growthfountain-storage.s3-website-us-west-1.amazonaws.com/133_811.jpg (expiration not specified)
http://growthfountain-storage.s3-website-us-west-1.amazonaws.com/205_1392.jpg (expiration not specified)
https://beta.growthfountain.com/7.bundle.157fab22a43c5fb172a0.js (expiration not specified)
https://beta.growthfountain.com/bundle.157fab22a43c5fb172a0.js (expiration not specified)
https://beta.growthfountain.com/css/main2.css (expiration not specified)
https://beta.growthfountain.com/img/bg.jpg (expiration not specified)
https://beta.growthfountain.com/img/callahan.png (expiration not specified)
https://beta.growthfountain.com/img/fade-in-logo.png (expiration not specified)
https://beta.growthfountain.com/img/logo.png (expiration not specified)
https://beta.growthfountain.com/img/logo_dcu.jpg (expiration not specified)
https://beta.growthfountain.com/img/logo_jd.png (expiration not specified)
https://beta.growthfountain.com/img/logo_rivermark.png (expiration not specified)
https://beta.growthfountain.com/img/raise-capital.png (expiration not specified)
https://beta.growthfountain.com/img/section-bg-3.jpg (expiration not specified)
https://js.stripe.com/v2/ (5 minutes)
https://ssl.google-analytics.com/ga.js (2 hours)
https://www.google-analytics.com/analytics.js (2 hours)

Acceptance Criteria: All described above drawbacks should be fixed after running Google's PageSpeed Tools.

Dev Estimation:

Test Estimation:

**Comment by OstapL** [comment]
@ratmirasanov 
that's for me )
