### ISSUE TITLE
Emails --> Emails to users on GF

### ISSUE THREAD

**Issue by ratmirasanov** [vladyslav2/gfwhitelabels#2430]
The following emails should implemented:
1. reset password (works but have grammar mistakes);
2. investment made (email does not work);
3. campaign submission (email does not work);
4. form c submission (email does not work);
5. team member invitation (works but have grammar mistakes);
6. welcome email (may or may not work, please check).

Acceptance Criteria: The user should be able to receive such emails.

Dev Estimation:

Test Estimation:

**Comment by growthfountain** [comment]
https://www.dropbox.com/sh/0bbcub7hvmahhd5/AABuX7DTCxJdz_Ua7fFm9qbda?dl=0
