### ISSUE TITLE
Backups --> Priority implementation

### ISSUE THREAD

**Issue by ratmirasanov** [vladyslav2/gfwhitelabels#2434]
Description:    We need to create database, code base and s3 storage backups.

Acceptance Criteria:  S3 storage with backups

Dev Estimation: 1 day

Test Estimation: 1 day

**Comment by triamazikamno** [comment]
Why was it closed?

**Comment by ratmirasanov** [comment]
We have moved to a new repository/tracker:
https://github.com/Growth-Fountain/growthfountain/issues/2

**Comment by triamazikamno** [comment]
Ah ok, thanks
