### ISSUE TITLE
HTML --> Update bootstrap for an new version

### ISSUE THREAD

**Issue by ratmirasanov** [vladyslav2/gfwhitelabels#2435]
Update bootstrap for an new version.

Acceptance Criteria:  Bootstrap is successfully updated (Please provide info here:
https://github.com/vladyslav2/gfwhitelabels/blob/formc/package.json#L25).

Dev Estimation:

**Comment by OstapL** [comment]
@ratmirasanov 
I think it's now bad idea update bootstrap for alpha 6 
because in alpha 5 - 6 many changes. You see this in documentation (https://blog.getbootstrap.com/) Later I update bootstrap, but not now )

**Comment by vladyslav2** [comment]
@OstapL какие основные изменения ? С чем могут возникнуть проблемы ?

**Comment by OstapL** [comment]
@vladyslav2 много классов убрали и заменили на новые 
если можно я с понедельника на своей ветке начну это делать и затянется это на пару дней ) 
я вчера сделал на своей ветке хотел посмотреть много ли нужно делать ) и увидел ужасную картину ) когда весь сайт поломался ) они очень много изменений внесли в 5 -6 версию
