### ISSUE TITLE
Form C Use of Procceeds Tab

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2477]
For the line "Commission Expenses (GrowthFountain): please add the formula so that it automatically calculates 6% of each amount sought

ie. 
![image](https://cloud.githubusercontent.com/assets/21956276/21943281/8b636546-d99e-11e6-8b49-6bd0afcf022f.png)

![image](https://cloud.githubusercontent.com/assets/21956276/21943069/af94945e-d99d-11e6-8231-a1272531bcb1.png)

**Comment by ratmirasanov** [comment]
@kenstaut, I think it has already fixed. Please check it.
