### ISSUE TITLE
Education Tab

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2479]
Change this statement to:

GrowthFountain receives a 6% payment in connection with the successful completion....

![image](https://cloud.githubusercontent.com/assets/21956276/21947070/2f9cf25a-d9b1-11e6-972e-b681fa760f7c.png)

**Comment by OstapL** [comment]
Fixed 
test site: alpha.growthfountain.com

**Comment by ratmirasanov** [comment]
@kenstaut, please check.
Fixed on https://alpha.growthfountain.com.
