### ISSUE TITLE
Create Campaign bugs

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#248]
@vladyslav2 @leonstiel 

1)Please make design of error
![2016-08-31 14 02 08](https://cloud.githubusercontent.com/assets/20995691/18126402/a7047acc-6f83-11e6-9387-69aa418ca6f9.png)
Like here
![2016-08-31 14 03 18](https://cloud.githubusercontent.com/assets/20995691/18126420/ba6cd582-6f83-11e6-9d0a-75fb08fd31ed.png)

2)Even if I do not fill some section, I am able to remove it
![2016-08-31 14 15 11](https://cloud.githubusercontent.com/assets/20995691/18126761/60e2a40e-6f85-11e6-84f5-e4c8fda7fce6.png)

![2016-08-31 14 15 36](https://cloud.githubusercontent.com/assets/20995691/18126772/6ad9b2ea-6f85-11e6-8a75-8a3f87fc8eaa.png)

Vlad we need to make so that if the user has not filled field, delete button should be not active.

3)What happens to my page Media? Why can I scroll it aside?
![2016-08-31 14 22 36](https://cloud.githubusercontent.com/assets/20995691/18127022/90b2170e-6f86-11e6-9d16-e2ba3e411333.png)

The same situation with Specifics page
![2016-09-02 17 35 09](https://cloud.githubusercontent.com/assets/20995691/18208743/5063b34c-7139-11e6-8b1a-c26be89ebdd5.png)
 
4)The same situation with the removal of sections of the video. Even if the user has not filled in  fields "Optional video", he already can delete this section. Besides, if he removed this section with optional video, the function "Add another video" appears under  section of required video. But we do not need to add more than one main video.

![2016-08-31 14 26 06](https://cloud.githubusercontent.com/assets/20995691/18127259/e4397fba-6f87-11e6-8b0b-b8652a71d923.png)
![2016-08-31 14 26 20](https://cloud.githubusercontent.com/assets/20995691/18127260/e43b608c-6f87-11e6-8b55-fcad53d6a82e.png)

5)Hovering in this area appears this Tip. It is not clear how it can be turned off, because it hinders to view uploaded photos. You need to make sure that the tip will show up on the right side of the section (like all the other tips)
![2016-08-31 14 34 03](https://cloud.githubusercontent.com/assets/20995691/18127347/84d95198-6f88-11e6-9bc7-84f7b7dfb0fb.png)

6)The system allows you to add team members without their names. This must be change
![2016-08-31 14 54 16](https://cloud.githubusercontent.com/assets/20995691/18127755/08610ae0-6f8b-11e6-98f4-d1f2735b9693.png)

7)Here please add spaces in the tooltip as in the layout. (Specifics Page)
![2016-08-31 14 46 03](https://cloud.githubusercontent.com/assets/20995691/18127568/db39f8fc-6f89-11e6-8235-77c2167cd413.png)

8)In such fields, there is an icon of the dollar. Let's do so that when people wrote a certain amount in these fields, the dollar icon remained. We also need to automatically have comas in the numbers.

![2016-08-31 14 48 50](https://cloud.githubusercontent.com/assets/20995691/18127690/a81dbbd8-6f8a-11e6-848f-d3d2ca593013.png)
![2016-08-31 14 52 59](https://cloud.githubusercontent.com/assets/20995691/18127689/a81da6c0-6f8a-11e6-8480-18946fb19201.png)

9)Here we should be able to download is only two types of files - PPT and PDF. But now the system allows us download here several different files. I think that there should be able to download only one file - PDF or PPT. Also the picture of files should match to  the type of file which user loaded.

![2016-08-31 14 59 39](https://cloud.githubusercontent.com/assets/20995691/18127897/cf074826-6f8b-11e6-8d8f-7b39ec4e2437.png)

10)And generally Vlad, in all those pages you need to check all labels according to layout, and check which fields are requirement and which are not.

**Comment by vladyslav2** [comment]
1, 6, 7, 17, 20 @OstapL

**Comment by OstapL** [comment]
1 Fixed http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/media/45

**Comment by OstapL** [comment]
7 fixed http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/media/45

**Comment by OstapL** [comment]
20 Fixed

**Comment by OstapL** [comment]
6 Fixed http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/company/create

**Comment by vladyslav2** [comment]
@MariaKravchuk its too difficult to work with such a big issue list
please split on small tasks
