### ISSUE TITLE
Revenue Share Calculator

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2480]
This pdf should appear in a separate popup tab when user clicks the agreement link

![image](https://cloud.githubusercontent.com/assets/21956276/21947286/6a434624-d9b2-11e6-8951-b3ff1fe17f2a.png)
[Revenue Share Agreement.pdf](https://github.com/vladyslav2/gfwhitelabels/files/705440/Revenue.Share.Agreement.pdf)

**Comment by ratmirasanov** [comment]
@vladyslav2 tested on alpha.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
