### ISSUE TITLE
Bugs with Invest / Profile / Investor Dashboard

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2481]
Investor dashboard:
 
![image](https://cloud.githubusercontent.com/assets/21956276/21949125/bc3c9f42-d9bd-11e6-9d40-27057886aa43.png)

1.	This is not an accurate reflection of the days remaining in the campaign
2.	This is not the right date (should be 1/13/2017 as of date of logging this bug)
3.	This is not supposed to be “$240.”  This is the cumulative amount invested
 
INVEST PAGE

![image](https://cloud.githubusercontent.com/assets/21956276/21949128/c0c8f3c6-d9bd-11e6-859d-3960b96206cc.png)

4.	User MUST check “TRUE” for all instances in order to proceed
 
![image](https://cloud.githubusercontent.com/assets/21956276/21949135/c85dbff4-d9bd-11e6-9f6e-7260783ff434.png)

5.	Social security number is exactly 9 digits (the system allows you to enter more than 9 digits)
Error message should say "Please enter a social security number that is 9 digits"  Also fix this error message in Profile

 
![image](https://cloud.githubusercontent.com/assets/21956276/21949138/cb561cba-d9bd-11e6-912b-d7a63477001a.png)

6.	This user has logged $0 income and $0 net worth in their profile.  They are only supposed to be able to invest a maximum of $2,000 in all offerings on GrowthFountain for a rolling 12 month period.  The site caps me at $2,000 for a single investment, but it lets me make multiple investments which put me over my allowable limit.

**Comment by vladyslav2** [comment]
6. problem that user can invest for 2000 twice even if his income is $0 and net worth is $0  in their profile

**Comment by ratmirasanov** [comment]
@kenstaut, we know about these bugs.

**Comment by ratmirasanov** [comment]
5. Now it is working with such message -- "Social Security number (SSN) or Tax ID (ITIN/EIN) must be 9 characters.".
6. We will do this like a new US for the next Sprint.

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha site.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
