### ISSUE TITLE
Partners

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#249]
@NewRoman @leonstiel  

1) Add here external links for logos
![parteners](https://cloud.githubusercontent.com/assets/20995691/18128611/5421ed38-6f8f-11e6-803a-90f8a9faee43.png)

For the first logo - http://www.callahan.com/

For the second logo - https://www.jdcu.org/

For third logo - https://www.rivermarkcu.org/

the links should open in the new tab

**Comment by NewRoman** [comment]
fix 
https://github.com/NewRoman/gfwhitelabels/commit/1906ad6328577e8a7bab571c39c0aee5a80a38e2
