### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#250]
@OstapL @leonstiel 

1)Add new text from the updated layout to this section
![2016-08-31 15 50 59](https://cloud.githubusercontent.com/assets/20995691/18129292/c24f5c98-6f92-11e6-9280-7ac006dbcbdf.png)

2)Replace all texts with font open sans Light to Regular 
![2016-08-31 15 50 59](https://cloud.githubusercontent.com/assets/20995691/18129389/33a2b9f8-6f93-11e6-8a7d-2964766a9f60.png)
![2016-08-31 15 54 02](https://cloud.githubusercontent.com/assets/20995691/18129387/339f2f5e-6f93-11e6-9b1b-dd0b6fb1f6e8.png)
![2016-08-31 15 54 11](https://cloud.githubusercontent.com/assets/20995691/18129388/339fdce2-6f93-11e6-9e33-1b8783127575.png)

3) Add here the third new logo of partner as in the layout
![2016-08-31 15 55 23](https://cloud.githubusercontent.com/assets/20995691/18129425/594f251a-6f93-11e6-97b9-a0b7d34e7725.png)

4)Add links to this logos

For the first logo - http://www.callahan.com/

For the second logo - https://www.jdcu.org/

For third logo - https://www.rivermarkcu.org/

the links should open in the new tab

**Comment by OstapL** [comment]
@leonstiel @MariaKravchuk 
1 Fidex
2 corresponds not design
3 Fixed
4 Fixed
result http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com
commit 2b4f844c327880feaf159f5a07a0f53215bbef34
