### ISSUE TITLE
Static text pulled when you type growthfountain.com

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2501]
how ever we are taking this, we need to change it:

 
![image](https://cloud.githubusercontent.com/assets/21956276/22022623/c119a264-dc90-11e6-8ac8-97d302dfad9e.png)

Change to:

GrowthFountain is an SEC registered Funding Portal and FINRA Member where individuals can come together to support entrepreneurs and small businesses across America. Turn your customers, your social network, your neighbors and community members into owners who can become your brand ambassadors and evangelists. To learn more about GrowthFountain and the risks of crowdfunding, please visit www.growthfountain.com.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it.
