### ISSUE TITLE
Invest

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2503]
1. Cap is 2, not 1
![image](https://cloud.githubusercontent.com/assets/21956276/22023802/b88bc64a-dc95-11e6-858f-13d1783c4068.png)

2. A: This is not the correct date (the date is 1/17/2017)
   B: this is not the correct number of days left
   C: downloadable files are not working
![image](https://cloud.githubusercontent.com/assets/21956276/22023898/1a96b7e6-dc96-11e6-8a2a-bfe1cea4f936.png)

3. Oma's offering deadline is 7/10/17
![image](https://cloud.githubusercontent.com/assets/21956276/22024039/ab76000a-dc96-11e6-8f7a-4d1f63bb2a40.png)

4. Make sure the counter on Oma's is counting down to their 7/10/17 deadline
![image](https://cloud.githubusercontent.com/assets/21956276/22024078/c54ddd04-dc96-11e6-8e33-fc70ac75f289.png)

5. Make sure the counter on Cogent is counting down to their 7/17/17 deadline

6. Make sure the offering deadline for Cogent is changed to 7/17/17
![image](https://cloud.githubusercontent.com/assets/21956276/22024151/02ff60dc-dc97-11e6-8e01-55ac01a86a90.png)

**Comment by ratmirasanov** [comment]
@kenstaut, we know about these bugs.

**Comment by ratmirasanov** [comment]
@kenstaut please check it.
