### ISSUE TITLE
investment email

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2505]
We need to make sure the deadline date corresponds to the actual deadline date

![image](https://cloud.githubusercontent.com/assets/21956276/22027569/491f7d94-dca2-11e6-9fbc-279e69835329.png)

**Comment by ratmirasanov** [comment]
@kenstaut, we know about this bug.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it.
