### ISSUE TITLE
Changes to Confirmation of Understanding in Invest

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2514]
![image](https://cloud.githubusercontent.com/assets/21956276/22042403/11ebe93e-dcd9-11e6-89de-8a2d886bb1dc.png)

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha site.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
