### ISSUE TITLE
Investor Tutorial

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2520]
Investor tutorial:

![image](https://cloud.githubusercontent.com/assets/21956276/22068738/f36a1180-dd63-11e6-87f2-c080ff05ad4f.png)

Change (CLICK TO LAUNCH OUR INVESTOR CALCULATOR) TO:

(CLICK TO INPUT YOUR INCOME AND WEALTH)

and when the user clicks, it should take them to PROFILE/FINANCIAL INFORMATION
![image](https://cloud.githubusercontent.com/assets/21956276/22068766/0fa6346e-dd64-11e6-8bb8-729613072662.png)

**Comment by belskiyroman** [comment]
ветка alpha, комит "2520 - fix link "click to launch our investor calculator" on investor tutorial"

**Comment by ratmirasanov** [comment]
@belskiyroman, rename please link to "(CLICK TO INPUT YOUR INCOME AND WEALTH)".

**Comment by belskiyroman** [comment]
исправил надпись

**Comment by ratmirasanov** [comment]
@belskiyroman, DONE on alpha site.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it.
