### ISSUE TITLE
Facebook share feature

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2523]
please remove "by growthfountain"

![image](https://cloud.githubusercontent.com/assets/21366183/22072255/c1bc7072-dd6f-11e6-8f60-c08684802679.png)

**Comment by vladyslav2** [comment]
@ratmirasanov Роман посмотрит (мне кажется это сделать не возможно)

**Comment by ratmirasanov** [comment]
@belskiyroman is it ready?

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha site.

**Comment by ratmirasanov** [comment]
@kenstaut, @morganm24, please check it on beta.
