### ISSUE TITLE
issuer dashboard/investment

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2524]
issue was not fixed
user made investment today 1/18/17 NOT 1/17

![image](https://cloud.githubusercontent.com/assets/21366183/22073228/cb486080-dd72-11e6-95ec-49f0e2fed6ab.png)

**Comment by ratmirasanov** [comment]
@morganm24, we know about this bug.

**Comment by ratmirasanov** [comment]
@morganm24, please check it.
