### ISSUE TITLE
Popup description of Revenue Share

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2531]
underline (solid or dotted line) or help icon here in Campaign:
![image](https://cloud.githubusercontent.com/assets/21956276/22080543/f8e94110-dd8d-11e6-9592-26c019ce576f.png)

when user scrolls over, popup shows definition of revenue share:

![image](https://cloud.githubusercontent.com/assets/21956276/22080667/6c752612-dd8e-11e6-8113-7a0f63a489fc.png)

Here is the text: 
A Revenue Share Agreement is a form of investment contract in which the Company shares 5% of its revenue annually with investors.
Here’s how it works:
1.	Investors earn 5% of the company’s revenue annually;
2.	No distributions are required until the second full calendar year and the company is allowed one year of forbearance as needed;
3.	Distributions are capped at two times the invested amount (2x);
4.	In the event of default, investors become general unsecured creditors (senior to equity).

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha site.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
