### ISSUE TITLE
Popup description of Common Equity

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2532]
underline (solid or dotted line) or help icon here in Campaign:
![image](https://cloud.githubusercontent.com/assets/21956276/22080813/fc64d3d0-dd8e-11e6-86e7-910ab1a73dc2.png)

when user scrolls over, popup shows definition of common equity:
![image](https://cloud.githubusercontent.com/assets/21956276/22081089/31d13a12-dd90-11e6-81a1-4552f5e22796.png)

here is the text:
Equity represents ownership in a Company.  As owners, equity investors will generally receive a share of the proceeds upon trade sale or IPO.  Alternatively, investors can theoretically sell their ownership interest when the overall value of the Company has increased – though shares of common stock purchased in a crowdfunding transaction would have certain holding restrictions which are described in greater detail in our educational material.
The Pre-Money valuation is the valuation prior to this round of financing.  Post-Money valuation is based on Pre-Money valuation plus the proceeds from the financing.

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha site.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
