### ISSUE TITLE
Changes to INVEST and PROFILE

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2548]
lets add a second column that says:

(in INVEST)
Routing Number Again
![image](https://cloud.githubusercontent.com/assets/21956276/22118595/6bb12a7e-de46-11e6-84eb-3a805fc13c9e.png)

(in PROFILE)
Routing Number Again
![image](https://cloud.githubusercontent.com/assets/21956276/22118622/86597e6c-de46-11e6-91db-7fb7dec0ad1a.png)

**Comment by vladyslav2** [comment]
@ratmirasanov Роман делает

**Comment by belskiyroman** [comment]
Вова сделал уже..

**Comment by ratmirasanov** [comment]
@vladyslav2, tested on alpha.

**Comment by ratmirasanov** [comment]
@vladyslav2, after merging to live please add comment to me.

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha site.

**Comment by vladyslav2** [comment]
? @ratmirasanov tomorrow we will marge with beta, and on Wednesday with life

**Comment by ratmirasanov** [comment]
@vladyslav2 ok.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
