### ISSUE TITLE
Investor Dashboard

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2554]
Change "Agreement" to "Agreements"
![image](https://cloud.githubusercontent.com/assets/21956276/22155190/97131a72-defc-11e6-809d-884f0af76e5f.png)

When user clicks, you get a popup (like with "Financials") and both agreements appear:
Subscription Agreement
Participation Agreement

**Comment by vladyslav2** [comment]
Роман работает с этой таской

**Comment by vladyslav2** [comment]
@ratmirasanov

**Comment by belskiyroman** [comment]
@ratmirasanov отдал комит Владу

**Comment by ratmirasanov** [comment]
@vladyslav2, tested on alpha.
