### ISSUE TITLE
Automated Emails

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2556]
Please ensure there is a space between the last paragraph and "Sincerely,"

![image](https://cloud.githubusercontent.com/assets/21956276/22156508/911a5f2c-df01-11e6-9b36-a98a54f5699b.png)

**Comment by ratmirasanov** [comment]
@kenstaut, this email can be received after cancellation of investment?
Now I have received such email: https://www.dropbox.com/home/Maria%20Wireframes/Newsletters/Automated%20Emails?preview=5+GF+Automated+email+5+-+Investment+Cancellation_FINAL.psd.

**Comment by ratmirasanov** [comment]
@kenstaut, I think this bug was fixed.
