### ISSUE TITLE
Campaign Preview

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2559]
When campaign preview loads, it does not load to top of screen (edited)
This is what it does:
![image](https://cloud.githubusercontent.com/assets/21956276/22168659/2878eac0-df3c-11e6-93fa-68c689bb4c8a.png)

It should do this:
![image](https://cloud.githubusercontent.com/assets/21956276/22168667/35157514-df3c-11e6-99bb-4d5e259cfbd4.png)

**Comment by ratmirasanov** [comment]
@kenstaut, we know about this problem.
