### ISSUE TITLE
Social media icons to bottom of website

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2593]
please add growthfountain social media icons to bottom of website.
@MariaKravchuk please create design for social media links
facebook: https://www.facebook.com/GrowthFountain/?fref=ts

and linkedin:
https://www.linkedin.com/company/growthfountain

Here are examples 
![image](https://cloud.githubusercontent.com/assets/21366183/22312080/76c8da0a-e324-11e6-9e9d-f747713cd3a2.png)

![image](https://cloud.githubusercontent.com/assets/21366183/22312130/a178800c-e324-11e6-9941-4534d83f1916.png)

![image](https://cloud.githubusercontent.com/assets/21366183/22312154/b7933d0a-e324-11e6-908c-cc20c139714f.png)

**Comment by ratmirasanov** [comment]
@kenstaut, @morganm24, please check it on beta.
