### ISSUE TITLE
BackGround Check page of Form C

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2595]
These fields are required but there should not be any minimum number of characters:

![image](https://cloud.githubusercontent.com/assets/21956276/22335935/928f1170-e3ae-11e6-81ff-aef355acc89d.png)

**Comment by ratmirasanov** [comment]
We need to do two things: 
1) there needs to be a red error image that alerts them when required fields are incomplete;
2) any entry into these fields should mean they have answered the question (right now there is a minimum number of characters - lets just make it 1 character).

**Comment by ratmirasanov** [comment]
@vladyslav2 tested on alpha.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
