### ISSUE TITLE
links do not work

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#260]
Bottom of page (raise capital with us)
"RAISE CAPITAL" does not work
"LEARN MORE" does not work

![image](https://cloud.githubusercontent.com/assets/21366183/18137185/5bf3ba10-6f75-11e6-89e7-dc6427fd2894.png)

**Comment by morganm24** [comment]
Bottom of page (About us)
Overview- link does not work
Team- directed to wrong page (overview page) (wrong page)
Partners- directed to wrong page (overview page) (wrong page)
Contact Us- directed to wrong page (overview page) (wrong page)
Careers- directed to wrong page (overview page) (wrong page)
In the news- correct
FAQ- correct
Blog- correct
![image](https://cloud.githubusercontent.com/assets/21366183/18137239/95455aa8-6f75-11e6-8e06-7be9ecd5be1d.png)

**Comment by NewRoman** [comment]
@vladyslav2 
on my site 
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/
all this link are worked(except career)
Why they don't work on es7 - i dont know.

**Comment by vladyslav2** [comment]
@NewRoman please check now

**Comment by NewRoman** [comment]
@vladyslav2 @morganm24 
all links from ABOUT US menu work fine(except Career)
