### ISSUE TITLE
Issuer Dashboard

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2600]
Please add a link in the Issuer Dashboard of the Listing Agreement (which the company electronically signed on the first page of the Form C)

**Comment by vladyslav2** [comment]
Maria we want to add 3 buttons to the issuer dashboard:
- import google contacts
- import linkedin contacts
- setup facebook autoposter schedule

**Comment by MariaKravchuk** [comment]
@vladyslav2 

please add such link here
![2017-02-03 13 51 28](https://cloud.githubusercontent.com/assets/20995691/22590477/12d5e768-ea18-11e6-9da8-f4bf39251866.png)

but if you can at the same moment to add the link to Form C, will be great
![2017-02-03 13 54 11](https://cloud.githubusercontent.com/assets/20995691/22590528/4565d8b4-ea18-11e6-8d5f-c0dc506af3b8.png)

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta. Except of Vlad's comment. This is separate User Story and we will do it in the next sprint (4).
