### ISSUE TITLE
Form C (rev share and common)

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2602]
Problems with $ signs and should be "there is" rather than "these if"

![image](https://cloud.githubusercontent.com/assets/21956276/22352676/2796a0d0-e3eb-11e6-908b-ff1575a98b70.png)

**Comment by OstapL** [comment]
I  changed text (there is) and deleted $ ($7) 
other need to fix Vlad

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
