### ISSUE TITLE
Force Sign Up / Log In

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2616]
Force Sign Up/Login In if user clicks:

Success Guide
Advertising and Communication
Revenue Share Calculator
How Much Should I Raise
Whats My Business Worth

![image](https://cloud.githubusercontent.com/assets/21956276/22433392/30b74ca2-e6e6-11e6-955c-81255ee7b1d6.png)

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha.
