### ISSUE TITLE
Social security number

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2617]
Lets not make this a required field for investment.

Completely remove this field
![image](https://cloud.githubusercontent.com/assets/21956276/22429772/b0f58fee-e6d9-11e6-9f43-bf14aedb8805.png)

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.

**Comment by kenstaut** [comment]
Please also remove the text
![image](https://cloud.githubusercontent.com/assets/21956276/22511875/1286efd2-e865-11e6-9d26-12b46db5af29.png)

**Comment by ratmirasanov** [comment]
@vladyslav2 tested on alpha.
