### ISSUE TITLE
Profile on Beta Site

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2633]
![image](https://cloud.githubusercontent.com/assets/21956276/22511946/523022a2-e865-11e6-891b-9973fac57129.png)

**Comment by ratmirasanov** [comment]
@kenstaut can you please give us steps to reproduce this bug?
We cannot reproduce it.
Thanks.

**Comment by kenstaut** [comment]
seems like it has fixed itself
