### ISSUE TITLE
Campaign help icon

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#264]
The blue text should be larger or bold. It is difficult to read.

![image](https://cloud.githubusercontent.com/assets/21366183/18141614/3052dab8-6f88-11e6-9e29-ac2963232693.png)

Change the quote to  “If you can’t explain it simply, you don’t understand it well enough.” —Albert Einstein

**Comment by vladyslav2** [comment]
@MariaKravchuk @OstapL
