### ISSUE TITLE
Social media share icons

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2648]
1. for twitter, delete this:
![image](https://cloud.githubusercontent.com/assets/21956276/22570562/f10fa352-e969-11e6-84e5-7ab0c491702e.png)

2. For facebook, why are there question marks?
![image](https://cloud.githubusercontent.com/assets/21956276/22570573/05fc9a7c-e96a-11e6-8dbc-392796df00d6.png)

**Comment by belskiyroman** [comment]
@ratmirasanov пулл-реквест у Влада. После апрува будет на альфе.
- сделал 2-й пункт.
- первый пункт не воспроизводится ни у кого. Скорее всего это индивидуальная проблема связанная с кешем, настройками браузера или установленными приложениями 
(плагины/расширения) в браузере.
Если все это все же баг, то нужно описание чекой последовательности действий и описание окружение окружения при котором воспроизводится баг.

**Comment by ratmirasanov** [comment]
1. Done.
2. We cannot reproduce this issue.
@kenstaut, please check it on beta.
