### ISSUE TITLE
Marketing to Site Best Practices

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2653]
![image](https://cloud.githubusercontent.com/assets/21956276/22598137/738f5368-ea00-11e6-8119-10af44166a4c.png)

Can we add something like CircleUp does?
Maybe our clickable links can be: 
Sign In
About Us
Deals
For Entrepreneuers
In the News
Resources

![image](https://cloud.githubusercontent.com/assets/21956276/22598208/aadd4c12-ea00-11e6-803d-61a3b5072745.png)

**Comment by ratmirasanov** [comment]
@leonstiel can you proceed with this task?
