### ISSUE TITLE
campaign listing page

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#266]
Campaigns with more information are bigger
make all campaigns the same size.
![image](https://cloud.githubusercontent.com/assets/21366183/18141976/99ce4fa8-6f89-11e6-94a0-1d8c2b23c242.png)

**Comment by OstapL** [comment]
@morganm24 @leonstiel 
Fixed https://github.com/vladyslav2/gfwhitelabels/commit/b8e90db3606ad3d8d795e13d2da0895152c6f1be
