### ISSUE TITLE
New automated email

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2664]
For issuers when someone asks a question in the communication channel
[Your Have a Question from an Investor.docx](https://github.com/vladyslav2/gfwhitelabels/files/755734/Your.Have.a.Question.from.an.Investor.docx)

**Comment by MariaKravchuk** [comment]
@vladyslav2 @OstapL 
I made layout for this email.
https://www.dropbox.com/home/Maria%20Wireframes/Newsletters/Automated%20Emails?preview=Question+from+investor.psd
