### ISSUE TITLE
Investor FAQ

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2665]
Add an FAQ here:
![image](https://cloud.githubusercontent.com/assets/21956276/22666409/6ee2d51e-ec86-11e6-9034-a9e48c4bb06d.png)

That looks like this:
![image](https://cloud.githubusercontent.com/assets/21956276/22666480/b50acb3c-ec86-11e6-95fe-daa181685d31.png)

And here is the text:
Do I need to provide my social security number?
You do not need to provide your social security number to invest but you may need to provide your social security number in the future in order to receive certain payments and distributions from the issuers in which you invest.  Since GrowthFountain is not able to offer tax related advice, the determination around how your investment and returns are treated is left up to the issuer and the Internal Revenue Service.  If your social security number is needed, the issuer will contact you to request it after the closing.  For this reason, please be sure to provide accurate contact information and to promptly update it if such information changes.

**Comment by OstapL** [comment]
@ratmirasanov @kenstaut 
please check on alpha

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
