### ISSUE TITLE
Fixes to FAQs

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2666]
Changes to INVESTOR FAQS

![image](https://cloud.githubusercontent.com/assets/21956276/22666518/d7322f2a-ec86-11e6-89b8-25752c5d8f5a.png)

Change text to:
with a third-party FDIC insured account designated by GrowthFountain as being for the benefit of issuers and investors

![image](https://cloud.githubusercontent.com/assets/21956276/22666535/e566fc9c-ec86-11e6-88f7-54de0e657fa5.png)

Change text to:
contact the third-party FDIC insured account

![image](https://cloud.githubusercontent.com/assets/21956276/22666548/f32dbd0c-ec86-11e6-8f5b-18b400d3ac5b.png)

Change whole FAQ to:
What is an FBO Account
An FBO Account is an acronym for a “for the benefit of” account and references a third-party FDIC insured account designated by GrowthFountain as being for the benefit of issuers and investors.  Since GrowthFountain does not take possession of any investor funds, all committed capital would be held in the third-party FDIC insured FBO account.  If a company reaches its minimum target fundraising goal, your committed capital would be transferred from the third-party FDIC insured FBO account to the company and the company would issue the purchased securities to each of the investors. If a company fails to reach its minimum target fundraising goal, all investor commitment amounts would be returned from the third-party FDIC insured FBO account, less any participation fees assessed and without any accrued interest.

Changes to ISSUER FAQ:
![image](https://cloud.githubusercontent.com/assets/21956276/22666588/2767b7a8-ec87-11e6-960a-12044bcb5d23.png)

Add this text to the end: 
You may also have certain obligations to make reports to the IRS as a result of payments or distributions to investors, and this may include collecting taxpayer information such as social security numbers from investors.  GrowthFountain is not able to provide tax related advice.

**Comment by OstapL** [comment]
@kenstaut @ratmirasanov 
please check on alpha

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha.

**Comment by ratmirasanov** [comment]
@kenstaut, please check it on beta.
