### ISSUE TITLE
Subscription and Purchase Agreement for COMMON STOCK

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2667]
![image](https://cloud.githubusercontent.com/assets/21956276/22668059/570f9966-ec8d-11e6-8893-beb95931be86.png)

Add text (copied here:)
Subscriber understands that delivery of the Shares and any payments or distributions relating to the Shares may be dependent and conditioned upon the Subscriber providing correct and up-to-date contact and tax-related information, including without limitation, any of the following as requested: an email delivery address, a physical delivery address and a social security number.

And:
![image](https://cloud.githubusercontent.com/assets/21956276/22668080/6e70d0f2-ec8d-11e6-8c8a-cf2a2a74122e.png)

Add text (copied here:)
, including without limitation any personal information such as updated contact information and accurate social security information for purposes of delivering any payments or distributions relating to the Shares.

**Comment by OstapL** [comment]
@ratmirasanov please check

**Comment by ratmirasanov** [comment]
@OstapL I cannot see changes on alpha.

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha.

**Comment by ratmirasanov** [comment]
@kenstaut please check it on beta.
