### ISSUE TITLE
Subscription and Purchase Agreement for REVENUE SHARE AGREEMENT

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2668]
![image](https://cloud.githubusercontent.com/assets/21956276/22668163/b3ea9136-ec8d-11e6-8755-1326d6d2066b.png)

Add text (copied here)
Subscriber understands that delivery of the Security and any payments or distributions relating to the Security may be dependent and conditioned upon the Subscriber providing correct and up-to-date contact and tax-related information, including without limitation, any of the following as requested: an email delivery address, a physical delivery address and a social security number.

![image](https://cloud.githubusercontent.com/assets/21956276/22668186/c59545ca-ec8d-11e6-97da-256dd9b27e5d.png)

Add text (copied here):
, including without limitation any personal information such as updated contact information and accurate social security information for purposes of delivering any payments or distributions relating to the Security.

**Comment by OstapL** [comment]
@ratmirasanov please check

**Comment by ratmirasanov** [comment]
@kenstaut, in "https://www.dropbox.com/home/Maria%20Wireframes/Website%20Documents/UPDATED%20DOCUMENTS%2012_15_16?preview=Common+_+Comparison.docx" document we have another 2.4 section.
Please update ticket if needed.

**Comment by ratmirasanov** [comment]
@OstapL I cannot see the changes on alpha.

**Comment by ratmirasanov** [comment]
@vladyslav2 checked on alpha.

**Comment by ratmirasanov** [comment]
@kenstaut please check it on beta.
