### ISSUE TITLE
FROM C REVENUE SHARE

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#2669]
![image](https://cloud.githubusercontent.com/assets/21956276/22668265/1601b570-ec8e-11e6-9a78-450429ba0d8e.png)

Add text (copied here)
The delivery of the purchased securities and any payments or distributions relating thereto may be dependent and conditioned upon the investor providing correct and up-to-date contact and tax-related information, including without limitation, the following as requested: an up-to-date email delivery address, an up-to-date physical delivery address and an accurate social security number.

**Comment by OstapL** [comment]
@kenstaut @ratmirasanov 
fix 
please check on alpha

**Comment by ratmirasanov** [comment]
@kenstaut please check it on beta.
