### ISSUE TITLE
campaign list page

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#267]
The Dropdown list doesn't work.. and there should only be two options
Common Equity
PayBack Share

![image](https://cloud.githubusercontent.com/assets/21366183/18142191/71e73b98-6f8a-11e6-8846-0a6c1ae3e647.png)

**Comment by vladyslav2** [comment]
@arthuryip723

**Comment by arthuryip723** [comment]
Fixed.
