### ISSUE TITLE
campaign preview link

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2683]
Can we please move company website link to bottom of campaign and make it smaller? We do not want users to leave our page. Possibly move their fb and twitter page to a different location too
@MariaKravchuk @ratmirasanov @kenstaut 
![image](https://cloud.githubusercontent.com/assets/21366183/22707764/dade4530-ed41-11e6-898f-b410a0036dc8.png)

**Comment by ratmirasanov** [comment]
@morganm24, done. Please, check it on live.
