### ISSUE TITLE
company slogan

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2685]
it is important to keep company name and slogan next to each other otherwise the slogan is confusing.
@kenstaut @MariaKravchuk 
![image](https://cloud.githubusercontent.com/assets/21366183/22708452/463ba320-ed44-11e6-8cc1-eceb07a97cd8.png)

 example/
![image](https://cloud.githubusercontent.com/assets/21366183/22708138/395b350e-ed43-11e6-9d01-40190d0a25d5.png)
![image](https://cloud.githubusercontent.com/assets/21366183/22708313/ccab7be8-ed43-11e6-8196-846f7db3e6af.png)
![image](https://cloud.githubusercontent.com/assets/21366183/22708402/1bb9cb90-ed44-11e6-9234-f4e2d0ccfd24.png)
![image](https://cloud.githubusercontent.com/assets/21366183/22708410/272663bc-ed44-11e6-8286-1d5b8d42f201.png)

**Comment by ratmirasanov** [comment]
@morganm24, done. Please, check it on live.
