### ISSUE TITLE
Login and signup with social buttons on white label sites

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#278]
We do have white labels sites for our partners:

http://growthfountain-jeanne-darc.s3-website-us-east-1.amazonaws.com/account/signup

and social sign up/login have to work on that sites too.

skype me for more details about white labels sites please.

**Comment by DenekUrich** [comment]
You need to use [document](https://drive.google.com/open?id=1bfJlc-Kv6RuKamQY2bKHs-YUHf_q4hLtwhWvPVX-Od4) and add new domains to social app configuration.

**Comment by vladyslav2** [comment]
@DenekUrich lets setup  a time with @morgan24 where you can make a screenshare and explain that

thanks
