### ISSUE TITLE
index page (partners)

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#291]
Every link should open a new window so users do NOT leave growthfountain.com 
(when you click on these icons, you leave growthfountain.com)

![image](https://cloud.githubusercontent.com/assets/21366183/18179692/b6659900-7051-11e6-9045-6242ed1b67b6.png)

**Comment by OstapL** [comment]
@morganm24 
Morgan look here http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/

**Comment by morganm24** [comment]
@vladyslav2 
when you click on the icon, the next tab will diplay the site. it should open a completely new tab window
![image](https://cloud.githubusercontent.com/assets/21366183/18183833/2e5d96a8-7064-11e6-88a2-451c901da0b8.png)
