### ISSUE TITLE
company list page (drop down menu)

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#297]
this should be titled: LOCATION

![image](https://cloud.githubusercontent.com/assets/21366183/18184129/8e4ef6dc-7065-11e6-8aeb-261d40185963.png)

this should be titled: SECURITY TYPE
![image](https://cloud.githubusercontent.com/assets/21366183/18184837/c454e996-7068-11e6-8d94-9ec60f1e8a08.png)

When you scroll over the list on each drop down menu it should highlight each field like below.

![image](https://cloud.githubusercontent.com/assets/21366183/18184073/48ba5dfa-7065-11e6-87f6-f88af1da8e09.png)

Industries, stage, location, and location and security
![image](https://cloud.githubusercontent.com/assets/21366183/18184019/031ce16e-7065-11e6-98a8-70c2650b2be3.png)

**Comment by growthfountain** [comment]
drop down menu highlighting should be consistent across the whole site

**Comment by vladyslav2** [comment]
@morganm24 did arthur fixed this ?

**Comment by morganm24** [comment]
make sure fields are highlighted when user's mouse is on the category.
-another issuer: when user selects the category it then shows up as the title. ex/ common equity is at the top of deal type.
*make sure industry/stage/location/deal type is always the title

![image](https://cloud.githubusercontent.com/assets/21366183/18453335/c58731fa-790c-11e6-8846-bd39635e9557.png)

![image](https://cloud.githubusercontent.com/assets/21366183/18453363/e7ff4ccc-790c-11e6-8add-1af5b2ec4473.png)

this is a good example how user checking or unchecking a box then clicking apply to set the filters.
![image](https://cloud.githubusercontent.com/assets/21366183/18453378/fd0eb242-790c-11e6-8df1-1947a7ae9222.png)
