### ISSUE TITLE
sharing campaign link

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2992]
user copies link and shares it to slack/twitter/facebook/SMS
ISSUE: does NOT pull image and content
Fix: Please fix campaign pages so that Link pulls thumbnail image and "about us"

Here are examples
![image](https://cloud.githubusercontent.com/assets/21366183/24367195/ad0a10a8-12e9-11e7-85e7-82f50b310335.png)

![image](https://cloud.githubusercontent.com/assets/21366183/24367738/c20d0b5c-12eb-11e7-80d5-b8027c291a26.png)

![image](https://cloud.githubusercontent.com/assets/21366183/24367746/cbe164ac-12eb-11e7-873f-e1ea0a2c33bc.png)

**Comment by ratmirasanov** [comment]
@morganm24, done. Please, check it on live.
