### ISSUE TITLE
campaign share feature for linkedin

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#2995]
user chooses to share campaign to linkedin 
issue: no popup window appears with text
fix: popup window asking to share to your linkedin like we had before

![image](https://cloud.githubusercontent.com/assets/21366183/24368315/f137a49e-12ed-11e7-8806-b591e9010952.png)

![image](https://cloud.githubusercontent.com/assets/21366183/24368269/c9c25bb6-12ed-11e7-8926-f5edd0bd3b85.png)

**Comment by ratmirasanov** [comment]
@morganm24, is working as expected.
