### ISSUE TITLE
Create campaign/Team members

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#300]
@OstapL @vladyslav2 @leonstiel 
1)Swap please this social fields. LinkedIn should be the first 
![2016-09-02 13 50 56](https://cloud.githubusercontent.com/assets/20995691/18201740/72c2ae90-7114-11e6-8cc1-da3bb1d218eb.png)

2)Vlad, I suggest the form team member to make two buttons from the bottom as in the layout:
![2016-09-02 13 54 30](https://cloud.githubusercontent.com/assets/20995691/18201795/cded207a-7114-11e6-969a-fc4d42c65726.png)

If the user has already added the two members of the team, then I suggest to add here on the top some message. 
![2016-09-02 13 59 33](https://cloud.githubusercontent.com/assets/20995691/18201898/99521cfc-7115-11e6-906c-4d73ef865abf.png)

This message should contain text about that if the user will have added the desired number of team members, it must use the side menu and go to Specifics page. 
I do not like this button Specifics here.

3)When you add 4 team members the fourth team member appear on the right. He should be on the left
![2016-09-02 17 34 06](https://cloud.githubusercontent.com/assets/20995691/18207869/ad668e6a-7135-11e6-8558-a6a383214f4b.png)

**Comment by OstapL** [comment]
@MariaKravchuk @leonstiel @vladyslav2 
1 Fixed c482a921b712c18514e9b2e72b80c596dc0e6442
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/team-members/45/add/member/2
3 Fixed http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/team-members/45
