### ISSUE TITLE
team member order text

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#3077]
I know this is temporary fix, but can you please change the text.

Please change text:
Enter a number. Team members will be displayed in ascending order.

![image](https://cloud.githubusercontent.com/assets/21366183/24669063/f1067b04-1936-11e7-9b53-44be4ad4ec22.png)

**Comment by MariaKravchuk** [comment]
@morganm24 I propose to add a tooltip here with your text

**Comment by morganm24** [comment]
@MariaKravchuk that is a good idea
