### ISSUE TITLE
Fix default image for campaign

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#308]
https://www.dropbox.com/home/Maria%20Wireframes/Default%20images?preview=1600*548.png

it should be at 2560 px 
WQHD, 16:9, 2560x1440

**Comment by MariaKravchuk** [comment]
@vladyslav2 
https://www.dropbox.com/home/Maria%20Wireframes/Default%20images?preview=2560x870.png
