### ISSUE TITLE
The discrepancy between the campaign creation process and view the campaign as a result.

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#311]
@arthuryip723  @leonstiel 
1) Here should show only those icons that the user added when filling the relevant information (in the Create Company page)
![2016-09-02 21 29 58](https://cloud.githubusercontent.com/assets/20995691/18214211/715127fe-7154-11e6-9930-62cb1638c700.png)

2) Let make this form for dates like in design
![2016-09-02 22 21 22](https://cloud.githubusercontent.com/assets/20995691/18215784/9e8d6da2-715b-11e6-82f5-9f5f28605a1f.png)

3)Why here we have buttons only with name "Invest" but not "invest in some company"
![2016-09-02 22 48 59](https://cloud.githubusercontent.com/assets/20995691/18216481/9e803dcc-715f-11e6-9807-72fc7a5dbf34.png)
![2016-09-02 22 49 06](https://cloud.githubusercontent.com/assets/20995691/18216482/9e85a29e-715f-11e6-92d5-881ea7e8c359.png)

Please make here this button like in the layouts
![2016-09-05 21 07 10](https://cloud.githubusercontent.com/assets/20995691/18254989/c4b11eea-73ac-11e6-8661-80718bf29d57.png)
![2016-09-05 21 07 21](https://cloud.githubusercontent.com/assets/20995691/18254990/c4b4e192-73ac-11e6-9c7f-f81355299126.png)

4)By default, here should be reflected only 4 FAQ. Other users can see if he click on "See all FaQ"
![2016-09-07 18 31 42](https://cloud.githubusercontent.com/assets/20995691/18318275/c75b4f48-7529-11e6-8ca5-bbaeb7248a73.png)

5)If more Risks don`t exist in the bottom should not be link "See more"
![2016-09-07 18 36 41](https://cloud.githubusercontent.com/assets/20995691/18318480/77cada24-752a-11e6-8f9a-d507e858eec2.png)

**Comment by vladyslav2** [comment]
@MariaKravchuk can we close that ?
