### ISSUE TITLE
CSS of <a> with class "btn" should not show link style

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#312]
a(data-dismiss="modal").update-location.btn.btn-lg.btn-primary.text-uppercase save
here's the jade code for my button. and please look at the screenshot. It shows the link style when hovering.
![screen shot 2016-09-02 at 3 22 26 pm](https://cloud.githubusercontent.com/assets/1624001/18215886/a1f72ac6-7121-11e6-970c-cb07dbcda21c.png)

**Comment by OstapL** [comment]
@arthuryip723 
better use the 
button(data-dismiss="modal").update-location.btn.btn-lg.btn-primary.text-uppercase save instead of following links or else you need to write href=""

**Comment by OstapL** [comment]
@arthuryip723 
a(data-dismiss="modal" href="#").update-location.btn.btn-lg.btn-primary.text-uppercase save

**Comment by OstapL** [comment]
@arthuryip723
Fixed a759dd49c967fe13e1b18fb205a997cb1a9f5e93

**Comment by arthuryip723** [comment]
OK. Thanks for the update. I'll check.
