### ISSUE TITLE
Common Equity/Payback Share differences on look of Campaign

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#324]
@arthuryip723 @leonstiel 

1) If the user selected here Type of Security **Common Equity** (Specifics page)
![2016-09-05 20 16 15](https://cloud.githubusercontent.com/assets/20995691/18254358/a02d813c-73a5-11e6-9103-32815654609b.png)

we should have the following information on the Company Page
![2016-09-05 19 42 17](https://cloud.githubusercontent.com/assets/20995691/18253864/f0b477be-73a0-11e6-8aba-95979f206311.png)

![2016-09-05 19 59 25](https://cloud.githubusercontent.com/assets/20995691/18254116/495835d4-73a3-11e6-9677-5047881aff90.png)

and this information on the List of Campaigns page
![2016-09-05 20 01 17](https://cloud.githubusercontent.com/assets/20995691/18254163/a73b459c-73a3-11e6-9029-527b4be35092.png)

2) If the user selected here Type of Security **Payback Share** (Specifics page)
![2016-09-05 20 15 46](https://cloud.githubusercontent.com/assets/20995691/18254351/8f8f666a-73a5-11e6-92a3-b424c16e32cc.png)

we should have the following information on the Company Page
![2016-09-05 20 06 21](https://cloud.githubusercontent.com/assets/20995691/18254237/41fe34ea-73a4-11e6-9f83-6d4522b7cc9a.png)

![2016-09-05 20 15 17](https://cloud.githubusercontent.com/assets/20995691/18254345/818c6504-73a5-11e6-94bd-b3579351a902.png)

and this information on the List of Campaigns page

![2016-09-05 20 17 02](https://cloud.githubusercontent.com/assets/20995691/18254374/c0729cc0-73a5-11e6-8682-3bace732eff2.png)

**Comment by arthuryip723** [comment]
Thanks. I am looking at it.
