### ISSUE TITLE
Team members buttons

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#329]
@OstapL @leonstiel 
It should be aligned the users on the left side.

Change the name of button "Specifics" on "Go to Specifics" 

And align these buttons on the right side.

![2016-09-05 22 43 15](https://cloud.githubusercontent.com/assets/20995691/18256252/6b78dc0a-73bb-11e6-9289-b6133c79b216.png)

**Comment by OstapL** [comment]
@MariaKravchuk @leonstiel 
Fixed 58c008c23c39db06e892356118d2798d10d2f374
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/team-members/45
