### ISSUE TITLE
PayBack calculator

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#337]
@NewRoman @leonstiel 
1) The color of this element should be blue like in the layout
![2016-09-06 12 53 06](https://cloud.githubusercontent.com/assets/20995691/18269520/16f32ef8-7431-11e6-8278-a0ea72d45494.png)

2)The user should be able to return to the previous page using this element
![2016-09-06 12 55 17](https://cloud.githubusercontent.com/assets/20995691/18269656/afdef5de-7431-11e6-9d98-381990594a3b.png)

3)If on this page I have not filled all the data I should not be able to go to the next page
![2016-09-06 13 00 08](https://cloud.githubusercontent.com/assets/20995691/18269725/0130a806-7432-11e6-9197-e9dd17e12ca8.png)

4)This button on the finish page of calculator should lead to the previous page.
![2016-09-06 13 01 36](https://cloud.githubusercontent.com/assets/20995691/18269769/3a635f4c-7432-11e6-9519-39259cfffc21.png)

5)Can you change the font here on Open Sans?
![2016-09-06 13 03 52](https://cloud.githubusercontent.com/assets/20995691/18269808/74d9fa28-7432-11e6-87d1-ed3bb24a41a8.png)
![2016-09-06 13 03 58](https://cloud.githubusercontent.com/assets/20995691/18269809/74dbd190-7432-11e6-821d-9c8c30d68f56.png)

**Comment by NewRoman** [comment]
@MariaKravchuk  @vladyslav2 
For point number 3 created new issue 
https://github.com/vladyslav2/gfwhitelabels/issues/348

**Comment by NewRoman** [comment]
1,2,4 fixed in commit
https://github.com/NewRoman/gfwhitelabels/commit/a5ccd46212edf157bc62714838994005bf480d36

5 - I can't change that font family
