### ISSUE TITLE
Tweak design of some elements on Company page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#339]
@OstapL @leonstiel 
Ostap, here we already added all the necessary information. you need to tweak the design of these sections according to the layout
![2016-09-06 13 15 39](https://cloud.githubusercontent.com/assets/20995691/18270188/6d90d762-7434-11e6-8700-46d9ddfbb4b2.png)
![2016-09-06 13 16 36](https://cloud.githubusercontent.com/assets/20995691/18270187/6d8d615e-7434-11e6-9b40-7acb1facdde3.png)

**Comment by OstapL** [comment]
@MariaKravchuk @leonstiel 
Fixed 6c78c56fe31e35163871c2cf31c47a8b41b02083
-added a new unit , respectively, changes in design
-change width block Type of Security
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign/55
