### ISSUE TITLE
index page sign up to start investing

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#344]
when user clicks "sign up to start investing" if they are logged in, they should be brought to the campign listing page. 
![image](https://cloud.githubusercontent.com/assets/21366183/18279471/b453735a-7423-11e6-83c0-5b8ba9e4f060.png)
they should NOT be brought here
![image](https://cloud.githubusercontent.com/assets/21366183/18279551/ef87f52c-7423-11e6-9a84-a94fed8a728c.png)

if user is signed in, they should go to this page.
![image](https://cloud.githubusercontent.com/assets/21366183/18279489/c2e5b4be-7423-11e6-9c2e-b9f410e4eeca.png)

**Comment by growthfountain** [comment]
let's discuss
