### ISSUE TITLE
campaign list page

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#351]
spelling: change locations to LOCATION
 change industries to INDUSTRY

![image](https://cloud.githubusercontent.com/assets/21366183/18280775/51c4bba4-7428-11e6-844c-a69210b792e4.png)

**Comment by OstapL** [comment]
@morganm24 @MariaKravchuk 
Fixed 
change name option INDUSTRY and LOCATION
c0a9c7b1c8eb1cb33c066a08100cba0517d8c8a2
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign

**Comment by growthfountain** [comment]
@morganm24 can this be closed?
