### ISSUE TITLE
index page -raise capital button

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#353]
raise capital button should bring you to campaign setup. the raise capital button does NOT work for certain accounts.
![image](https://cloud.githubusercontent.com/assets/21366183/18280976/14b748ac-7429-11e6-9038-99aa3e9a7128.png)

user should click raise capital and appear here
![image](https://cloud.githubusercontent.com/assets/21366183/18281114/a2cd74ae-7429-11e6-8d86-a3f5479242b1.png)

**Comment by NewRoman** [comment]
@MariaKravchuk 
fix here
https://github.com/NewRoman/gfwhitelabels/commit/ae78b117601d30635eec92c4cf2f4a9e7da6c248

**Comment by morganm24** [comment]
@vladyslav2 can we work on this today

**Comment by vladyslav2** [comment]
@morganm24 can we close that ?
