### ISSUE TITLE
index page

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#354]
bottom page. "raise capital" and "learn more" do not work

![image](https://cloud.githubusercontent.com/assets/21366183/18281288/4c79d9ca-742a-11e6-972e-c9fe3bd8edf0.png)

raise capital button should bring you here
![image](https://cloud.githubusercontent.com/assets/21366183/18281306/625ca722-742a-11e6-8d28-da6b66d6ed4d.png)

learn more should bring you here
http://growthfountain-es7.s3-website-us-east-1.amazonaws.com/pg/entrepreneurquestions

**Comment by NewRoman** [comment]
@MariaKravchuk  
fix here 
https://github.com/NewRoman/gfwhitelabels/commit/ae78b117601d30635eec92c4cf2f4a9e7da6c248
