### ISSUE TITLE
index page, partner icons bottom of page

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#355]
when user clicks on these icon. a new tab should appear. you fixed this problem everywhere else but at the bottom of the index page.
![image](https://cloud.githubusercontent.com/assets/21366183/18281698/d76fd01a-742b-11e6-98ac-69122435f177.png)

**Comment by vladyslav2** [comment]
please check http://growthfountain-romank.s3-website-us-east-1.amazonaws.com/

**Comment by growthfountain** [comment]
@morganm24 can this be closed?
