### ISSUE TITLE
campaign setup/checkmark

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#3585]
green check mark does not appear when required fields are complete. please make sure checkmark appears when all REQUIRED (questions with red *) fields are completed.
![image](https://user-images.githubusercontent.com/21366183/27545685-70c6202a-5a5e-11e7-9bf2-dd4bb029a8d8.png)

**Comment by ratmirasanov** [comment]
@morganm24, you should add at least 6 images to the "Gallery" field.

**Comment by ratmirasanov** [comment]
@morganm24, we have added error message during submitting campaign.
