### ISSUE TITLE
index page, learn more

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#361]
when user clicks on "learn more" they are brought to the middle of the FAQ
![image](https://cloud.githubusercontent.com/assets/21366183/18286308/22603812-7440-11e6-8e18-10e9d71d95b6.png)

Please make it so the user is at the top of the page
![image](https://cloud.githubusercontent.com/assets/21366183/18286338/4a1a3ef2-7440-11e6-8118-a840e9e5d584.png)

**Comment by vladyslav2** [comment]
Can you check please ?
