### ISSUE TITLE
index page, bottom

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#364]
change this
![image](https://cloud.githubusercontent.com/assets/21366183/18286645/bec6cab2-7441-11e6-889e-1fb10a50a8af.png)

to this
![image](https://cloud.githubusercontent.com/assets/21366183/18286654/c7d62f12-7441-11e6-99e8-8515bd0b9137.png)

**Comment by vladyslav2** [comment]
@NewRoman please fix

**Comment by vladyslav2** [comment]
@NewRoman Do not forget !

**Comment by NewRoman** [comment]
@vladyslav2 @MariaKravchuk @morganm24 

fixed in commit 
https://github.com/NewRoman/gfwhitelabels/commit/ffa20d5cc5f8f29a57a7a1a767fb1d3895815940

**Comment by NewRoman** [comment]
@morganm24 
check please
