### ISSUE TITLE
Type of Security

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#369]
@arthuryip723 @leonstiel 

1) if user chooses Type of security Payback Share (on page Specifics http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/campaign/specifics/50) we should have following look of some Campaign section:

Percentage revenue will be always 5%
![2016-09-06 22 24 57](https://cloud.githubusercontent.com/assets/20995691/18287713/e12de786-7480-11e6-9f82-04ec9f69a173.png)

This section should look like here and percentage revenue will be always 5% and cap - 2x
![2016-09-06 22 26 38](https://cloud.githubusercontent.com/assets/20995691/18287749/17278d4c-7481-11e6-99d9-8982f24e08d2.png)

and here should be it (List of campaigns page)
![2016-09-06 22 27 53](https://cloud.githubusercontent.com/assets/20995691/18287771/339c201e-7481-11e6-980d-68916753270d.png)

2) if user chooses Type of security Common equity (on page Specifics http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/campaign/specifics/50) we will be have following look of some Campaign section:

![2016-09-12 22 01 57](https://cloud.githubusercontent.com/assets/20995691/18448664/a0dfbe44-7934-11e6-9458-4144e47946ab.png)

**Comment by vladyslav2** [comment]
@MariaKravchuk please check
if fixed - please close

**Comment by MariaKravchuk** [comment]
@vladyslav2 @arthuryip723 Please read my task again and pay attention to the screenshots
