### ISSUE TITLE
white label site

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#370]
@vladyslav2  please convert jdcu site to the rivermark format

**Comment by vladyslav2** [comment]
Sorry i do not understand you

do you want me to add information to the index page of jdcu site ?

**Comment by growthfountain** [comment]
@morganm24 not sure what this means, can you please clarify or close?  note that JDCU provided their own design for their whitelabel, and we committed to deliver them that.

**Comment by morganm24** [comment]
@growthfountain this was something vlad wanted me to write to remind him about a task. We resolved the issue. He forgot that he told me to write that.
