### ISSUE TITLE
Press design and js updates

### ISSUE THREAD

**Issue by growthfountain** [vladyslav2/gfwhitelabels#371]
1)  We need to change the background to a flat color until we are able to autopopulate an image.
2)  We need to limit the length of the headline / use a link shortening service such as bit.ly so that the content fits in the area.  Or we can expand the area.  Please see attached image, example on the right.
![press](https://cloud.githubusercontent.com/assets/6185789/18288641/4ff03f02-744a-11e6-8103-892678195180.png)

**Comment by vladyslav2** [comment]
@MariaKravchuk @arthuryip723 can we create a group chat and eliminate that issues please ?

**Comment by vladyslav2** [comment]
@MariaKravchuk ?

**Comment by MariaKravchuk** [comment]
@vladyslav2 @OstapL Let`s make such design for Press section
https://growthfountain.slack.com/files/maria/F2B7FR0R1/__________________________2016-09-13____22.18.13.png

Here is updated Campaign page https://www.dropbox.com/home/Maria%20Wireframes/Company%20page
