### ISSUE TITLE
Add Bootstrap slider for input on step-1 page of Calculator Capitalrise

### ISSUE THREAD

**Issue by NewRoman** [vladyslav2/gfwhitelabels#373]
@vladyslav2 @MariaKravchuk 
page address
calculator/capitalrise/step-1

![_121](https://cloud.githubusercontent.com/assets/8603994/18288948/01799ada-7486-11e6-8015-527a11b70e31.png)

**Comment by vladyslav2** [comment]
@NewRoman please assign to me tasks like this

**Comment by rkuleshov-corevalue** [comment]
It's done from my side. Has to be styled

**Comment by NewRoman** [comment]
@MariaKravchuk 
it is ready to check
