### ISSUE TITLE
campaign setup (company section)

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#375]
if you type www.website.com it wont let you move on. 
User should be allowed to type www.11111.com without having to enter http://

![image](https://cloud.githubusercontent.com/assets/21366183/18291679/b7710df2-7457-11e6-97c1-6ac04cc778ac.png)

**Comment by vladyslav2** [comment]
will you be able to fix that ?

**Comment by arthuryip723** [comment]
@vladyslav2 Probably. I am looking at it.

**Comment by arthuryip723** [comment]
@vladyslav2 I am not quire sure how to fix this. Please advise.

**Comment by growthfountain** [comment]
I believe this is the same issue as #476 , just a different field.   We should standardize all web url inputs to accept either http:// or www.

**Comment by morganm24** [comment]
additional fields that require a web url.
![image](https://cloud.githubusercontent.com/assets/21366183/18418408/d4b863d2-7813-11e6-9dcb-d8ef808f2709.png)

**Comment by vladyslav2** [comment]
@morganm24 lets close this issue and create new one

for facebook/linkedin we might need to use different solution
