### ISSUE TITLE
campaign setup media

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#383]
Scroll bar does not work and Make scroll bar larger.
![image](https://cloud.githubusercontent.com/assets/21366183/18318286/243a843a-74ef-11e6-9e63-4dd5e44ca26d.png)

**Comment by vladyslav2** [comment]
Do not work at all ?

**Comment by growthfountain** [comment]
@vladyslav2 @arthuryip723  let's make the scroll bar bigger if it's not a big piece of work
