### ISSUE TITLE
campaign setup media delete header and thumbnail image

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#385]
Add option to delete images. Put large red X in top right corner
![image](https://cloud.githubusercontent.com/assets/21366183/18318385/8681c798-74ef-11e6-816c-e97816b66eb4.png)

**Comment by vladyslav2** [comment]
if you will delete an image what should you get instead ? empty spot ?

**Comment by morganm24** [comment]
Yes for now.

Morgan Kinzler
GrowthFountain LLC
79 Madison Ave, 5th Floor
New York, NY 10016
www.growthfountain.com
