### ISSUE TITLE
PayBack Share Calculator

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#388]
issue 1. If user clicks "Finish" site freezes

![image](https://cloud.githubusercontent.com/assets/21956276/18318684/a66a5f74-74f0-11e6-9907-692702e5e2ce.png)

issue 2. on "Step 1" the fields should be blank (not prepopulated)

![image](https://cloud.githubusercontent.com/assets/21956276/18318750/e91b2006-74f0-11e6-9923-1bfdc2cd2b7e.png)

issue 3. on "Finish" stop displaying any results once a multiple of 2 has been returned

![image](https://cloud.githubusercontent.com/assets/21956276/18318795/0eb221f2-74f1-11e6-9610-b2470a50fd30.png)

**Comment by morganm24** [comment]
@vladyslav2 please make sure you see this and assign it to the right person.

**Comment by vladyslav2** [comment]
@rkuleshov-corevalue

**Comment by rkuleshov-corevalue** [comment]
I've merged UI with my functionality. You can check it after pull request https://github.com/vladyslav2/gfwhitelabels/pull/561 is merged 

On the last step graph doesn't work. As I know Vladyslav made a decision to use another plugin for that

**Comment by rkuleshov-corevalue** [comment]
Could you check it on more time please.
Note: 
1) you don't have ability to go to the final step without data entered.
2) We have changed plugin for the graph. You may notice that now we don't have draw animation and final label. (I'm working on it)

**Comment by rkuleshov-corevalue** [comment]
Draw animation and final label are implemented
