### ISSUE TITLE
Risks

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#389]
@OstapL @leonstiel 
1)We have changes in the risks. Now they will not be as accordions

![2016-09-07 18 49 06](https://cloud.githubusercontent.com/assets/20995691/18318904/248d6582-752c-11e6-9dc1-91d81892622f.png)

Please look at the updated PSD in dropbox

**Comment by vladyslav2** [comment]
@MariaKravchuk DO NOT CREATE NEW PSD FOR THAT WE WILL NOT WORK WITH RISKS ON THAT WEEK
