### ISSUE TITLE
campaign media page, thumbnail cropping

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#390]
campaign thumbnail photo is cut off if it doesn't meet the right dimensions. Can you provide a box when image is uploaded to show what part of the picture will be displayed?

![image](https://cloud.githubusercontent.com/assets/21366183/18318644/752bb0ac-74f0-11e6-822f-231ab5919009.png)

**Comment by vladyslav2** [comment]
@MariaKravchuk

**Comment by vladyslav2** [comment]
close that for now 
please create new issue
