### ISSUE TITLE
login in page, social media logins

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#395]
Denis since we set up google login for GF, lets work with google.
![image](https://cloud.githubusercontent.com/assets/21366183/18519620/9a5bc39e-7a72-11e6-99cd-63a52e23c5ac.png)
issue: google credentials are always saved unless you delete history in browser.
 example/ if Morgan logs in through google when Morgan logs out, make sure her credentials are not saved. so if Vlad tries to login through google on morgan's computer it will make vlad to enter his google email and pw

login through facebook on kickstarter to understand.
step 1. login through facebook
step 2 log out
step 3. this will appear, requesting you enter information.
![image](https://cloud.githubusercontent.com/assets/21366183/18321500/304848f4-74fc-11e6-9206-dc7f41320002.png)

**Comment by vladyslav2** [comment]
@DenekUrich we need documentation from you

**Comment by DenekUrich** [comment]
@morganm24 I tried to write a document - https://docs.google.com/document/d/1bfJlc-Kv6RuKamQY2bKHs-YUHf_q4hLtwhWvPVX-Od4/edit . I think you need to add domains that you use for the testing. At this moment we use my account for the social login configuration.

**Comment by vladyslav2** [comment]
@morganm24 can you take a look on the document and check that you can understand it ?

**Comment by DenekUrich** [comment]
@morganm24 You can give me domains list that you use, I will add them to my social accounts.

**Comment by DenekUrich** [comment]
@morganm24, please give me information about this problem.

**Comment by vladyslav2** [comment]
@DenekUrich we need to make a call with screen share from you
