### ISSUE TITLE
campaign setup, percent that campaign is completed

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#398]
the percentage doesnt equal the amount of information submitted.
![image](https://cloud.githubusercontent.com/assets/21366183/18322047/b1c2ac4c-74fe-11e6-927b-6a210695594f.png)

**Comment by vladyslav2** [comment]
@arthuryip723 will you be able to do this ?

**Comment by vladyslav2** [comment]
@morganm24 i need a table for each filed - how much percent will it give to you

For example:
pitch - 5%
FAQ - 3% and etc

**Comment by arthuryip723** [comment]
@vladyslav2 Sure.
