### ISSUE TITLE
campaign set up, enter button

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#400]
when i press enter during campaign setup. it refreshes to the next page.

**Comment by vladyslav2** [comment]
@morganm24 i think arthur is fixed that, everything is fine now ?

**Comment by morganm24** [comment]
looks good except here when i press enter it jumps to the bottom of the page
![image](https://cloud.githubusercontent.com/assets/21366183/18451744/2c05963a-7906-11e6-951d-0a5856108437.png)

**Comment by morganm24** [comment]
this page still has the enter button issue. it will bring you to the campaign preview page
![image](https://cloud.githubusercontent.com/assets/21366183/18451764/431887c4-7906-11e6-8297-271bca5eeb6b.png)

**Comment by vladyslav2** [comment]
@morganm24 thanks
