### ISSUE TITLE
campaign setup, state drop down

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#402]
delete PALAU
delete MARSHALL ISLANDS
![image](https://cloud.githubusercontent.com/assets/21366183/18324170/18ec8bae-7509-11e6-8626-b53ecd479548.png)
![image](https://cloud.githubusercontent.com/assets/21366183/18324431/769880e0-750a-11e6-86fc-fb193b92ebb0.png)

**Comment by arthuryip723** [comment]
Should be fixed once my commits are pulled.

**Comment by arthuryip723** [comment]
Fixed and checked.
