### ISSUE TITLE
campaign setup, city/state

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#403]
city and state should appear blank until user enters information.
(new york, ny) automatically appears

![image](https://cloud.githubusercontent.com/assets/21366183/18324657/a09a3c3e-750b-11e6-8a24-961b50c56e9f.png)

**Comment by vladyslav2** [comment]
Roman Kuleshov also can do that

so if Artur have other job to do i'll ask roman to do that

**Comment by arthuryip723** [comment]
I think I can do that. But I make need to ask you a question on that today.

**Comment by arthuryip723** [comment]
fixed. included in the pull request.

**Comment by growthfountain** [comment]
@arthuryip723 Can this be closed?

**Comment by arthuryip723** [comment]
yes. fixed.
@vladyslav2
