### ISSUE TITLE
campaign setup, tagline

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#404]
User cannot type more into TAGLINE.. The site limits the amount of information in the box.

![image](https://cloud.githubusercontent.com/assets/21366183/18325260/753da230-750e-11e6-8a5f-10f71d402f42.png)

**Comment by growthfountain** [comment]
This is intentional to prevent breaking the campaign page with an overlong tagline.  Let's test and see if it's too short.

**Comment by growthfountain** [comment]
as per my discussion with @arthuryip723 we will make the character limit 90 (from 30)

**Comment by growthfountain** [comment]
@arthuryip723 can this be closed?
