### ISSUE TITLE
campaign set up, founding date

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#405]
issue 1. Capitalize D in date "Founding Date"
issue 2. capitalize S in structure "Corporate Structure"
issue 2. for mm user should not be able to type in a number larger than 12  (01-12 options)
issue 3. YYYY should be current year or earlier

![image](https://cloud.githubusercontent.com/assets/21366183/18325635/2146c286-7510-11e6-9fd7-4a3041528750.png)

example/ wefunder does not let you enter a date in the future
![image](https://cloud.githubusercontent.com/assets/21366183/18325486/6ca38418-750f-11e6-93b9-79b3b7e9b62e.png)

**Comment by growthfountain** [comment]
@vladyslav2 @MariaKravchuk these are good catches by @morganm24, we should assign them to be fixed

**Comment by vladyslav2** [comment]
@morganm24 please check first
for a second lets create new task and assign it to denis

**Comment by morganm24** [comment]
please add error message to date organized if user enters the wrong info
![image](https://cloud.githubusercontent.com/assets/21366183/18451381/a06a8154-7904-11e6-96f2-bb0fc3355bd3.png)

**Comment by vladyslav2** [comment]
@morganm24 it is totally different problem
can you close that issue and create new ? 
for that one i want denis to help us
