### ISSUE TITLE
campaign setup, main video

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#406]
users should not be required to have a video. it is an option.
it also requires that you enter https://. it should allow users to type www.
![image](https://cloud.githubusercontent.com/assets/21366183/18326257/ef48b0de-7512-11e6-9d29-5c1cbb9c440d.png)

**Comment by vladyslav2** [comment]
@morganm24 please check

**Comment by morganm24** [comment]
@arthuryip723 
please fix the video link issue. user should not be required to enter https:// for either video field.
![image](https://cloud.githubusercontent.com/assets/21366183/18449996/67baa8a2-78ff-11e6-99b4-f518f466eb70.png)

**Comment by vladyslav2** [comment]
@arthuryip723

**Comment by arthuryip723** [comment]
@vladyslav2 @morganm24 
Should have been fixed, see my next push.

**Comment by arthuryip723** [comment]
@morganm24 
Please check and close.
