### ISSUE TITLE
campaign setup team

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#408]
we do not require 2 people. delete the alert box

![image](https://cloud.githubusercontent.com/assets/21366183/18326412/9aa7093a-7513-11e6-917b-37b983461466.png)

**Comment by vladyslav2** [comment]
We require 1 person at least
so we need update text in the box

**Comment by arthuryip723** [comment]
I've updated the text. The change could be seen after a new pull today.
