### ISSUE TITLE
campaign setup/gallery

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#4094]
gallery image upload

image is not uploading

![image](https://user-images.githubusercontent.com/21366183/29894266-bb4a716a-8da2-11e7-81cd-80a9d1882999.png)

**Comment by ratmirasanov** [comment]
@morganm24, I cannot reproduce. Please give me details.

**Comment by ratmirasanov** [comment]
@morganm24, for me -- everything is working.
