### ISSUE TITLE
Contact Us image extends too far to the left

### ISSUE THREAD

**Issue by growthfountain** [vladyslav2/gfwhitelabels#410]
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/pg/contact

The side menu is inaccessible

**Comment by vladyslav2** [comment]
@kenstaut sorry, which menu ?

**Comment by growthfountain** [comment]
The side menu that's present when you click Overview, In the News, etc, disappears when you click Contact Us.

**Comment by growthfountain** [comment]
(this login is Leon btw)

**Comment by MariaKravchuk** [comment]
@NewRoman let`s make a little another another design for this page.
Here is updated design https://www.dropbox.com/home/Maria%20Wireframes/ABOUT%20US/PSD?preview=CONTACT+US.psd

**Comment by NewRoman** [comment]
@morganm24 @MariaKravchuk 

it will be avaiable to check in 30 minutes

http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/contact
