### ISSUE TITLE
campaign setup min/max raise

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#413]
when number is entered.. commas should appear

![image](https://cloud.githubusercontent.com/assets/21366183/18327358/2b16c718-7518-11e6-944e-d5be51f040b0.png)

example/
![image](https://cloud.githubusercontent.com/assets/21366183/18327494/c66bc740-7518-11e6-9cc9-55b3c0e2f37f.png)

**Comment by arthuryip723** [comment]
This feature requires some back-end work, we will release this feature once we get the back-end ready.
