### ISSUE TITLE
campaign setup/perks alert box

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#414]
change the color of this box

![image](https://cloud.githubusercontent.com/assets/21366183/18327958/d50bcff0-751a-11e6-86f7-b30905672776.png)

**Comment by arthuryip723** [comment]
What color would you like?

**Comment by vladyslav2** [comment]
@MariaKravchuk

**Comment by vladyslav2** [comment]
Morgan i will close it for now
and will open that latter
i just won't want to create a mess here

we will came back to that issue
