### ISSUE TITLE
Company

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#418]
Change "Founding date" to "Date Organized" and change entry field to "MM/DD/YY" and make sure the date entered is not greater than todays date

![image](https://cloud.githubusercontent.com/assets/21956276/18328647/b5e18694-751d-11e6-8b31-ac5ad89e5838.png)

**Comment by vladyslav2** [comment]
@kenstaut do we really need to have Date ?

**Comment by kenstaut** [comment]
Yes. Legal requirement

**Comment by arthuryip723** [comment]
Can we try a date picker plugin like this?
https://jqueryui.com/datepicker/
