### ISSUE TITLE
Mobile menu. 

### ISSUE THREAD

**Issue by NewRoman** [vladyslav2/gfwhitelabels#420]

**Comment by NewRoman** [comment]
Make dropdown same apple site for mobile devices
https://github.com/NewRoman/gfwhitelabels/commit/bfb359bef98ed4e3743b17018182f1622289b72a

**Comment by vladyslav2** [comment]
Very nice job Roman !
@MariaKravchuk what do you think ?

**Comment by MariaKravchuk** [comment]
I like it, but the user section does not have dropdown list yet. Also we don`t have the search section. We just have the Explore button on the menu.

**Comment by NewRoman** [comment]
@MariaKravchuk @vladyslav2 
menu for mobile already done. please check it
commits
https://github.com/NewRoman/gfwhitelabels/commit/46129d45db1c7d302609edeab2d6c271a262a5d2
https://github.com/NewRoman/gfwhitelabels/commit/d10a10826628b141c347bd991d62029e2f37a3ec

Available to see here
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/

**Comment by NewRoman** [comment]
@MariaKravchuk 
Please, advise me how to placed this buttons in ttis situation

![_136](https://cloud.githubusercontent.com/assets/8603994/18364926/15f8bf06-7619-11e6-8542-e57cbbcac1fa.png)

**Comment by NewRoman** [comment]
@MariaKravchuk @vladyslav2 

fix mobile menu for unlogin user 

in this commit
https://github.com/NewRoman/gfwhitelabels/commit/af50403ecc8fc8463e6b28142491957833624b31

http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/
