### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#426]
1)When you click on this field the color of text change to gray. It should be always black
![2016-09-08 18 06 18](https://cloud.githubusercontent.com/assets/20995691/18354742/648b654e-75ef-11e6-81b3-f835259618f8.png)

2)The same situation with dropdown 
![2016-09-08 18 10 15](https://cloud.githubusercontent.com/assets/20995691/18354791/9a7e5dbe-75ef-11e6-80d7-9b09666d3ad8.png)

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/company/create
