### ISSUE TITLE
Fix font  size for popovers

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#430]
![screen shot 2016-09-08 at 11 59 38 am](https://cloud.githubusercontent.com/assets/704096/18356687/c40f3718-75bb-11e6-9ef1-3b9ad767e394.png)

**Comment by MariaKravchuk** [comment]
@OstapL @vladyslav2 
Let`s do such text for tips
![2016-09-09 17 35 26](https://cloud.githubusercontent.com/assets/20995691/18390733/19c7e7f6-76b4-11e6-83a6-e1830b52b830.png)

**Comment by OstapL** [comment]
@MariaKravchuk
Fixed #564
change font size and add font bold
align popover to top position
add max-width 500px
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/company/create
