### ISSUE TITLE
TEXT LOOKS UGLU !

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#431]
OSTAP!
![screen shot 2016-09-08 at 12 27 04 pm](https://cloud.githubusercontent.com/assets/704096/18357610/a218ce68-75bf-11e6-822d-c6cd10997a14.png)

what happens ?! Why does we two fields with different text color ?!!!

**Comment by OstapL** [comment]
@leonstiel @vladyslav2 
fixed 
change color input 
#464 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/company/create

**Comment by vladyslav2** [comment]
thanks
