### ISSUE TITLE
Add option to delete team members

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#433]
![screen shot 2016-09-08 at 12 34 41 pm](https://cloud.githubusercontent.com/assets/704096/18357904/aa5b9a82-75c0-11e6-8a72-f29a6d75c662.png)

Maria i need a design from you
and i think its better to move edit button to the top left corner

**Comment by MariaKravchuk** [comment]
@vladyslav2 https://www.dropbox.com/home/Maria%20Wireframes/Create%20Campaign/PSD?preview=TEAM+MEMBERS%3AButtons.psd

I think on the top we should add only delete option
