### ISSUE TITLE
Add state list to the dropdown on the add team member page

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#434]
![screen shot 2016-09-08 at 12 36 38 pm](https://cloud.githubusercontent.com/assets/704096/18357974/f4977378-75c0-11e6-9631-9535443bbd09.png)

**Comment by arthuryip723** [comment]
I fixed this. Just need to take the pull request.

**Comment by arthuryip723** [comment]
@morganm24
Please check and close.

**Comment by morganm24** [comment]
please delete "federated states of micronesia" from drop down @arthuryip723

**Comment by arthuryip723** [comment]
@morganm24
Sure.
