### ISSUE TITLE
campaign specifics page, make calculators links actual work

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#435]
![screen shot 2016-09-08 at 12 38 11 pm](https://cloud.githubusercontent.com/assets/704096/18358034/33ca5b78-75c1-11e6-9cf4-ee5964c6b7c3.png)

it should open calculators in a new window

**Comment by arthuryip723** [comment]
Fixed. Included in the pull request.

**Comment by arthuryip723** [comment]
@morganm24
Pleas check and close.
The last item, What's My Business Worth?, has not been implemented. Thus it's not going to anywhere. But the other links are good.

**Comment by arthuryip723** [comment]
@vladyslav2 @kenstaut @morganm24
Pleas check and close.
The last item, What's My Business Worth?, has not been implemented. Thus it's not going to anywhere. But the other links are good.
