### ISSUE TITLE
Tall images inappropriately cut. 

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#442]
In the campaign media section, the image was cut inappropriately. Pleas refer to the effect and the original image.
![tall](https://cloud.githubusercontent.com/assets/1624001/18365831/38e729c6-75e2-11e6-83c5-3b07eb54034d.png)
![screen shot 2016-09-08 at 4 33 14 pm](https://cloud.githubusercontent.com/assets/1624001/18365841/426cbad8-75e2-11e6-82b9-f49e5579736f.png)

**Comment by vladyslav2** [comment]
we need to add jquery croper for that problem
will close that issue
