### ISSUE TITLE
index campaign listing page, border

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#444]
can you create a border around each campaign. if user's image is white it blends in with the background.

![image](https://cloud.githubusercontent.com/assets/21366183/18366740/f01f62f4-75e5-11e6-9f8c-aaf41933067b.png)

**Comment by MariaKravchuk** [comment]
@OstapL https://www.dropbox.com/home/Maria%20Wireframes/Campaign%20list?preview=LIST.psd

please add border like in updated layout
