### ISSUE TITLE
signup/login page link does not work

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#445]
after you click login button top right, you are brought tot he login page.
issue: click sign up link does not work

![image](https://cloud.githubusercontent.com/assets/21366183/18367265/3e1cfc80-75e8-11e6-906d-9fce647446a5.png)

**Comment by arthuryip723** [comment]
It's caused by a typo. I have fixed this in my local version. Should be live on Monday.

**Comment by vladyslav2** [comment]
@morganm24  !

**Comment by vladyslav2** [comment]
@morganm24 i took care about that
please check
