### ISSUE TITLE
Show all risk should not be collapsable.

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#449]
@MariaKravchuk Maria please redesign the show all risk section, @leonstiel Leon thinks that it should not be collapsible. Thank you very much.
![screen shot 2016-09-08 at 6 39 00 pm](https://cloud.githubusercontent.com/assets/1624001/18369401/8e23e8e6-75f3-11e6-852b-9fb4f498803b.png)

**Comment by vladyslav2** [comment]
Artur it is JavaScript issue not a design

**Comment by vladyslav2** [comment]
So Maria Wil not be able to help you

**Comment by MariaKravchuk** [comment]
@vladyslav2 Vlad, I have already updated the Risks and wrote the appropriate issue

@arthuryip723 https://www.dropbox.com/home/Maria%20Wireframes/Company%20page?preview=COMPANY+PAGE.psd
Arthur look at the risks section on this layout. There should be by default only 4 risks. Other risks user could see on link "See all Risks"

**Comment by arthuryip723** [comment]
@MariaKravchuk Great. Thank you very much.
