### ISSUE TITLE
campign preview/social media icons

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#461]
if user does not input these fields then they should not appear

![image](https://cloud.githubusercontent.com/assets/21366183/18391700/d4339064-767c-11e6-8a00-00f85fa1f22f.png)

**Comment by vladyslav2** [comment]
@morganm24 have we fixed this ?

**Comment by morganm24** [comment]
good 
![image](https://cloud.githubusercontent.com/assets/21366183/18454014/07197832-7910-11e6-94eb-fd4ca28d6370.png)
