### ISSUE TITLE
campaign/additional video

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#462]
if user does not additional video, this should not appear

![image](https://cloud.githubusercontent.com/assets/21366183/18391825/5112bf92-767d-11e6-96aa-a2c6b45b8260.png)

**Comment by growthfountain** [comment]
@vladyslav2 @arthuryip723 let's fix

**Comment by arthuryip723** [comment]
@vladyslav2 
Looks like the additional_video field is never empty. It will contains at least an entry even if it is null.

**Comment by vladyslav2** [comment]
@morganm24 can you check this ? i fixed this but i want you to check it (create new company/compaign and check it)
