### ISSUE TITLE
campaign setup/team member/social media

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#463]
Change text your personal linkedin link to: "LinkedIn" Inside box "Your LinkedIn profile"
Facebook section change the inside field box to "Your Facebook profile"

![image](https://cloud.githubusercontent.com/assets/21366183/18392047/4c01a116-767e-11e6-9e17-2c649c2b7481.png)

**Comment by arthuryip723** [comment]
Fixed. Included in the pull request.

**Comment by growthfountain** [comment]
@arthuryip723 can this be closed?

**Comment by vladyslav2** [comment]
@morganm24 ?
