### ISSUE TITLE
articles and press

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#466]
articles of press format must change:
![image](https://cloud.githubusercontent.com/assets/21366183/18393688/5c52366a-7684-11e6-8404-b622bfe4f0cc.png)

change to format like this. format should be the Article Title and the Link below
![image](https://cloud.githubusercontent.com/assets/21366183/18393392/2b1b4056-7683-11e6-885f-fc666106db39.png)

**Comment by growthfountain** [comment]
we have an open item to remove the background image.  let's review after that is complete
