### ISSUE TITLE
questions on preview do not match campaign setup

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#467]
the questions asked do not match the campaign preview
![image](https://cloud.githubusercontent.com/assets/21366183/18393857/3264fc56-7685-11e6-89f0-c0e361a64b05.png)

**Comment by growthfountain** [comment]
@vladyslav2 @arthuryip723 this should be corrected

**Comment by vladyslav2** [comment]
@morganm24 please check
