### ISSUE TITLE
campaign preview/amount funded

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#468]
this text should not appear
![image](https://cloud.githubusercontent.com/assets/21366183/18393900/5f714ca4-7685-11e6-9572-3221e4074ea6.png)

**Comment by growthfountain** [comment]
This should say less than 20% funded, not Nan%, and should show the bar partially filled.  This worked on prior versions

**Comment by morganm24** [comment]
"less than nan% funded" appears when user does not enter data for campaign min and max funding goals. is it possible to always show less than 20% with or without entering details?
*this is not a priority. (can wait)

**Comment by vladyslav2** [comment]
@morganm24  ?
