### ISSUE TITLE
ACCOUNT

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#47]
@NewRoman 
1) Distance from tab`s border to input should be 50 px.
![2016-08-12 20 57 15](https://cloud.githubusercontent.com/assets/20995691/17632238/f8149f0e-60cf-11e6-8988-5d328d07b993.png)

2) Inscription "Maria Kravchuk," must be 18 font size. And bottom space from the inscription to the image should be 25 px.
![2016-08-12 21 05 55](https://cloud.githubusercontent.com/assets/20995691/17632392/c185cd86-60d0-11e6-9a45-e76198a20cfe.png)

3) The space between inputs should be 25 px. Names of inputs should be black. Only the "Street address 2" is gray, because it is optional.
![2016-08-12 21 07 42](https://cloud.githubusercontent.com/assets/20995691/17632530/87d6f1fe-60d1-11e6-9425-df5ab9ae8bbb.png)

4) This icon should be gray.
![2016-08-12 21 14 41](https://cloud.githubusercontent.com/assets/20995691/17632592/eb9db27c-60d1-11e6-891e-d206703c31ff.png)

5) The top space above the "Save" button should be 50 px. Bottom - 85 px.
![2016-08-12 21 16 04](https://cloud.githubusercontent.com/assets/20995691/17632671/487039f2-60d2-11e6-8cbe-6f9932b245f0.png)

6) Tab's Border should be aligned on the right edge of inputs.
![2016-08-12 21 20 19](https://cloud.githubusercontent.com/assets/20995691/17633087/539655bc-60d4-11e6-8666-fe6e3e465be0.png)

7) The top space above the inscription "Drop your profile photo here" to the picture should be     25 px. Bottom space from the inscription to the icon "camera" must be 20 px. 
![2016-08-12 21 34 03](https://cloud.githubusercontent.com/assets/20995691/17633260/0dccd3ca-60d5-11e6-99f3-7df827b71f02.png)

8)Please check the input field according to the design. Here they do not meet the layout.
![2016-08-12 21 40 28](https://cloud.githubusercontent.com/assets/20995691/17633391/bcc234a6-60d5-11e6-8bcc-155f68e60577.png)

9) Between the last input and message should be a gray line.
Also, right message's edge should be aligned with the edges of inputs.
![2016-08-12 22 00 53](https://cloud.githubusercontent.com/assets/20995691/17634222/32510608-60da-11e6-9784-042f12e79f1a.png)

10) Check how inputs made in the layout, because it does not fit my design.
![2016-08-12 22 16 46](https://cloud.githubusercontent.com/assets/20995691/17634349/dc49e198-60da-11e6-81c7-2f24dc9f3068.png)

11) In the picture should be displayed user's initials by default
![2016-08-12 22 20 12](https://cloud.githubusercontent.com/assets/20995691/17634762/c3d2fc6a-60dc-11e6-85cb-b051f417ad33.png)

**Comment by NewRoman** [comment]
Point which closed: 
1,2,5, 7, 8, 9, 10

https://github.com/vladyslav2/gfwhitelabels/pull/58

https://github.com/NewRoman/gfwhitelabels/commit/d95cdbc4462373f83b82efe224d88bf52be3fbfa
