### ISSUE TITLE
campaign setup/team/specifics button

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#475]
there is no button save or next. we need to create a button
![image](https://cloud.githubusercontent.com/assets/21366183/18396322/0f2d655a-7691-11e6-9cac-481efd37ddf9.png)

go to specifics button should say "save"
![image](https://cloud.githubusercontent.com/assets/21366183/18395997/51fc0c76-768f-11e6-8e52-c4eb077792dd.png)

**Comment by growthfountain** [comment]
@morganm24  let's get user feedback on this one, because you aren't actually saving anything (you save from the team member detail view)

**Comment by morganm24** [comment]
![image](https://cloud.githubusercontent.com/assets/21366183/18396441/99bb326a-7691-11e6-9e0d-7ae03c0ea841.png)

**Comment by growthfountain** [comment]
We should consider this behavior after we clear out the bugs

**Comment by vladyslav2** [comment]
@morganm24 Leon whats it to be go to the specific
i'll close for now

guys you need to decide how to name a button
