### ISSUE TITLE
campaign setup/company/incorrect date

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#477]
if incorrect date is entered you cannot move to the next page. but there is no error message
please create an error message

![image](https://cloud.githubusercontent.com/assets/21366183/18396277/d2f607a4-7690-11e6-9083-fbda5653e158.png)

**Comment by growthfountain** [comment]
@vladyslav2 @arthuryip723 pls fix, if there is validation that prevents you from moving forward, there has to be an error message as to what's wrong.

**Comment by vladyslav2** [comment]
@DenekUrich:

```
companies/serializers.py:
 9     def validate(self, data):                                                   
10         # ToDo                                                                  
11         # Make widget and validate_founding_date                                
12         data['founding_date'] = self.initial_data['founding_date__year'] + '-' + self.initial_data['founding_date__month'] + '-' + self.initial_data['founding_date__day']
13         self.initial_data['founding_date'] = data['founding_date']              
14         return data 
```

Can we do better validation here please ? We need to valid each field and base on that return error message.

From the API standpoint i need this:
/api/company
for GET response
```
....
founding_date: "2002-12-12"
```

i send to /api/company
```
...
founding_date__day: "12"
founding_date__month: "12"
founding_date__year: "2002"
....
```

In case of error or wrong day/month/year i need to get in return:
Status Code:400 Bad Request

```
{
...
founding_date: 'Month cannot be negative'
...
}
```

**Comment by DenekUrich** [comment]
duplicate with [https://github.com/vladyslav2/gfwhitelabels/issues/477](https://github.com/vladyslav2/gfwhitelabels/issues/477)

**Comment by DenekUrich** [comment]
I fixed validation. **I wait from frontend date in format { founding_date: YYYY-MM-DD }**
For frontend you can use limits with type="number" min="1" max="12" for months to prevent an incorrect user input.
