### ISSUE TITLE
campaign setup/first page

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#478]
when user is on company page (first page), they cannot click on the other sections even if all fields are completed. the only way to move forward is to click the save button at the bottom

![image](https://cloud.githubusercontent.com/assets/21366183/18397336/b5ffeb56-7695-11e6-9bbd-f0a5731feaa3.png)

**Comment by growthfountain** [comment]
let's leave for now, as we want the user to get into the habit of clicking the save button.  Perhaps we can highlight the save functionality if someone tries to navigate this way, in the future.

**Comment by vladyslav2** [comment]
@morganm24 please check
