### ISSUE TITLE
campaign preview/citystate 

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#487]
this is no longer matching with the city/state i am entering.
is this matched to zipcode or city/state dropdown?
![image](https://cloud.githubusercontent.com/assets/21366183/18402427/4d371f1e-76ad-11e6-8b25-2652b62f6d6b.png)

**Comment by morganm24** [comment]
same issue with this location

![image](https://cloud.githubusercontent.com/assets/21366183/18402486/9520544e-76ad-11e6-9a18-d1d472efab99.png)

**Comment by growthfountain** [comment]
@vladyslav2 @arthuryip723 pls fix, this should show the correct info

**Comment by arthuryip723** [comment]
@morganm24 
I think I have fixed this issue. Please check.

**Comment by vladyslav2** [comment]
@morganm24 do not forget to close issues ! why you are not closing it ?
thats why our ticket counter is keep growing !

**Comment by morganm24** [comment]
looks good but please capitalize the first letter
![image](https://cloud.githubusercontent.com/assets/21366183/18449317/bf0ff06a-78fc-11e6-90e5-6a9a634d8e04.png)
![image](https://cloud.githubusercontent.com/assets/21366183/18449322/c92a7142-78fc-11e6-810e-ac82553a2a8b.png)

**Comment by vladyslav2** [comment]
@arthuryip723

**Comment by morganm24** [comment]
and here too
![image](https://cloud.githubusercontent.com/assets/21366183/18449796/99d0f7ac-78fe-11e6-9e10-0f089d6d6602.png)

**Comment by arthuryip723** [comment]
@OstapL 
We need to capitalize the city, probably using the text-transform: capitalize; property. We think you're best person to work on this. Could you fix this issue? Thanks.

**Comment by vladyslav2** [comment]
@OstapL

**Comment by OstapL** [comment]
@arthuryip723 @vladyslav2 @morganm24
Fixed #690
