### ISSUE TITLE
On dev server email stop working (i do have smtp running on my machine on 1025 port)

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#488]
django_1    | Traceback (most recent call last):
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
django_1    |     return self.application(environ, start_response)
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
django_1    |     response = self.get_response(request)
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
django_1    |     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 289, in handle_uncaught_exception
django_1    |     return debug.technical_500_response(request, *exc_info)
django_1    |   File "/usr/local/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
django_1    |     six.reraise(exc_type, exc_value, tb)
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
django_1    |     response = self.process_exception_by_middleware(e, request)
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
django_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
django_1    |     return func(*args, **kwargs)
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
django_1    |     return view_func(*args, **kwargs)
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
django_1    |     return self.dispatch(request, *args, **kwargs)
django_1    |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
django_1    |     response = self.handle_exception(exc)
django_1    |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
django_1    |     response = handler(request, *args, **kwargs)
django_1    |   File "/usr/local/lib/python2.7/site-packages/rest_framework/generics.py", line 192, in post
django_1    |     return self.create(request, *args, **kwargs)
django_1    |   File "/usr/local/lib/python2.7/site-packages/rest_auth/registration/views.py", line 38, in create
django_1    |     user = self.perform_create(serializer)
django_1    |   File "/usr/local/lib/python2.7/site-packages/rest_auth/registration/views.py", line 48, in perform_create
django_1    |     None)
django_1    |   File "/usr/local/lib/python2.7/site-packages/allauth/account/utils.py", line 182, in complete_signup
django_1    |     signal_kwargs=signal_kwargs)
django_1    |   File "/usr/local/lib/python2.7/site-packages/allauth/account/utils.py", line 142, in perform_login
django_1    |     send_email_confirmation(request, user, signup=signup)
django_1    |   File "/usr/local/lib/python2.7/site-packages/allauth/account/utils.py", line 311, in send_email_confirmation
django_1    |     signup=signup)
django_1    |   File "/usr/local/lib/python2.7/site-packages/allauth/account/models.py", line 58, in send_confirmation
django_1    |     confirmation.send(request, signup=signup)
django_1    |   File "/usr/local/lib/python2.7/site-packages/allauth/account/models.py", line 122, in send
django_1    |     get_adapter(request).send_confirmation_mail(request, self, signup)
django_1    |   File "/usr/local/lib/python2.7/site-packages/allauth/account/adapter.py", line 395, in send_confirmation_mail
django_1    |     ctx)
django_1    |   File "/usr/local/lib/python2.7/site-packages/allauth/account/adapter.py", line 127, in send_mail
django_1    |     msg.send()
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/core/mail/message.py", line 292, in send
django_1    |     return self.get_connection(fail_silently).send_messages([self])
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
django_1    |     new_conn_created = self.open()
django_1    |   File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 58, in open
django_1    |     self.connection = connection_class(self.host, self.port, **connection_params)
django_1    |   File "/usr/local/lib/python2.7/smtplib.py", line 256, in __init__
django_1    |     (code, msg) = self.connect(host, port)
django_1    |   File "/usr/local/lib/python2.7/smtplib.py", line 316, in connect
django_1    |     self.sock = self._get_socket(host, port, self.timeout)
django_1    |   File "/usr/local/lib/python2.7/smtplib.py", line 291, in _get_socket
django_1    |     return socket.create_connection((host, port), timeout)
django_1    |   File "/usr/local/lib/python2.7/socket.py", line 575, in create_connection
django_1    |     raise err
django_1    | error: [Errno 111] Connection refused

**Comment by vladyslav2** [comment]
and the most bigger issue that i cannot create account because of that.

Email error should not affect on the process flow at all

**Comment by DenekUrich** [comment]
fixed in this [commit](https://bitbucket.org/vladyslav_t/gfdjango/commits/45d62f600b39112467d94846e1edceed79115801)

**Comment by vladyslav2** [comment]
thanks
