### ISSUE TITLE
campaign preview/media gallery images

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#489]
when you click on an image from the media gallery
![image](https://cloud.githubusercontent.com/assets/21366183/18402596/2cc99544-76ae-11e6-8ee1-5019a7bc6f98.png)

it appears like this
![image](https://cloud.githubusercontent.com/assets/21366183/18402612/3fe8ceec-76ae-11e6-8bf0-b74d23f0a0df.png)

**Comment by growthfountain** [comment]
this looks like a duplicate with https://github.com/vladyslav2/gfwhitelabels/issues/549
