### ISSUE TITLE
campign preview/college&hometown

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#491]
this should not be an option to click.

![image](https://cloud.githubusercontent.com/assets/21366183/18402839/7af9ed94-76af-11e6-84e7-7fa4435f62b5.png)

**Comment by arthuryip723** [comment]
@growthfountain sure.

**Comment by arthuryip723** [comment]
@vladyslav2 @growthfountain 
I've fixed this. You guys don't redo this. thanks.

**Comment by vladyslav2** [comment]
@arthuryip723 sorry, but it is still clickable

**Comment by MariaKravchuk** [comment]
@OstapL can you fix it? this two elements should not be clickable and please make them in gray colors like in layout
![2016-09-15 13 12 41](https://cloud.githubusercontent.com/assets/20995691/18546374/4c94249c-7b46-11e6-88c8-940806b1e73e.png)
