### ISSUE TITLE
Day of Founding Date Is Not Saved. And you don't know which is day, which is month.

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#494]
@vladyslav2 As in title.
![screen shot 2016-09-09 at 6 33 18 pm](https://cloud.githubusercontent.com/assets/1624001/18404944/ec2eceba-76bb-11e6-9146-4d6ed6d472d9.png)

**Comment by vladyslav2** [comment]
Fixed, please take a look

**Comment by vladyslav2** [comment]
@arthuryip723 please check
