### ISSUE TITLE
Node 6.5 (associated with newer bootstrap version) cause problem in 'gulp styles'

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#497]
@OstapL @vladyslav2 

Steps to repeat:
1, brew upgrade node (should upgrade to 6.5)
2, make a new clone of the project
3, npm install
4, gulp styles

you would see the following error.
[00:10:04] Using gulpfile ~/Documents/codes/gf_fork/gulpfile.js
[00:10:04] Starting 'styles'...
Error in plugin 'sass'
Message:
    node_modules/bootstrap/scss/_alert.scss
Error: Undefined operation: "8px 21px times 2".
        on line 29 of node_modules/bootstrap/scss/_alert.scss
>>   padding-right: ($alert-padding * 2);
   ------------------^

**Comment by vladyslav2** [comment]
Остап это не связанно с nodejs
просто версия bootstrap последняя взята

**Comment by arthuryip723** [comment]
A way to fix that is in package.json, use "bootstrap": "4.0.0-alpha.3", instead of "bootstrap": "^4.0.0-alpha.3", notice the difference of '^'.
only alpha.3 will work. alpha.4 and alpha2 would not work.
