### ISSUE TITLE
Can Not Delete the Last Perk

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#501]
As in title.
The last perk can be remove on the page. But it is not saved even if you click save. Navigate back to that page you can still see the last perk.
@vladyslav2

**Comment by morganm24** [comment]
when user enters perks in campaign setup and they decide to delete perks, the delete action does not save.
 ex/ 3 perks are created, then delete all 3 perks, click save. ERROR: both campaign setup and campaign preview are displaying the perks.

**Comment by vladyslav2** [comment]
please check
