### ISSUE TITLE
Can Not Go through Specifics

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#502]
I am not sure if this happens to all campaigns. But for this one, I can not go through the page by clicking save. It shows 'Internal Server Error'.
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/campaign/specifics/45
user: admin@gf.com
@vladyslav2

**Comment by vladyslav2** [comment]
Can you give a screenshot and link to campaign ?

**Comment by vladyslav2** [comment]
And can you give response from server ?

**Comment by arthuryip723** [comment]
@vladyslav2 
![screen shot 2016-09-10 at 12 01 06 pm](https://cloud.githubusercontent.com/assets/1624001/18411839/80cc6bbc-774e-11e6-95db-ff9fea1569eb.png)
![screen shot 2016-09-10 at 12 02 14 pm](https://cloud.githubusercontent.com/assets/1624001/18411840/80cd6328-774e-11e6-870c-a4ca509ec4e1.png)

**Comment by vladyslav2** [comment]
@arthuryip723 can you check please ?
