### ISSUE TITLE
page invest not work 

### ISSUE THREAD

**Issue by OstapL** [vladyslav2/gfwhitelabels#509]
page invest not works on all servers

**Comment by arthuryip723** [comment]
![screen shot 2016-09-10 at 4 16 48 pm](https://cloud.githubusercontent.com/assets/1624001/18413310/0f8b73ca-7772-11e6-9576-f8860cd0684e.png)
@vladyslav2 
investModel not defined.

**Comment by arthuryip723** [comment]
@vladyslav2 
Here we really need you to look.
