### ISSUE TITLE
paybackshare calculator fixes

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#513]
Постарайся разобраться, если будут вопросы напиши буду пытаться выяснять детали 

[paybackcalculator.xlsx](https://github.com/vladyslav2/gfwhitelabels/files/466063/paybackcalculator.xlsx)

**Comment by rkuleshov-corevalue** [comment]
Done. Pull request https://github.com/vladyslav2/gfwhitelabels/pull/568
