### ISSUE TITLE
Campaigns add site name in the admin list

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#514]
http://jd-django.jwpbirm43d.us-east-1.elasticbeanstalk.com/admin/campaigns/campaign/

тут хотелось бы видеть сайт сразу же

**Comment by vladyslav2** [comment]
2. аналогично в списке компаний http://jd-django.jwpbirm43d.us-east-1.elasticbeanstalk.com/admin/companies/company/

**Comment by vladyslav2** [comment]
3. http://jd-django.jwpbirm43d.us-east-1.elasticbeanstalk.com/admin/investment/investment/ и в списке инвестиций

**Comment by DenekUrich** [comment]
Done:
For Campaign:
![screenshot-jd-django jwpbirm43d us-east-1 elasticbeanstalk com 8000-2016-09-12-13-42-06](https://cloud.githubusercontent.com/assets/101607/18433237/2d43e1a8-78ef-11e6-97a5-4aa05e5e6098.png)
For Company:
![screenshot-jd-django jwpbirm43d us-east-1 elasticbeanstalk com 8000-2016-09-12-13-44-19](https://cloud.githubusercontent.com/assets/101607/18433244/35f8be86-78ef-11e6-83b4-0fd58f3d7100.png)
For Investment:
![screenshot-jd-django jwpbirm43d us-east-1 elasticbeanstalk com 8000-2016-09-12-13-44-55](https://cloud.githubusercontent.com/assets/101607/18433247/3d5dd864-78ef-11e6-9064-8091f6961485.png)
