### ISSUE TITLE
КТО НАПИСАЛ ТАКОЙ КОД??? 

### ISSUE THREAD

**Issue by OstapL** [vladyslav2/gfwhitelabels#519]
.text_block
	.page_title
		width: 100%
		border-color: $light_grey

		h4
			font-weight: 400
	ul 
		li
			a//TODO перенести в общие стили для ссылок всего сайта
				color: $small-text

				&:hover 
					color: rgba($footer_text, 0.6)

		&.simple-list 
			padding-left: rem(20)
			li 
				margin-bottom: rem(15)

				a
					color: $wild_willow
у нас есть документация где есть все ссылки какие Мария нарисовала ? 
есть пример использования ) 
пожалуйста используйте как в примере )

**Comment by DenekUrich** [comment]
git blame?

**Comment by OstapL** [comment]
a//TODO перенести в общие стили для ссылок всего сайта
            color: $small-text
            &:hover 
                color: rgba($footer_text, 0.6)
у нас есть дополнительные класы ссылок 
            a
                color: $wild_willow
для такой ссылки у нас так же есть дополнительный класс

**Comment by NewRoman** [comment]
писал я этот код, когда еще не до конца разобрался в структуре файлов стилей. спасибо что написал, эти стили скорее всего уже и не используються вовсе.

**Comment by OstapL** [comment]
сделай доброе дело ) удали их ) везде где есть ссылки старайся использовать link-1 ну и так далее
