### ISSUE TITLE
campaign preview/team member picture

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#534]
user should not able to click on team member image.
(issue: user is brought to the top of the campaign when they click on the team member image)

![image](https://cloud.githubusercontent.com/assets/21366183/18447283/f48bcf6a-78f3-11e6-8706-e88bd3a22425.png)

**Comment by morganm24** [comment]
if user does not upload image for team members this image should appear instead of a white box.

![image](https://cloud.githubusercontent.com/assets/21366183/18447899/95ac28fc-78f6-11e6-93a4-9ddb6301bb91.png)

**Comment by morganm24** [comment]
same here


![image](https://cloud.githubusercontent.com/assets/21366183/18478800/8abac6ce-79a0-11e6-92f4-434b67d96a5b.png)

**Comment by MariaKravchuk** [comment]
@morganm24 @vladyslav2 
I want that we will be constant concerning our different elements in design. Therefore I suggest following default picture

![create-campaign_team-members](https://cloud.githubusercontent.com/assets/20995691/18546063/ada9e368-7b44-11e6-8198-66e20a50b296.png)
![team-members_buttons](https://cloud.githubusercontent.com/assets/20995691/18546064/adaab298-7b44-11e6-84f5-a87b8bdde74d.png)
