### ISSUE TITLE
login page/terms of service/privacy policy

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#535]
issue 1: there are no pages attached to those links. 
issue 2: i clicked on those links and all my data was deleted
when user clicks of terms of service they should be directed to this link http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/pg/terms_of_use
when user clicks on privacy policy they should be directed to this link http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/pg/privacy_policy
![image](https://cloud.githubusercontent.com/assets/21366183/18447757/024fd7e8-78f6-11e6-939c-543c3734465d.png)

**Comment by vladyslav2** [comment]
@NewRoman !

**Comment by NewRoman** [comment]
@vladyslav2 @morganm24 

fixed it in commit
https://github.com/NewRoman/gfwhitelabels/commit/4a550881e0ba169a604438fb036bcb7ef0878cd4
