### ISSUE TITLE
terms of use bottom page, text edit

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#536]
@arthuryip723 
please change this to terms of service

![image](https://cloud.githubusercontent.com/assets/21366183/18448193/17e4bb4e-78f8-11e6-8bf7-c9023e2a0336.png)

**Comment by vladyslav2** [comment]
@NewRoman !

**Comment by NewRoman** [comment]
@vladyslav2 @morganm24 

fixed it in commit
https://github.com/NewRoman/gfwhitelabels/commit/ad1a2a862e750c81ba76ae646fd2aba1ac9cd61b

**Comment by MariaKravchuk** [comment]
@NewRoman also change it here (title, bread crumbs, title of side menu) http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/pg/terms_of_use

**Comment by NewRoman** [comment]
@morganm24 @MariaKravchuk 

fix it in commit
https://github.com/NewRoman/gfwhitelabels/commit/3c8629c922ee8d68b30d539c11359e8b61eb95c0

**Comment by NewRoman** [comment]
@morganm24 @MariaKravchuk 

ready to check
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/terms_of_use
