### ISSUE TITLE
preview campaign/pre money valuation

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#538]
if user enters pre money valuation larger than 4 digits, it will not show up on campaign listing page

![image](https://cloud.githubusercontent.com/assets/21366183/18448647/e372405a-78f9-11e6-9b69-0cd6a48f3465.png)

thumbnail will only show 4 digits
![image](https://cloud.githubusercontent.com/assets/21366183/18448746/3efe4fb8-78fa-11e6-88d5-c6ce1f16fd0d.png)

please edit the text to say "Valuation" instead of pre money valuation.
![image](https://cloud.githubusercontent.com/assets/21366183/18448795/718d22b0-78fa-11e6-8378-9a8e0fa3916b.png)

*make sure you do not change this text
![image](https://cloud.githubusercontent.com/assets/21366183/18448835/92118a62-78fa-11e6-9784-24e5b4ad2091.png)

**Comment by vladyslav2** [comment]
@arthuryip723 do you have ideas how to do that ?
can you convert 300,000 to 300K  and 3,000,000 to 3M ?

**Comment by arthuryip723** [comment]
@morganm24 
Please check and close this.
