### ISSUE TITLE
login sign in page. space from top

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#542]
*not important

sign up page too far from top of page. (compared to log in page. )
please raise the sign up text

![image](https://cloud.githubusercontent.com/assets/21366183/18451562/769ee9e0-7905-11e6-9982-26721a454287.png)

![image](https://cloud.githubusercontent.com/assets/21366183/18451567/7f40712c-7905-11e6-950f-fa363061ba92.png)

**Comment by vladyslav2** [comment]
@NewRoman

**Comment by NewRoman** [comment]
@MariaKravchuk @morganm24 

fix in this commit 
https://github.com/NewRoman/gfwhitelabels/commit/71ae8bfd3817251c568fef549cbf9d0cd70ce9d1
