### ISSUE TITLE
create document for reset password/update password from backend

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#548]
@DenekUrich 
we need a documentation (requests with a parameters)
to get connect reset/change password with your API

**Comment by DenekUrich** [comment]
1. send POST {email: 'some@example.com'} to /password/reset/, you will receive link like as /password/confirm/?uid=some_uid&token=some_token
1. send POST {new_password1: 'password', new_password2: 'password', uid: 'uid_from_get', token: 'token_from_get'}

**Comment by DenekUrich** [comment]
@vladyslav2 Please try and notify me.

**Comment by vladyslav2** [comment]
Thanks 

We need to store as a document somewhere

**Comment by arthuryip723** [comment]
@DenekUrich @vladyslav2 
send POST {new_password1: 'password', new_password2: 'password', uid: 'uid_from_get', token: 'token_from_get'}to /rest-auth/password/reset/confirm/

Hello Denis,

1, Should confirming new password also do the login as well? Right now the confirm new password API doesn't do that?
2, Should there be a way to tell that the password has been reset?

Thanks!
