### ISSUE TITLE
campaign preview/galley/images

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#549]
when you click on image it should expand and you should be able to scroll through images.
![image](https://cloud.githubusercontent.com/assets/21366183/18453199/23c55996-790c-11e6-9e9d-14bd9034a45d.png)

issue: user is brought to a new page and image does not appear larger
![image](https://cloud.githubusercontent.com/assets/21366183/18453181/134a3410-790c-11e6-825e-bd5ce4e2597f.png)

example of how it should look
![image](https://cloud.githubusercontent.com/assets/21366183/18453223/3aaf83f2-790c-11e6-9d7a-46bdf2a06118.png)

**Comment by MariaKravchuk** [comment]
@vladyslav2 I think this is important, we should fix it

**Comment by vladyslav2** [comment]
@morganm24 can you check please ?
