### ISSUE TITLE
campaign setup/specifics/premoney valuation

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#551]
data gets erased when i click save

![image](https://cloud.githubusercontent.com/assets/21366183/18453675/6a068e46-790e-11e6-8d68-082ae99ffe1b.png)

**Comment by MariaKravchuk** [comment]
@kenstaut @leonstiel @vladyslav2 @arthuryip723 
Guys if i understood right we do not need Minimum Equity Offered/Maximum Equity Offered fields for now. Should we remove it from Specifics page?

**Comment by kenstaut** [comment]
Please leave it on the specifics page - it's really more for the issuer to see. Thank you

Sent from my iPhone

On Sep 15, 2016, at 5:53 AM, MariaKravchuk <notifications@github.com<mailto:notifications@github.com>> wrote:


@kenstaut<https://github.com/kenstaut> @leonstiel<https://github.com/leonstiel> @vladyslav2<https://github.com/vladyslav2> @arthuryip723<https://github.com/arthuryip723>
Guys if i understood right we do not need Minimum Equity Offered/Maximum Equity Offered fields for now. Should we remove it from Specifics page?

-
