### ISSUE TITLE
campaign setup/error message

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#553]
@DenekUrich 
please add error message to date organized if user enters the wrong info

![image](https://cloud.githubusercontent.com/assets/21366183/18454563/1110ecdc-7913-11e6-9f1b-4ad3d531837c.png)

**Comment by DenekUrich** [comment]
In the right side of menu we have assignees, please use it to assign issues to me.

**Comment by DenekUrich** [comment]
Vlad please sync and check it with [https://github.com/vladyslav2/gfwhitelabels/issues/477](https://github.com/vladyslav2/gfwhitelabels/issues/477)
