### ISSUE TITLE
Add new fields to Create Company page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#573]
@OstapL @vladyslav2 @leonstiel 

We should add 2 new fields here - Industry and Jurisdiction of Incorporation/Organization

![2016-09-13 18 09 45](https://cloud.githubusercontent.com/assets/20995691/18479397/7ef71c9c-79dd-11e6-950b-c5449ff18e26.png)

For Industry dropdown use these fields and let issuers choose multiple fields:
1.    Art & Entertainment 
2.    Food & Beverage 
3.    Electronics & Technology 
4.    Health & Wellness
5.    Fashion & Beauty 
6.    Sports
7.    Animals & Environment 
8.    Education 
9.    Community

Also change it
![2016-09-16 20 56 05](https://cloud.githubusercontent.com/assets/20995691/18596041/0313e4be-7c50-11e6-9ab8-027e8ea9cfef.png)

Please see updated layout https://www.dropbox.com/home/Maria%20Wireframes/Create%20Company

**Comment by OstapL** [comment]
@vladyslav2 
ты добавишь я подправлю ? или как ?

**Comment by vladyslav2** [comment]
please check
