### ISSUE TITLE
menu when scrolling does not work

### ISSUE THREAD

**Issue by OstapL** [vladyslav2/gfwhitelabels#574]
@arthuryip723 @leonstiel 
Arthur please look at the menu page when scrolling does not work properly . I would be very grateful if you fix this bug
http://growthfountain-river-mark.s3-website-us-east-1.amazonaws.com/api/campaign/85

**Comment by arthuryip723** [comment]
I definitely am glad to help. Could you be a bit more specific? I am not sure what the issue looks like. Thanks.
@OstapL

**Comment by arthuryip723** [comment]
Oh I got it. I'll try to fix it. Thanks.
