### ISSUE TITLE
Titles

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#575]
@OstapL  @leonstiel 
1)On the all steps for create Campaign (General information, media, team members, specifics, perks) should be title "Create Campaign" instead of "Create Company"
![2016-09-13 18 15 11](https://cloud.githubusercontent.com/assets/20995691/18479622/58c08cd8-79de-11e6-8c52-b3587c577dbf.png)

2)Please delete bottom text under title Create campaign (Media step)
https://www.dropbox.com/home/Maria%20Wireframes/Create%20Company?preview=CREATE+COMPANY.psd

**Comment by OstapL** [comment]
@MariaKravchuk
Fixed #577 
http://localhost:7070/campaign/media/45
