### ISSUE TITLE
Добавить thumnails в API для /api/campaigns

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#578]
для list_image_data key:

list_image_data :
{
   folder: 37,
   id: 695,
   modified_at: "2016-09-12T20",
   name: "netflix_thumbnail.jpg",
   thumbnails: [{
     'size:"255x153"
     'url':"https://s3.amazonaws.com/growthfountain-development/filer_public_thumbnails/filer_public/06/73/06732c5e-59c0-4ed4-9b48-fed77603ab14/4766fbd0jw1e2m9bli0fsj.jpg__255x153_q85_crop_subsampling-2.jpg"1
   }],
   url: "https://s3.amazonaws.com/growthfountain-development/filer_public/05/8f/058fc485-db03-4424-b1b8-0f081921e0a8/netflix_thumbnail.jpg"
}

сейчас там всегда пусто я не пойму почему

**Comment by DenekUrich** [comment]
[Done](https://bitbucket.org/vladyslav_t/gfdjango/commits/7df1e7fe97d53b095e725dfce439c58196b53b98) Reimplemented with the new solution.

**Comment by DenekUrich** [comment]
[Done](https://bitbucket.org/vladyslav_t/gfdjango/commits/d0cf2438c6dcac73dfa9885a492c4a9ae0175177).
