### ISSUE TITLE
Specifics Page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#579]
@OstapL @leonstiel 

We a little change on Specifics  Page "Pre-Money Valuation and Equity Terms" section
please make it according to updated layout https://www.dropbox.com/home/Maria%20Wireframes/Create%20Campaign/PSD?preview=CREATE+CAMPAIGN%3ASpecifics.psd

Link to calculators: 1) If common equity the dropdown should include: Brand New Startup; Established Business
2) If Payback share the dropdown should include: Payback Share 

And this is document for top link (it should open in the new tab)
[growthfountain_security_description.pdf](https://github.com/vladyslav2/gfwhitelabels/files/470205/growthfountain_security_description.pdf)

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #587 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/specifics/45
