### ISSUE TITLE
campaign thumbnail content

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#580]
![image](https://cloud.githubusercontent.com/assets/21366183/18480345/5e26c21a-79a6-11e6-96ca-7e0609671b29.png)
campaign thumbnail content is matched with wrong field.

it should match with this field (about us) not why you should invest
![image](https://cloud.githubusercontent.com/assets/21366183/18480389/8504c0b2-79a6-11e6-9243-3657c2795c31.png)

**Comment by arthuryip723** [comment]
@vladyslav2 
Can we have the field of 'description' in campaign list?
As I don't see it in the result list.

**Comment by arthuryip723** [comment]
![screen shot 2016-09-13 at 7 03 36 pm](https://cloud.githubusercontent.com/assets/1624001/18494565/d95b9878-79e4-11e6-85fc-7cfd117d860a.png)

I didn't see the field 'description'.

**Comment by vladyslav2** [comment]
aga, ask Denis to help us

**Comment by DenekUrich** [comment]
[Done](https://bitbucket.org/vladyslav_t/gfdjango/commits/b40e715897133b525e28785d5beaf94a927e689e). Please check

**Comment by arthuryip723** [comment]
Fixed locally. Should be available after today's push.
