### ISSUE TITLE
Разобраться чему не подтягиваются labels с моделей

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#581]
OPTIONAL REQUEST:
http://jd-django.jwpbirm43d.us-east-1.elasticbeanstalk.com/api/campaign/specifics

will return:

actions.POST.minimum_raise.label = 'Minimum raise'

but in the model i have:
minimum_raise = models.PositiveIntegerField('Our Minimum Total Raise is', default=0)

WTF ?!

**Comment by DenekUrich** [comment]
[Done](https://bitbucket.org/vladyslav_t/gfdjango/commits/5812869dda800b4f118ba729b41fb93cb61db3a7)

Please check it.

**Comment by vladyslav2** [comment]
@DenekUrich Look
here is a problem
we do have all labels defined in the models for companies, campaigns, investments

we don't want to recreate labels in the serializers files.

minimum_raise = MoneyField(label='Our Minimum Total Raise is', min_value=0)
I know that this will work

but i want this code 
`
minimum_raise = models.PositiveIntegerField('Our Minimum Total Raise is', default=0)
`
actually start working.

its just redundant job to redeclare all labels in serializers

**Comment by DenekUrich** [comment]
[Done](https://bitbucket.org/vladyslav_t/gfdjango/commits/7df1e7fe97d53b095e725dfce439c58196b53b98). Reimplemented with the new solution.
