### ISSUE TITLE
maximum raise

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#584]
please input logic:
1. maximum raise has to be capped at $1 million
2. maximum raise must be >= minimum raise

![image](https://cloud.githubusercontent.com/assets/21366183/18481114/029149e0-79a9-11e6-82d1-73a6ff23532f.png)

**Comment by vladyslav2** [comment]
@DenekUrich there is something strange in the DRG
if i will set max_value=1000000 for maximum_raise field DGR will show error for any value no matter if it is less or more

Can you check that ? Maybe i did something wrong

**Comment by DenekUrich** [comment]
[Done](https://bitbucket.org/vladyslav_t/gfdjango/commits/9990f272d29988defbd83d79424f3b3eb67b87da). I used validators to define limits. Also i fixed to_internal_value it must return correct value.

**Comment by MariaKravchuk** [comment]
@DenekUrich @vladyslav2 here 2 punct does not fixed

**Comment by DenekUrich** [comment]
@MariaKravchuk please check
[Done](https://bitbucket.org/vladyslav_t/gfdjango/commits/ef378ee495cc075ba45004b1998f9691c11ec7cd)
