### ISSUE TITLE
campaign setup/save

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#589]
everytime i click save, the page refreshes and the information is deleted

![image](https://cloud.githubusercontent.com/assets/21366183/18485352/7a1e14a0-79ba-11e6-8c88-10b00ecdedd8.png)

**Comment by growthfountain** [comment]
i am not seeing this behavior on the dev site. http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/api/campaign/46
