### ISSUE TITLE
Top Menu/Footer

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#59]
@NewRoman @leonstiel 
1) We need to add to the section "Raise funds" following sections:
-Publish Company
-Publish Campaign
-Fill Form C
-Form C Review
![2016-08-15 23 07 35](https://cloud.githubusercontent.com/assets/20995691/17678102/746a58da-633e-11e6-957c-ad787ea7e9f9.png)

2)We need to add to the section "About Us" following sections:
-FAQ
-Blog
![2016-08-15 23 18 00](https://cloud.githubusercontent.com/assets/20995691/17678167/abc7b80e-633e-11e6-9c68-a0b0f9b31e10.png)

3)Fix window of notifications according to design.
![2016-08-15 23 21 45](https://cloud.githubusercontent.com/assets/20995691/17678283/13b4337a-633f-11e6-996c-f5731abe6149.png)

4) Delete from "for business" Campaign section.
![2016-08-15 23 31 09](https://cloud.githubusercontent.com/assets/20995691/17678618/842e5c06-6340-11e6-8f4f-71538eeb9fc6.png)

5) Please fix footer according to the updated design. I sent the PSD with updated footer to Roman.
![2016-08-15 23 22 45](https://cloud.githubusercontent.com/assets/20995691/17678338/5e873d52-633f-11e6-9cbe-850ec9ce601f.png)

**Comment by NewRoman** [comment]
All pointes were closed

https://github.com/vladyslav2/gfwhitelabels/pull/62
