### ISSUE TITLE
campaign setup/empty fields

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#590]
when user does not enter data, error message should read "this field may not be blank" (not " " not a valid choice)

![image](https://cloud.githubusercontent.com/assets/21366183/18485436/c4903e8c-79ba-11e6-86f3-e89e94dfdf89.png)

**Comment by morganm24** [comment]
why is this showing up for  corporate structure 

![image](https://cloud.githubusercontent.com/assets/21366183/18525455/8a3a2862-7a8a-11e6-8bdd-ea05a2b6d12e.png)

**Comment by growthfountain** [comment]
I see the text as updated.  I did not see the behavior on the corp structure, but it's possible that's because i updated an existing campaign. , The validation of the phone appears to have been turned off.  Closing this ticket and we can create a new ones if necessary with the specific issues.
