### ISSUE TITLE
Fix help-block of date of birth field

### ISSUE THREAD

**Issue by NewRoman** [vladyslav2/gfwhitelabels#600]
@OstapL 

возможно уже есть подобная задача, поэтому если это дубль то закрой ее пожалуйста.

http://screenshot.ru/3de1a6dc56c5848e53839a8f5ffbf6ff

**Comment by vladyslav2** [comment]
@OstapL ideas ?

**Comment by growthfountain** [comment]
Possibly a duplicate: https://github.com/vladyslav2/gfwhitelabels/issues/654

**Comment by OstapL** [comment]
@vladyslav2 @NewRoman
Fixed 
http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/api/campaign/81/invest
