### ISSUE TITLE
campaign setup/specifics/all fields should be blank

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#603]
if user does not enter data. nothing should appear. field should be BLANK

![image](https://cloud.githubusercontent.com/assets/21366183/18492281/73e3eb8c-79d8-11e6-817a-6f5aa85712ff.png)

**Comment by vladyslav2** [comment]
@morganm24 check if that work for you
it is still shows 0 but if you click 0 will be auto removed
