### ISSUE TITLE
campaign setup & preview length of campaign

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#604]
120 days left always shows up. not accurate. it should match with campaign length of campaign setup.
![image](https://cloud.githubusercontent.com/assets/21366183/18492374/01da7870-79d9-11e6-9540-b2bcece54fd7.png)

![image](https://cloud.githubusercontent.com/assets/21366183/18492407/1aa1a8d8-79d9-11e6-8048-39d3aeb3732a.png)

**Comment by growthfountain** [comment]
@vladyslav2 @arthuryip723

**Comment by growthfountain** [comment]
@vladyslav2 let's be sure to close this out today
