### ISSUE TITLE
Drop zone

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#625]
@arthuryip723 @OstapL @leonstiel 
1)Here we have updated layout with drop zone https://www.dropbox.com/home/Maria%20Wireframes/Create%20Campaign/PSD?preview=CREATE+CAMPAIGN%3AMedia.psd

Just make it in any the same section on the Media page, Team members page, Specifics page. @OstapL @arthuryip723 

2) on the Specifics page we should not have this image by default. It will appears only when user uploaded some file. @arthuryip723 
![2016-09-14 18 02 55](https://cloud.githubusercontent.com/assets/20995691/18517595/83904d64-7aa5-11e6-8b04-1c25b0fad6e0.png)

**Comment by morganm24** [comment]
can we make this the investor presentation look like thumbnail picture and header picture
![image](https://cloud.githubusercontent.com/assets/21366183/18525718/af36ced0-7a8b-11e6-8d65-cfbdf35e3026.png)
![image](https://cloud.githubusercontent.com/assets/21366183/18525743/ca65ba2c-7a8b-11e6-9578-d4ed1da1bf7a.png)

**Comment by OstapL** [comment]
@MariaKravchuk @morganm24 
Fixed #684 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/media/45

**Comment by morganm24** [comment]
thank you. can you lower the ppt image so its parallel to the upload button

**Comment by OstapL** [comment]
@morganm24 
Morgan Please check
