### ISSUE TITLE
All white label sites

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#629]
1. Please remove "PARTNERS" from ABOUT US on the top nav and on the bottom nav
2. Please change "TEAM" in ABOUT US on the top and the bottom nav to "GROWTHFOUNTAIN TEAM"

![image](https://cloud.githubusercontent.com/assets/21956276/18519343/9edd98a8-7a71-11e6-88b4-2a63b51a9671.png)

**Comment by NewRoman** [comment]
@MariaKravchuk  @kenstaut 

please tell me what I should to do with this link in footer?

![_001](https://cloud.githubusercontent.com/assets/8603994/18639452/a62ad61e-7e9c-11e6-942c-af0ca5a8d84e.png)

**Comment by kenstaut** [comment]
For white label sites, please remove that link.

Thanks,
Ken

Sent from my iPhone

On Sep 19, 2016, at 9:10 AM, Roman <notifications@github.com<mailto:notifications@github.com>> wrote:


@MariaKravchuk<https://github.com/MariaKravchuk> @kenstaut<https://github.com/kenstaut>

please tell me what I should to do with this link in footer?

[_001]<https://cloud.githubusercontent.com/assets/8603994/18639452/a62ad61e-7e9c-11e6-942c-af0ca5a8d84e.png>

-

**Comment by OstapL** [comment]
@kenstaut @MariaKravchuk 
Fixed #742 
http://growthfountain-river-mark.s3-website-us-east-1.amazonaws.com/pg/team
