### ISSUE TITLE
LIST OF CAMPAIGNS

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#63]
@OstapL @leonstiel 

1) It is necessary to solve the problem with filters. You need to change the look of the font in the name of the filter and look of the font of selected item from the drop down list. See PSD layout "LIST".
![2016-08-17 14 30 32](https://cloud.githubusercontent.com/assets/20995691/17734914/eae208c4-6487-11e6-9ed9-90af1b560113.png)

2)Please check the font size of the button's name and paddings according to layout. 
![2016-08-17 14 36 22](https://cloud.githubusercontent.com/assets/20995691/17734986/67f171a6-6488-11e6-96ff-b5f7daf3d5cd.png)

3)Correct the content of the window on the company image according to design.
![2016-08-17 14 47 52](https://cloud.githubusercontent.com/assets/20995691/17735289/fa9a10b6-6489-11e6-8702-1e6670e15c09.png)

4)Here also correct all derogations according to PDS layout.
![2016-08-17 14 51 18](https://cloud.githubusercontent.com/assets/20995691/17735342/43de642a-648a-11e6-86d4-2c3957b3dd7e.png)

**Comment by OstapL** [comment]
@MariaKravchuk @leonstiel 
made changes according to the model
