### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#631]
We only need one checkbox, not two.

Please make it read: 
![image](https://cloud.githubusercontent.com/assets/21956276/18519952/cd216ecc-7a73-11e6-9561-ed86cdd6e83b.png)

I will provide the document for Electronic Signature and Electronic Delivery of Documentation shortly - and it should appear under the LEGAL section in the footer

![image](https://cloud.githubusercontent.com/assets/21956276/18519886/86eac0ac-7a73-11e6-92d1-1ebed7a356f1.png)

**Comment by growthfountain** [comment]
@kenstaut alex had wanted 2 check boxes, are you sure 1 is ok?

**Comment by kenstaut** [comment]
Yes I’m sure (sorry, I do remember how we had to change it….that was a mistake)

**Comment by vladyslav2** [comment]
@DenekUrich tell me when you will update backend - i'll make a changes on front end

**Comment by DenekUrich** [comment]
[Done](https://bitbucket.org/vladyslav_t/gfdjango/commits/c08f8e054a2cc25731ac53a159ee50e244556da6)

left only **checkbox1** field
