### ISSUE TITLE
API: campaign list requests

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#634]
/api/campaign:
return only is_approved=True campaigns

/api/campaign/id - 
return only is_approved=True campaigns or if user that open campaign is an owner of that campaign or if user is admin or staff

remove ability to delete campaigns with /api/campaign/id DELETE request

**Comment by DenekUrich** [comment]
[Done](https://bitbucket.org/vladyslav_t/gfdjango/commits/c35dcfae27e3d1a0aa1b3a6ac985e5b5bf835f4c)
