### ISSUE TITLE
Design of calculators

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#651]
@NewRoman @leonstiel 
2)This section should has name "How Much Should I Raise?"
![2016-09-15 18 17 34](https://cloud.githubusercontent.com/assets/20995691/18555505/c4313358-7b70-11e6-8643-a7ee14a6b639.png)

3) Can you make like in design this caption "GrowthFountain Recommended Total Amount of Capital Raise" (Capital Raise calculator)
![2016-09-15 13 45 02](https://cloud.githubusercontent.com/assets/20995691/18547174/c64cb1c4-7b4a-11e6-9285-6963916392ee.png)

**Comment by NewRoman** [comment]
@MariaKravchuk @vladyslav2 @rkuleshov-corevalue 

add bootstrap slider styles 
https://github.com/NewRoman/gfwhitelabels/commit/af5d12d82cfc88fdc857cc86ae004af3303e96f9
