### ISSUE TITLE
Deleting an image in the gallery prompts an upload

### ISSUE THREAD

**Issue by growthfountain** [vladyslav2/gfwhitelabels#656]
When you delete an image, the upload an image opens.  It's possible that you simply want to delete an image, without adding.

http://growthfountain-dev.s3-website-us-east-1.amazonaws.com/campaign/media/46

**Comment by vladyslav2** [comment]
@arthuryip723 
take a look on this please https://github.com/enyo/dropzone/blob/master/src/dropzone.coffee#L588

lets discuss this

**Comment by arthuryip723** [comment]
@growthfountain 
Please check and close.

**Comment by growthfountain** [comment]
nicely done
