### ISSUE TITLE
Remove image from the background of press

### ISSUE THREAD

**Issue by growthfountain** [vladyslav2/gfwhitelabels#659]
I know @MariaKravchuk is working on a design, but we cannot give the site to more users to test on Friday with the current background image from a different campaign.  Please make it a flat color for now and we will fix more completely next week.

**Comment by MariaKravchuk** [comment]
@growthfountain today I think we will implement new design for this section

I wrote about it in this issue
https://github.com/vladyslav2/gfwhitelabels/issues/371

**Comment by growthfountain** [comment]
@MariaKravchuk, it look like we need to control the vertical height of the new press area (for longer links), but I'll close this one and we can open a new one if necessary.  It looks good.
