### ISSUE TITLE
Update Invest Page

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#674]
Change Verification Section here:
![image](https://cloud.githubusercontent.com/assets/21956276/18558368/cfe85cba-7b40-11e6-9400-5f04bce64b5c.png)

To this:
[invest.pptx](https://github.com/vladyslav2/gfwhitelabels/files/475150/invest.pptx)

**Comment by MariaKravchuk** [comment]
@kenstaut I updated appropriate layout and coders will change it

**Comment by MariaKravchuk** [comment]
@OstapL here updated layout for this task

https://www.dropbox.com/home/Maria%20Wireframes/Invest/PSD?preview=INVEST.psd

**Comment by OstapL** [comment]
@MariaKravchuk @kenstaut
Fixed #736 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign/85/invest
