### ISSUE TITLE
Payback share calculator

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#713]
Почему 0% появляется только при onhover ?
![screen shot 2016-09-16 at 3 18 39 pm](https://cloud.githubusercontent.com/assets/704096/18599827/687e579e-7c28-11e6-82b9-3d57efa8ab29.png)

**Comment by rkuleshov-corevalue** [comment]
поправил https://github.com/vladyslav2/gfwhitelabels/pull/722
