### ISSUE TITLE
campaign preview/share campaign to social media

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#714]
facebook share is not working

![image](https://cloud.githubusercontent.com/assets/21366183/18599836/6fde1150-7c28-11e6-82db-531751ee8ef4.png)

this message appears when you click the facebook logo
![image](https://cloud.githubusercontent.com/assets/21366183/18599846/7f3d1376-7c28-11e6-9af4-1e9404f4a29e.png)

**Comment by vladyslav2** [comment]
@morganm24 i think Desin explain to you what to do with that error ?
