### ISSUE TITLE
Payback share calculator

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#716]
1. График должен всегда показывать шкалу в 10 лет
те с текущего года + 10 лет - мы всегда это показываем, не важно есть данные для этого или нет.

2. Шкала по высоте, multiple return,  показываем проценты, 100%, 200%

3. Шкала по "ширине" - года, показываем YEAR 2016, 2017, ... 2026
![screen shot 2016-09-16 at 3 20 53 pm](https://cloud.githubusercontent.com/assets/704096/18599881/a84fcdf8-7c28-11e6-9055-5c5ddd7de8eb.png)

**Comment by rkuleshov-corevalue** [comment]
Готово, проверяйте https://github.com/vladyslav2/gfwhitelabels/pull/722
