### ISSUE TITLE
Calculator: I HAVE AN ESTABLISHED BUSINESS

### ISSUE THREAD

**Issue by vladyslav2** [vladyslav2/gfwhitelabels#717]
Нужен срочно !

**Comment by NewRoman** [comment]
@vladyslav2 @MariaKravchuk 

Fixed some styles, texts and blocks and merge on romang server
available to check 
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/calculator/establishedBusiness/finish

**Comment by rkuleshov-corevalue** [comment]
Done from my side

**Comment by NewRoman** [comment]
@MariaKravchuk @rkuleshov-corevalue @vladyslav2 

добавлена верстка промежуточной страницы для establishedBusinessCalculator

добавил в папку establishedBusinessCalculator/templates/selectCalculator.pug

ее еще необходимо подключить.

https://github.com/NewRoman/gfwhitelabels/commit/8ffecc31be57228fb29da967016d422a6505ee78
