### ISSUE TITLE
campaign setup/social channel url

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#723]
i thought this was fixed?

![screen shot 2016-09-18 at 5 40 41 pm](https://cloud.githubusercontent.com/assets/21366183/18619303/fba59092-7dc6-11e6-9c91-87665dc37a6c.png)

**Comment by arthuryip723** [comment]
Oh, i'll apply this to all the url inputs. I haven't applied the fix to everywhere. I'll get it done. And in case I may leave out any other similar fields, do you know anywhere else with the same url fields? Thanks.
@morganm24

**Comment by arthuryip723** [comment]
fixed.
