### ISSUE TITLE
Update Specifics page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#732]
@OstapL @leonstiel 
After Pre-money  valuation section please add some text.

![2016-09-19 18 08 07](https://cloud.githubusercontent.com/assets/20995691/18637235/694a3b48-7e94-11e6-8708-5e4786b7604e.png)

Here updated layout
https://www.dropbox.com/home/Maria%20Wireframes/Create%20Campaign/PSD?preview=CREATE+CAMPAIGN%3ASpecifics.psd

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #738
