### ISSUE TITLE
Mobile version (log in page, main page)

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#755]
@OstapL @NewRoman @leonstiel 

1) Remove space on the right side
![image](https://cloud.githubusercontent.com/assets/20995691/19530227/ab2bb168-963b-11e6-9bd8-7330ce141784.png)

4)In such sections is absent the image
![image](https://cloud.githubusercontent.com/assets/20995691/18682554/6d65a5d2-7f75-11e6-8a01-d6265fda3d3a.png)

5)What with the main image here?
![image](https://cloud.githubusercontent.com/assets/20995691/18689200/a2905dfe-7f90-11e6-82ac-60f40cafac7a.png)

6) Add some space between partner's logos
![image](https://cloud.githubusercontent.com/assets/20995691/18785563/8f6932b0-81a1-11e6-94b1-9260ca824f54.png)

Please fix it

**Comment by NewRoman** [comment]
@MariaKravchuk 
point 2 already fixed and it can be checked here
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/news

**Comment by OstapL** [comment]
@MariaKravchuk  
Fixed 1, 3 
#778

**Comment by NewRoman** [comment]
@MariaKravchuk 
all points ready
