### ISSUE TITLE
campaign setup (save all actions)

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#763]
step 1.Please make sure that when a user clicks a section on the side menu their content is saved.
step 2. can you also make sure that when user clicks "preview" all info is saved.

![image](https://cloud.githubusercontent.com/assets/21366183/18690828/4e413304-7f5e-11e6-9ff5-09c12d715ed6.png)
![image](https://cloud.githubusercontent.com/assets/21366183/18690843/5b361a98-7f5e-11e6-81db-ffa76a6df0ca.png)

**Comment by vladyslav2** [comment]
Preview done
please check

**Comment by vladyslav2** [comment]
@morganm24 can you check preview button one more time please ?
