### ISSUE TITLE
campaign setup/team member buttons

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#773]
both "add team member" and "add advisor" are pulling up the SAME page
![image](https://cloud.githubusercontent.com/assets/21366183/18718721/7ee2ecac-7ff2-11e6-8cac-90470618e092.png)

this is what shows when i click add team member
![image](https://cloud.githubusercontent.com/assets/21366183/18718755/91dda0c2-7ff2-11e6-9f4b-7c46b56864e3.png)

this is what shows when i click add advisor"
![image](https://cloud.githubusercontent.com/assets/21366183/18718785/b3398132-7ff2-11e6-9e11-7867287650d7.png)

**Comment by arthuryip723** [comment]
Let me work on this.

**Comment by arthuryip723** [comment]
@morganm24 
please check.
