### ISSUE TITLE
Fix White Label Site

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#785]
on my laptop (or on slightly smaller screen) this appears:

![image](https://cloud.githubusercontent.com/assets/21956276/18730011/212126bc-8022-11e6-88b0-ecea1a688f3c.png)

**Comment by OstapL** [comment]
@kenstaut @MariaKravchuk  
Fixed this bug #788 
http://growthfountain-river-mark.s3-website-us-east-1.amazonaws.com/
