### ISSUE TITLE
Side menu "RAISE FUNDS", "EDUCATION LINKS"

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#80]
@OstapL @leonstiel 
1) Caption "10% Done" should not be bold. 
![2016-08-18 23 08 03](https://cloud.githubusercontent.com/assets/20995691/17788978/d25fbf00-6598-11e6-8309-483213b9d4e3.png)

2)These captions must be a size 12 with appropriate letter-spacing
![2016-08-18 23 10 12](https://cloud.githubusercontent.com/assets/20995691/17789056/27c6bf7a-6599-11e6-9137-08e150a9a16e.png)

3)This icon should be gray and have a size of 18 pixels
![2016-08-18 23 22 17](https://cloud.githubusercontent.com/assets/20995691/17789480/0a4086b4-659b-11e6-9850-1f3cdc0d6579.png)

4)interval between the links should be 20 pixels
![2016-08-18 23 26 33](https://cloud.githubusercontent.com/assets/20995691/17789541/55d10a2c-659b-11e6-8532-d1bfc49ac254.png)

5)Here, I should be able to click on the icon to download the file.
![2016-08-18 23 27 53](https://cloud.githubusercontent.com/assets/20995691/17789586/89c85740-659b-11e6-8c46-fe5f725bbecc.png)

**Comment by OstapL** [comment]
@MariaKravchuk @leonstiel  
made changes
