### ISSUE TITLE
Mobile version (About Us pages)

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#808]
@NewRoman  @leonstiel 
1)On Team page we have such problem with bottom section. We must make content of this section appropriate concerning size and also here does not appear image.
![image](https://cloud.githubusercontent.com/assets/20995691/18785672/36f266d2-81a2-11e6-9730-1d0cfaf2f04b.png)

2)On the Partners page place logos on the center.
![image](https://cloud.githubusercontent.com/assets/20995691/18785724/9129b312-81a2-11e6-8810-4a20f7487234.png)

3)On the In the News page make the same spaces under the logos
![image](https://cloud.githubusercontent.com/assets/20995691/18785756/bd31c1f2-81a2-11e6-929f-861fe644f7eb.png)

![image](https://cloud.githubusercontent.com/assets/20995691/18785761/c9571b26-81a2-11e6-94c3-cba446e05121.png)

4) on the Blog page add some space above the "read more" buttons
![image](https://cloud.githubusercontent.com/assets/20995691/18785801/1301efe4-81a3-11e6-90a1-03bb341c68db.png)

**Comment by NewRoman** [comment]
@MariaKravchuk 
1 fixed
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/team

4 fixed
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/blogs

please check it

**Comment by NewRoman** [comment]
@MariaKravchuk 
point 2 ready to check
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/partners

point 3 ready to check
http://growthfountain-romang.s3-website-us-east-1.amazonaws.com/pg/news
