### ISSUE TITLE
Team member/Media/Create company pages

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#81]
@OstapL @leonstiel 
1) This icon should be gray. Also, I should be able to click on it to download the file.
![2016-08-18 23 55 05](https://cloud.githubusercontent.com/assets/20995691/17790484/55500626-659f-11e6-9b4c-aac0f850fe06.png)

2)The distance between the image and the buttons should be 50 pixels (Team member page)
![2016-08-18 23 57 38](https://cloud.githubusercontent.com/assets/20995691/17790550/a5b395b0-659f-11e6-8bb6-1cce37c91d20.png)

3)The distance between the header and the edge of the image should be 50 pixels
![2016-08-18 23 59 36](https://cloud.githubusercontent.com/assets/20995691/17790618/f46e0596-659f-11e6-8eec-5c379ce8f9df.png)

4)The distance between these two blocs should be 25 pixels
![2016-08-19 00 01 00](https://cloud.githubusercontent.com/assets/20995691/17790654/272c3958-65a0-11e6-87fd-4bf00c16933c.png)

5)The distance between the buttons and Footer should be 85 pixels (Media Page)
![2016-08-19 00 03 04](https://cloud.githubusercontent.com/assets/20995691/17790724/761cecb0-65a0-11e6-9f0c-7c145d97731e.png)

6)Please add here icon such as in the layout
![2016-08-19 00 05 56](https://cloud.githubusercontent.com/assets/20995691/17790816/e11e6a66-65a0-11e6-9a6b-97a3dbad1df3.png)

7) under these pictures should be possible to flip them horizontally, because the user can download a maximum of 8 images.
![2016-08-19 00 07 27](https://cloud.githubusercontent.com/assets/20995691/17790905/4625cdf0-65a1-11e6-8d4a-02f41820307c.png)

8) I think we have to find some other form of this input
![2016-08-19 00 10 40](https://cloud.githubusercontent.com/assets/20995691/17790972/8c664fce-65a1-11e6-8681-dfb38002e9e6.png)

9) This icon should be gray and be separate from the word (Create Company page)
![2016-08-19 00 13 10](https://cloud.githubusercontent.com/assets/20995691/17791030/d7447a02-65a1-11e6-8273-3a2f47d83506.png)

**Comment by OstapL** [comment]
@MariaKravchuk @leonstiel 
made changes, 
but 
5)The distance between the buttons and Footer should be 85 pixels (Media Page)  it corrects Roman , as the rules footer
