### ISSUE TITLE
Calculators

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#818]
@rkuleshov-corevalue @leonstiel 
1)PAYBACK SHARE CALCULATOR

- If the user clicked in a input field but has not entered any data, in the field automatically put zero. This should not happen.

![2016-09-23 20 42 35](https://cloud.githubusercontent.com/assets/20995691/18795782/dcf32acc-81ce-11e6-9ec3-f9e61932ea1c.png)

- When you enter some data in the fields, and then clicks "continue", the first two fields become empty, and the system shows no error.
![2016-09-23 20 52 44](https://cloud.githubusercontent.com/assets/20995691/18795942/b46a657e-81cf-11e6-81c6-fd8fd94709e9.png)

- When you hover on one of this points here should appear some tips
![2016-09-23 21 13 42](https://cloud.githubusercontent.com/assets/20995691/18796645/df51b3c0-81d2-11e6-93b9-a1dc4b44f806.png)

2)CAPITAL RAISE CALCULATOR

 - All fields must be empty by default.
![2016-09-23 20 53 57](https://cloud.githubusercontent.com/assets/20995691/18795992/eab9f02c-81cf-11e6-8bd2-bbc098691f60.png)

- here as well automatically tabulated zero.
![2016-09-23 20 55 58](https://cloud.githubusercontent.com/assets/20995691/18796048/290ae764-81d0-11e6-9627-51e11830b261.png)

- here do not work tips. Please make them like in the layouts
![2016-09-23 20 56 25](https://cloud.githubusercontent.com/assets/20995691/18796079/51907dac-81d0-11e6-8b26-8363d7c8ba74.png)

- Add to slider percent icon
![2016-09-23 20 57 29](https://cloud.githubusercontent.com/assets/20995691/18796116/7bca65b0-81d0-11e6-83df-95419962d1da.png)

3) STARTUP BUSINESS VALUATION CALCULATOR

- all fields should be empty by default
![2016-09-23 21 00 13](https://cloud.githubusercontent.com/assets/20995691/18796195/d15b7bf4-81d0-11e6-96f1-1a3d85676d22.png)

4) ESTABLISHED BUSINESS VALUATION CALCULATOR

- Here the same things: all fields should be empty by default; do not work tips; as well automatically tabulated zero.

- In some fields, which permit calculation of the formula, it should be possible to set zero.

- Please make finish step like in the updated layout https://www.dropbox.com/home/Maria%20Wireframes/CALCULATORS/Established%20Calculator/PSD?preview=Established+Calculator%3A+Finish.psd

Also this graph should be dynamic.

**Comment by rkuleshov-corevalue** [comment]
I've completed all items except
- "When you hover on one of this points here should appear some tips"
- "here do not work tips. Please make them like in the layouts"
I will be continue working with them tomorrow

**Comment by rkuleshov-corevalue** [comment]
All items from the list are done. If there is any updates - just let me know
