### ISSUE TITLE
campaign setup/company/social media link

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#826]
user enters text into linkedin, twitter,instagram, facebook fields. then deletes text. 

ERROR: "http://" appears and cannot be erased.

![image](https://cloud.githubusercontent.com/assets/21366183/18799120/006536ba-81a4-11e6-8724-ae0f25876efb.png)

**Comment by arthuryip723** [comment]
I am on this.

**Comment by arthuryip723** [comment]
@morganm24 
please check
