### ISSUE TITLE
Add Member Page Should Allow Cancel, Shouldn't It?

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#834]
As in title
@morganm24 @vladyslav2 @growthfountain 
![screen shot 2016-09-23 at 4 21 11 pm](https://cloud.githubusercontent.com/assets/1624001/18800414/cffc7f54-81aa-11e6-9a66-f204ad69ad20.png)

**Comment by morganm24** [comment]
![image](https://cloud.githubusercontent.com/assets/21366183/18800598/dfd617a4-81ab-11e6-8f8a-0dccfa1f4af7.png)

**Comment by MariaKravchuk** [comment]
@morganm24 @arthuryip723 thank you guys, it was well noticed

@OstapL Please  add the button "cancel". Here the updated layout
https://www.dropbox.com/home/Maria%20Wireframes/Create%20Campaign/PSD?preview=CREATE+CAMPAIGN%3ATeam+members.psd

**Comment by OstapL** [comment]
@MariaKravchuk @morganm24 
Fixed #862 
please check
see here
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/team-members/114/add/member/new
