### ISSUE TITLE
Update User Profile 

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#836]
@arthuryip723 @OstapL @vladyslav2 @leonstiel 
I know that you have added a link to change password. So I updated the design of this page and added drop zone here.

See updated layout here
https://www.dropbox.com/home/Maria%20Wireframes/User%20profile/PSD?preview=PROFILE.psd

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/account/profile
