### ISSUE TITLE
Article's block size

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#837]
@OstapL @leonstiel 
Let's make the same sizes for all article's blocks like we have made for perks
![2016-09-26 14 06 53](https://cloud.githubusercontent.com/assets/20995691/18832238/e54b418e-83f2-11e6-81f9-0ede6787976e.png)

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed
Maria please check 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign/96
