### ISSUE TITLE
campaign setup/perks

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#848]
please change text to "Describe the Perk" and delete text inside box.

![image](https://cloud.githubusercontent.com/assets/21366183/18842508/38167a42-83e3-11e6-8208-a67aec533eac.png)

**Comment by MariaKravchuk** [comment]
@morganm24 @vladyslav2 i think that on the input should be text (placeholder) "Description"

**Comment by vladyslav2** [comment]
fixed
please check
