### ISSUE TITLE
New fields to Team members/Form C

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#866]
@OstapL 
please add two new fields to the Team members (buttons)/Form C page

See updates layout
https://www.dropbox.com/home/Maria%20Wireframes/Form%20C/PSD?preview=02+Team+members+buttons.psd

**Comment by OstapL** [comment]
@MariaKravchuk 
FIxed #889 
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/formc/team-members/114
