### ISSUE TITLE
Some changes to Form C 

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#890]
@OstapL @leonstiel 
1)Outstanding Security page
Added new field
![2016-09-28 23 07 09](https://cloud.githubusercontent.com/assets/20995691/18930330/4f9ddd60-85d0-11e6-81f6-956790177c74.png)
See here
https://www.dropbox.com/home/Maria%20Wireframes/Form%20C/PSD?preview=07+Outstanding+security.psd

2)USE OF PROCEEDS page
Delete an option to describe or upload, only require upload
![2016-09-28 23 10 35](https://cloud.githubusercontent.com/assets/20995691/18930455/ca3e7ce6-85d0-11e6-9864-0e4bf1645dad.png)
See here
https://www.dropbox.com/home/Maria%20Wireframes/Form%20C/PSD?preview=04+USE+OF+PROCEEDS.psd

**Comment by OstapL** [comment]
@MariaKravchuk 
1 Fixed #904 
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/formc/outstanding-security/114
2 Fixed #907 
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/formc/use-of-proceeds/114

**Comment by MariaKravchuk** [comment]
@OstapL please remake 2 point
