### ISSUE TITLE
campaign setup/form c/risk factors/market and customer risk

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#911]
please fix text: You are free "to" use .........(ADD "to")

![image](https://cloud.githubusercontent.com/assets/21366183/18968054/7e2a43dc-8655-11e6-9ae6-ccfb7b43ada3.png)

**Comment by OstapL** [comment]
Fixed 
please check 
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/formc/17/risk-factors-market
