### ISSUE TITLE
New design for message

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#917]
@OstapL 
Please make design for messages (on Team members/buttons, Specifics, Perks pages) like in the layouts
![2016-09-30 13 58 08](https://cloud.githubusercontent.com/assets/20995691/18989694/ff52e674-8715-11e6-93be-88f4029cf04e.png)

updated layout here:
https://www.dropbox.com/home/Maria%20Wireframes/Create%20Campaign/PSD?preview=TEAM+MEMBERS%3AButtons.psd

https://www.dropbox.com/home/Maria%20Wireframes/Create%20Campaign/PSD?preview=CREATE+CAMPAIGN%3ASpecifics.psd

https://www.dropbox.com/home/Maria%20Wireframes/Create%20Campaign/PSD?preview=CREATE+CAMPAIGN%3APerks.psd

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #919 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/team-members/114
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/specifics/114
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/perks/114
