### ISSUE TITLE
Articles and Press

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#918]
@OstapL @arthuryip723 
We should show only three articles on the Campaign page. More articles user will be able to see when he`ll click "See All Articles and Press"

See updated layout:
https://www.dropbox.com/home/Maria%20Wireframes/Company%20page?preview=COMPANY+PAGE.psd

**Comment by OstapL** [comment]
@arthuryip723 I added links "See All Articles and Press"

**Comment by arthuryip723** [comment]
@MariaKravchuk @OstapL 
fixed.
