### ISSUE TITLE
Team members/ Form C (markup)

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#924]
@OstapL 

1)Here should be always the massage like in layout
![2016-09-30 20 01 49](https://cloud.githubusercontent.com/assets/20995691/19000844/57c595fe-874d-11e6-86ff-e17368962e68.png)

updated layout:
https://www.dropbox.com/home/Maria%20Wireframes/Form%20C/PSD?preview=02+Team+members+buttons.psd

2)Please align buttons on the right side
![2016-09-30 20 08 21](https://cloud.githubusercontent.com/assets/20995691/19000852/61a93bfc-874d-11e6-85e4-d202bb3d0c62.png)

3)TEAM MEMBERS (DIRECTOR)
- Make space under the heading like in layout
- align this delete icon on the right side
![2016-09-30 20 10 00](https://cloud.githubusercontent.com/assets/20995691/19000868/7acd4d62-874d-11e6-98d9-6d10124edd54.png)

-here too small space between side menu and inputs. make like in layout
![2016-09-30 23 22 37](https://cloud.githubusercontent.com/assets/20995691/19005771/eef80288-8764-11e6-938e-a9d523acdcdd.png)

4)TEAM MEMBERS (OFFICER)
- make here typography like in layout

![2016-09-30 20 13 06](https://cloud.githubusercontent.com/assets/20995691/19000872/823bad64-874d-11e6-94ff-8eec88beb450.png)

**Comment by OstapL** [comment]
1 Fixed #945 
2 Fixed #945

**Comment by OstapL** [comment]
@MariaKravchuk 
3 Fixed #947 
4 Fixed #946 
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/formc/114/team-members/add/officer/new
