### ISSUE TITLE
Deleting of some sections on the Form C pages

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#925]
@arthuryip723 

I can not delete section which I Added another one (for example on Related parties page)
![2016-09-30 20 38 48](https://cloud.githubusercontent.com/assets/20995691/19000976/f7b085e2-874d-11e6-99d7-d1d8aa67e14f.png)

And this problem is on the all pages of form C

**Comment by arthuryip723** [comment]
Hello Maria, I'll work with Vlad to address this. Will let you know when we have a decision. Thanks.

**Comment by MariaKravchuk** [comment]
ok
