### ISSUE TITLE
USE OF PROCEEDS

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#926]
@OstapL 
this is the inputs. User should be able to type here some information.
![2016-09-30 21 04 28](https://cloud.githubusercontent.com/assets/20995691/19001798/b3d4aab6-8751-11e6-8bd4-6ee209d38c80.png)

Also I updated this layout. Please make all change from it.

See here
https://www.dropbox.com/home/Maria%20Wireframes/Form%20C/PSD?preview=04+USE+OF+PROCEEDS.psd

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed all in this page with new design
#948 
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/formc/114/use-of-proceeds
