### ISSUE TITLE
Risks/Form C

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#927]
@OstapL 
please make our new design for message here
![2016-09-30 21 17 26](https://cloud.githubusercontent.com/assets/20995691/19002167/69edbb5c-8753-11e6-99af-05245fccfdab.png)

On all Risks pages

See updated layout
https://www.dropbox.com/home/Maria%20Wireframes/Form%20C/PSD?preview=05.02+Risk+Factors%3AMarket+and+Customer.psd

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #952 
http://growthfountain-formc.s3-website-us-east-1.amazonaws.com/formc/114/risk-factors-market
