### ISSUE TITLE
OUTSTANDING SECURITY

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#931]
@OstapL @arthuryip723 
1) Please make the table like in the updated layout
![2016-09-30 23 06 31](https://cloud.githubusercontent.com/assets/20995691/19005394/126ebdb2-8763-11e6-81bd-ebc50dc494e6.png)

2) In this way should look pop up
![2016-09-30 23 09 09](https://cloud.githubusercontent.com/assets/20995691/19005427/46055816-8763-11e6-8a3e-f74f7d7f799d.png)

this is the list for dropdown:
![2016-09-30 23 12 35](https://cloud.githubusercontent.com/assets/20995691/19005444/67d88328-8763-11e6-9f7e-cbf60cf3897d.png)

And when user selects "other" a text box has to become available for them to type in what it is

See updated layout here:
https://www.dropbox.com/home/Maria%20Wireframes/Form%20C/PSD?preview=07+Outstanding+security.psd

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed
