### ISSUE TITLE
BACKGROUND CHECK

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#932]
@OstapL 
-please check in this area all spaces and make them like in layout
![2016-09-30 23 19 30](https://cloud.githubusercontent.com/assets/20995691/19005686/8c44b9c4-8764-11e6-92b2-14bb433dc413.png)

-This text should be 18 font size
![2016-09-30 23 21 06](https://cloud.githubusercontent.com/assets/20995691/19005711/aad7ccfa-8764-11e6-882f-27509531bd01.png)

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #965
