### ISSUE TITLE
Create Company/Campaign (some updates)

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#933]
@OstapL 
1)Please add on the all pages of create company/campaign process new buttons
![2016-10-01 15 47 56](https://cloud.githubusercontent.com/assets/20995691/19014180/7f047472-87ee-11e6-9e0f-05e8b02ca9d8.png)
![2016-10-01 15 48 00](https://cloud.githubusercontent.com/assets/20995691/19014181/7f065d14-87ee-11e6-8a3a-834945c070b6.png)

2) You should make new Thank you page 

![2016-10-01 15 49 47](https://cloud.githubusercontent.com/assets/20995691/19014185/b8688ece-87ee-11e6-9074-00315b476e85.png)

All updated layouts for this issues here:
https://www.dropbox.com/home/Maria%20Wireframes/Create%20Company%20and%20Campaign/PSD

**Comment by OstapL** [comment]
Fixed all 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/company/create
