### ISSUE TITLE
Features to Create company/campaign process

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#934]
@vladyslav2 @OstapL @leonstiel 
1)Vlad let's make required fields with such gray star icon:
![2016-10-01 15 54 48](https://cloud.githubusercontent.com/assets/20995691/19014210/6b27ce12-87ef-11e6-9822-f7ee2bc78153.png)

and optional field should be just in black font color:
![2016-10-01 15 56 07](https://cloud.githubusercontent.com/assets/20995691/19014216/9a02ec58-87ef-11e6-9c31-7e42d32a0694.png)

2) If user clicks submit but does not fill all necessary forms we should have such pop up
![2016-10-01 15 57 34](https://cloud.githubusercontent.com/assets/20995691/19014221/cd8fd8c4-87ef-11e6-99c7-5c3317f68124.png)

Here you can find popup
https://www.dropbox.com/home/Maria%20Wireframes/Create%20Company%20and%20Campaign/PSD?preview=01.02+CREATE+CAMPAIGN.psd

**Comment by OstapL** [comment]
2 Fixed #936 
Maria look here 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/campaign/general_information/114
click on button SUBMIT CAMPAIGN

**Comment by MariaKravchuk** [comment]
@OstapL Please make all spaces and fonts in pop up like in layout

Also add Pop up on Create Company page

**Comment by OstapL** [comment]
@MariaKravchuk  I fixed this - change spaces and added font dosis

added pop up in company page
#962
