### ISSUE TITLE
Rivermark

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#940]
@OstapL @leonstiel 
1)Edit here to "GrowthFountain Team"
![2016-10-03 12 33 34](https://cloud.githubusercontent.com/assets/20995691/19033155/b3321984-8965-11e6-88df-a2df334b56f4.png)

2)Make the same size of campaigns box
![2016-10-03 12 35 40](https://cloud.githubusercontent.com/assets/20995691/19033215/fc073bd0-8965-11e6-8dba-92fddb0f6ea4.png)

3)Place this title on the center
![2016-10-03 12 39 57](https://cloud.githubusercontent.com/assets/20995691/19033339/967df23a-8966-11e6-81e3-0a49251c23a6.png)

4)Make the locality of the text in this box like in the layout
![2016-10-03 12 42 04](https://cloud.githubusercontent.com/assets/20995691/19033477/3c48ed82-8967-11e6-812b-1aa9af4511fc.png)

5)align text on the width.
![2016-10-03 12 46 38](https://cloud.githubusercontent.com/assets/20995691/19033549/9c346154-8967-11e6-9bb7-bd8a0964852d.png)

6)Also please write here "GrowthFountain Team"
![2016-10-03 12 48 12](https://cloud.githubusercontent.com/assets/20995691/19033576/b889cc0e-8967-11e6-9d5a-b413b6266cb4.png)

7)Change here font to Open sans
![2016-10-03 12 49 01](https://cloud.githubusercontent.com/assets/20995691/19033592/d2a97166-8967-11e6-9653-47d96027ff92.png)

8)Make on Education page scrolling side menu and bold headings (with letter spacing 100)
![2016-10-03 12 51 28](https://cloud.githubusercontent.com/assets/20995691/19033660/434c54ce-8968-11e6-9308-ae5af7985aea.png)

9)Don`t make this step boxes on the all calculators like a buttons! Leave here design which we have on GF site. And add for them appropriate color - # 2f94c9
![2016-10-03 12 53 58](https://cloud.githubusercontent.com/assets/20995691/19033815/179c27c2-8969-11e6-9b26-03b49c9306e1.png)

10) Please fix functionality of side menu on TERMS OF SERVICE and PRIVACY POLICY pages
![2016-10-03 13 34 20](https://cloud.githubusercontent.com/assets/20995691/19034791/2c8b5d2e-896e-11e6-8af7-a9f5483422e4.png)

![2016-10-03 13 34 59](https://cloud.githubusercontent.com/assets/20995691/19034798/36bd3808-896e-11e6-989a-5d863b159302.png)

**Comment by NewRoman** [comment]
@MariaKravchuk 
points 1-3,5-7, 9 ready
http://growthfountain-river-mark.s3-website-us-east-1.amazonaws.com/

**Comment by NewRoman** [comment]
@vladyslav2 
I need your help. I can't fix bug described in 10 item. 
I compare code in js file pg/route.js of river site with other and there are indentical.

This bug appears when visit terms of use and privacy policy pages from footer link

**Comment by NewRoman** [comment]
@MariaKravchuk 
item 4 ready
http://growthfountain-river-mark.s3-website-us-east-1.amazonaws.com/api/campaign/124
