### ISSUE TITLE
DCU

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#941]
@NewRoman @leonstiel 
1) Make the header background like in layout
![2016-10-03 13 06 48](https://cloud.githubusercontent.com/assets/20995691/19034076/5389e41c-896a-11e6-975b-f855757d8f34.png)

2)Change to "GrowthFountain Team"
![2016-10-03 13 08 27](https://cloud.githubusercontent.com/assets/20995691/19034132/986a8bc2-896a-11e6-9417-8b45183c9ae2.png)
![2016-10-03 13 08 34](https://cloud.githubusercontent.com/assets/20995691/19034134/986cf308-896a-11e6-9980-9d73bbaf156a.png)
![2016-10-03 13 08 44](https://cloud.githubusercontent.com/assets/20995691/19034133/986b1786-896a-11e6-832c-ddf27f22e9dc.png)

3)Change this Dosis font to Open sans
![2016-10-03 13 09 36](https://cloud.githubusercontent.com/assets/20995691/19034166/c63f9f42-896a-11e6-9164-eb754fb3d547.png)

as we have here
![2016-10-03 13 11 10](https://cloud.githubusercontent.com/assets/20995691/19034198/e2a89f9e-896a-11e6-9b01-94efc4b8b286.png)

4)Replace "Rivermark is your partner for..." to "DCU is your partner for..."
![2016-10-03 13 11 53](https://cloud.githubusercontent.com/assets/20995691/19034230/151c6988-896b-11e6-9aff-a1aa5a9ae9b3.png)

5)Make this section as we have in layout
![2016-10-03 13 13 09](https://cloud.githubusercontent.com/assets/20995691/19034253/307aebaa-896b-11e6-9e1a-ea1e03fdab7f.png)

and add here video from main page of GF site https://beta.growthfountain.com/

6)Here  should be letter spacing 100
![2016-10-03 13 17 31](https://cloud.githubusercontent.com/assets/20995691/19034388/ccdc2bf8-896b-11e6-9ba3-c99c07a9c881.png)

7)Make bold headings on the Education page
![2016-10-03 13 18 51](https://cloud.githubusercontent.com/assets/20995691/19034425/06a4af4a-896c-11e6-8d90-7b32fcce2b68.png)

8)Don`t make this step boxes on the all calculators like a buttons! Leave here design which we have on GF site. And add for them appropriate color - # 66a366
![2016-10-03 13 22 03](https://cloud.githubusercontent.com/assets/20995691/19034490/66f1df1c-896c-11e6-84d1-e9f61c47bf05.png)

9)Change font of Title to Open sans
![2016-10-03 13 24 21](https://cloud.githubusercontent.com/assets/20995691/19034549/c69733f4-896c-11e6-913a-8af7ff9958fa.png)

10) Add here appropriate colors
![2016-10-03 13 25 32](https://cloud.githubusercontent.com/assets/20995691/19034575/ea157f98-896c-11e6-836f-931774a1a491.png)

As we have here (in layout)
![2016-10-03 13 26 32](https://cloud.githubusercontent.com/assets/20995691/19034602/05dc0ef4-896d-11e6-8526-f45864edf20b.png)

11)please add to this section parallax effect 
![2016-10-03 14 55 57](https://cloud.githubusercontent.com/assets/20995691/19036623/9a76b8a0-8979-11e6-8e6e-1843830e7994.png)

12)Make the locality of the text in this box like in the layout
![2016-10-03 13 27 28](https://cloud.githubusercontent.com/assets/20995691/19034624/30272e28-896d-11e6-9393-7fe2fcf9f463.png)

And change color to # 66a366

See layouts for DCU here :
https://www.dropbox.com/home/Maria%20Wireframes/White%20label%20sites/DCU?d=1

**Comment by NewRoman** [comment]
@MariaKravchuk 
I need full screen size background for add paralax effect in this point
11)please add to this section parallax effect

**Comment by NewRoman** [comment]
@MariaKravchuk 
point 1-6, 9 ready 
http://growthfountain-dcu.s3-website-us-east-1.amazonaws.com/

**Comment by NewRoman** [comment]
@MariaKravchuk 
point 7,8, 11 ready(1 point have been fixed)
http://growthfountain-dcu.s3-website-us-east-1.amazonaws.com/

**Comment by NewRoman** [comment]
@MariaKravchuk 
please, show me which psd I should to use for fixed 11 point?

**Comment by MariaKravchuk** [comment]
@NewRoman see here https://www.dropbox.com/home/Maria%20Wireframes/White%20label%20sites/DCU?preview=DCU+index.psd

also add to ABOUT Us section on DCU site this text
[GrowthFountain DCU About Us document.docx](https://github.com/vladyslav2/gfwhitelabels/files/509351/GrowthFountain.DCU.About.Us.document.docx)

**Comment by NewRoman** [comment]
@MariaKravchuk 
I've made mistake in previous post, there I wanted that you show me psd for 12 but not 11 point.
12)Make the locality of the text in this box like in the layout

**Comment by NewRoman** [comment]
@MariaKravchuk 
10 ready
http://growthfountain-dcu.s3-website-us-east-1.amazonaws.com/api/campaign/68

**Comment by NewRoman** [comment]
@MariaKravchuk 
item 12 ready
http://growthfountain-dcu.s3-website-us-east-1.amazonaws.com/api/campaign/124

**Comment by NewRoman** [comment]
@MariaKravchuk all point done
