### ISSUE TITLE
Jeanna D`Arc

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#942]
@NewRoman @leonstiel 
1) Change this text to open sans font   
![2016-10-18 19 32 54](https://cloud.githubusercontent.com/assets/20995691/19487089/dee14964-9569-11e6-96e6-3e069e8ffdee.png)

2)Make this title bold
![2016-10-18 19 37 46](https://cloud.githubusercontent.com/assets/20995691/19487210/75533204-956a-11e6-8d6f-61b8b3cb60c9.png)

3)Make all headings bold (like in Rivermark page)
![2016-10-18 19 39 44](https://cloud.githubusercontent.com/assets/20995691/19487362/28e475a8-956b-11e6-88f0-0c64d69af1f1.png)

in general you can take typography from Rivermark

4)make this headings in black color
![2016-10-18 19 48 35](https://cloud.githubusercontent.com/assets/20995691/19487523/ef1ef216-956b-11e6-8559-af6951dc92b1.png)

 

See layouts for JD here
https://www.dropbox.com/home/Maria%20Wireframes/White%20label%20sites/Jeanna%20D'Arc?preview=JD+index.psd

**Comment by NewRoman** [comment]
@MariaKravchuk 
all points ready
