### ISSUE TITLE
ESTABLISHED BUSINESS VALUATION CALCULATOR

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#943]
@OstapL 
Please make here bold font for "the last twelve months"
![2016-10-03 13 49 06](https://cloud.githubusercontent.com/assets/20995691/19035129/3d70755a-8970-11e6-90e6-e6c6587745c6.png)

https://beta.growthfountain.com/calculator/establishedBusiness/step-2

And make here bold font for "the next twelve months"
![2016-10-03 13 50 38](https://cloud.githubusercontent.com/assets/20995691/19035148/642b873e-8970-11e6-9ece-205c47da032b.png)

https://beta.growthfountain.com/calculator/establishedBusiness/step-3

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #963
