### ISSUE TITLE
Letter spacing for H1

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#944]
@OstapL 
Make the same letter spacing for H1 on the Main page and on the Company page

![2016-10-03 13 51 55](https://cloud.githubusercontent.com/assets/20995691/19035197/b73ed9bc-8970-11e6-90d5-5cc38cfbe927.png)
![2016-10-03 13 51 42](https://cloud.githubusercontent.com/assets/20995691/19035203/be0f8296-8970-11e6-9967-a1c6f7ddeb51.png)

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #964
