### ISSUE TITLE
Scroll menu on Company page

### ISSUE THREAD

**Issue by MariaKravchuk** [vladyslav2/gfwhitelabels#969]
@OstapL 
Please fix this corners on highlighting 
![2016-10-04 19 59 30](https://cloud.githubusercontent.com/assets/20995691/19084081/b6cd74fe-8a6d-11e6-9b1d-bfffc0dfcc19.png)

And made this menu without any moving

**Comment by OstapL** [comment]
@MariaKravchuk 
Fixed #988 
http://growthfountain-ostap.s3-website-us-east-1.amazonaws.com/api/campaign/124
