### ISSUE TITLE
Profile Page Expects Telephone To Be An Integer

### ISSUE THREAD

**Issue by arthuryip723** [vladyslav2/gfwhitelabels#976]
@vladyslav2 
![screen shot 2016-10-04 at 2 39 40 pm](https://cloud.githubusercontent.com/assets/1624001/19087555/6edec148-8a40-11e6-928e-6819e3a89da1.png)

**Comment by vladyslav2** [comment]
Fixed
please take a look

**Comment by arthuryip723** [comment]
sure
