### ISSUE TITLE
campaign setup/preview: team member & advisor bio 

### ISSUE THREAD

**Issue by morganm24** [vladyslav2/gfwhitelabels#979]
for team members and advisors. please do not limit characters

![image](https://cloud.githubusercontent.com/assets/21366183/19087511/430e6be0-8a40-11e6-8a97-22aaa4b6db66.png)

for preview format:  limit all bios to 3 lines. if there is additional text, provide link to read more. (if no additional text then link should NOT appear)
![image](https://cloud.githubusercontent.com/assets/21366183/19088050/74d3eeb4-8a42-11e6-919c-292224951b0f.png)

**Comment by MariaKravchuk** [comment]
@OstapL here I added "Read more" for BIO

https://www.dropbox.com/home/Maria%20Wireframes/Company%20page?preview=COMPANY+PAGE.psd

**Comment by MariaKravchuk** [comment]
@arthuryip723 please do not limit characters (on Specifics page) and add "Read more" button like I made here 
![2016-10-19 15 08 45](https://cloud.githubusercontent.com/assets/20995691/19518105/f85dbc70-960d-11e6-9558-5ff5d3b8d0e3.png)
